### ISSUE TITLE
Cannot run the example on https://www.howtographql.com/

### ISSUE THREAD

**Issue by jcornaz** [howtographql/howtographql#1003]
On this page: https://www.howtographql.com/

> Never tried GraphQL before?
> Time to run your first query in the Playground…

I click "run":

```
{
  "error": "Project has exceeded its limits: number of requests (disables all requests)",
  "code": 6000
}
```

> That was easy, wasn't it?

Hem, not really...

**Comment by pwnreza** [comment]
Still not fixed?
Got the same issue. Only commenting to inform you.

![Bildschirmfoto 2020-02-17 um 17 05 40](https://user-images.githubusercontent.com/861695/74669751-16608000-51a8-11ea-8985-eaa5d5aa4541.png)

**Comment by Jolg42** [comment]
Closing as it seems the example was removed 🤷‍♂️
