### ISSUE TITLE
OR is not defined

### ISSUE THREAD

**Issue by LonelyDaoist** [howtographql/howtographql#1005]
**Course:** Graphql + Node
**Chapter:** Filtering, Pagination & Sorting
**Problem:** in the following code fragment, I get OR is not defined:
```
async function feed(parent, args, context, info) {
  const where = args.filter ? {
    OR: [
      { description_contains: args.filter },
      { url_contains: args.filter },
    ],
  } : {}

  const links = await context.prisma.links({
    where
  })
  return links
}
```
So I checked the generated **_prisma.schema.js_** and indeed it wasn't defined in _LinkWhereInput_
I don't know if this has happened to other people or if there's actually a problem with my setup.
**Possible solution:**
```
async function feed(root,args,context){
    const linksFilteredByUrl = await context.prisma.links({ where: {url_contains: args.filter} });
    const linksFilteredByDescription = await context.prisma.links({ where: {description_contains: args.filter} });
    return linksFilteredByDescription.concat(linksFilteredByUrl);
}
```
but this solution will cause duplication problems
Your thoughts are appreciated.
Cheers,

**Comment by bobinush** [comment]
It is disabled in Mongo according to this: https://github.com/prisma/prisma/issues/3897

**Comment by TasinIshmam** [comment]
Closing this since the tutorial has updated to Prisma2 (whereas this issue is relevant to Prisma1)
