### ISSUE TITLE
Broken download url for backend server in react-urql tutorial

### ISSUE THREAD

**Issue by sohara** [howtographql/howtographql#1017]
The url given to download the server code returns a 400. The tutorial says to use the following shell commands:

```sh
curl https://codeload.github.com/howtographql/react-urql/tar.gz | tar -xz --strip=1 react-urql/server
```
However that url returns a 400. Either the code needs to be posted there or the URL needs to be corrected.

**Comment by sohara** [comment]
Here's the relevant line in the source code: https://github.com/howtographql/howtographql/blame/master/content/frontend/react-urql/1-getting-started.md#L306

**Comment by sohara** [comment]
cc @kitten

**Comment by kitten** [comment]
Just confirmed that the link isn't working correctly. The tar command is also not working anymore. I'll check what we'll have to replace it with
