### ISSUE TITLE
graphql-elixir tutorial using deprecated option (--no-brunch)

### ISSUE THREAD

**Issue by Francesco-Lanciana** [howtographql/howtographql#1022]
Hey I noticed that the graphql-elixir tutorial (first page) requests that you make app using the --no-brunch option. This was replaced with the --no-webpack option (after brunch was replaced with webpack). 

Here is the PR describing this replacement: https://github.com/phoenixframework/phoenix/pull/2779

This resource has been hugely helpful so far, thanks for all the effort :)

**Comment by burrelle** [comment]
@Francesco-Lanciana I made a PR for all the updates to the tutorial #986

**Comment by maartenvanvliet** [comment]
Thx!
