### ISSUE TITLE
Ruby: `session` cannot be accessed inside a Resolver

### ISSUE THREAD

**Issue by nspriego** [howtographql/howtographql#104]
Going through the Ruby track tutorial - in chapter 4 under `Authentication` there is this instruction:

>We also need to update our signinUser resolver, so it also stores the token in session:

    class Resolvers::SignInUser < GraphQL::Function
      # ...code

      def call(_obj, args, ctx)
        # ...code

        crypt = 
    ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base.byteslice(0..31))
        token = crypt.encrypt_and_sign("user-id:#{ user.id }")

        session[:token] = token

        # ...code
      end
    end

When adding the line `session[:token] = token` to this resolver I am getting the error `NameError (undefined local variable or method 'session' for #<Resolvers::SignInUser:0x007fdb019ae730>)` when trying to log in.

**Comment by RStankov** [comment]
It should be `context[:session][:token]`. Will fix this.
