### ISSUE TITLE
Incorrect schema in GQL tutorial in video (Core Concepts)

### ISSUE THREAD

**Issue by Manimall** [howtographql/howtographql#1043]
Hey guys!
First, thank you very much for this great tutorial
Second, i found this a little bit incorrect (in my opinion) - 

![2019-12-01_12-07-14](https://user-images.githubusercontent.com/2580719/69911929-91c95580-1433-11ea-8532-982ff6cf1df3.png) 

Well, in my opinion, it should like like this - 

```js
{
  allPersons {
    name
    posts {
      title
    }
  }
}
```

Also, sorry for my English - there might be mistakes=)

**Comment by Manimall** [comment]
Woow.... It's alright, but problems with tabulation=)

**Comment by Glyphack** [comment]
Hey @Manimall 
So this should be closed right?

**Comment by Manimall** [comment]
yeah
