### ISSUE TITLE
Create-react-app global install no longer supported

### ISSUE THREAD

**Issue by rraabe** [howtographql/howtographql#1045]
In the React-Apollo [tutorial](https://www.howtographql.com/react-apollo/1-getting-started/) `yarn global create-react-app` is no longer supported. See the React [Docs](https://create-react-app.dev/docs/getting-started/). It may also be helpful to link to this [post](https://stackoverflow.com/questions/59188624/template-not-provided-using-create-react-app) if users are having issues with old installs.

**Comment by ShatterPlayer** [comment]
The problem with global installs of create-react-app in React-Apollo tutorial has been resolved. [Fix pull request](https://github.com/howtographql/howtographql/pull/1056) was approved.

**Comment by anku255** [comment]
@ShatterPlayer Thanks for the reminder. I am closing this issue.
