### ISSUE TITLE
Fix link in tutorial

### ISSUE THREAD

**Issue by Liroyd** [howtographql/howtographql#1048]
Link is not correct in https://www.howtographql.com/graphql-java/2-queries/

> To add GraphiQL, copy the example index.html from GraphiQL’s GitHub repo 

Just try to open it - https://github.com/graphql/graphiql/blob/master/example/index.html
It doesn't work. 
Seems like correct one is - https://github.com/howtographql/graphql-java/blob/master/src/main/webapp/index.html

And it's not needed to change any styles
> and replace the paths to graphiql.css and graphiql.js from

**Comment by anku255** [comment]
Hey @Liroyd 👋

Thank you for reporting this. I will fix the link asap.
