### ISSUE TITLE
I would like to build a site like this, where should I start?

### ISSUE THREAD

**Issue by ztana** [howtographql/howtographql#1053]
I want to build a workshop site like this, which may a lot simpler, I like the list style a lot, could you tell me where I can start? I tried pull the git and run locally but failed with a lot of errors like
`../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
15: error: no member named 'ForceSet' in 'v8::Object'`

I think maybe because my yarn and node version, but I'm not sure.

**Comment by hrnagesh** [comment]
I am experiencing a similar issue.

error C2039: 'ForceSet': is not a member of 'v8::Object'
nan\nan_converters_43_inl.h(22): error C2664: 'v8::Local<v8::Boolean> v8::Value::ToBoolean(v8::Isolate *) const': cannot convert argument 1 from 'v8::Local<v8::Context>' to 'v8::Isolate *' (compiling source file ..\src\deasync.cc)

**Comment by ztana** [comment]
I did successfully running it by downgrade node to v6.3.0
