### ISSUE TITLE
graphql-js - Authentication tutorial issue

### ISSUE THREAD

**Issue by vncastanheira** [howtographql/howtographql#1057]
![firefox_0pfI6EfFOs](https://user-images.githubusercontent.com/1210284/74244677-8fe80200-4cc0-11ea-849c-a42e17643200.jpg)

[This section](https://www.howtographql.com/graphql-js/6-authentication/) of the tutorial gives the following error:

```
Errors:

  Link
    × The field `postedBy` must provide a relation link mode. Either specify it on this field or the opposite field. Valid values are: `@relation(link: INLINE)`

  User
    × The field `links` must provide a relation link mode. Either specify it on this field or the opposite field. Valid values are: `@relation(link: INLINE)` 

Deployment canceled. Please fix the above errors to continue deploying.        
Read more about deployment errors here: https://bit.ly/prisma-force-flag  
```

**Comment by masonlouchart** [comment]
I think it is fixed since I completed this chapter without issue.

**Comment by masonlouchart** [comment]
After a better look at your issue we can see the tutorial was telling to put GraphQL types into the Prisma data model file what can't work.
