### ISSUE TITLE
🗣 Call for Maintainers

### ISSUE THREAD

**Issue by nikolasburk** [howtographql/howtographql#1070]
This repository is currently unmaintained and we're looking for community contributors to help clean up issues and merge existing PRs. 

If you're interested in helping out, [please reach out](mailto:burk@prisma.io).

**Comment by Urigo** [comment]
We ([The Guild](https://github.com/the-guild-org/)) would love to help!

Maybe if it's currently unmaintained we can start with a public roadmap?

**Comment by anku255** [comment]
Hi @Urigo 👋

I currently have maintainer access for this repo. Unfortunately, I haven't been able to contribute much in the past few weeks. 

I am with you on the public roadmap idea. Let's discuss that and thanks for your help.

**Comment by armstrongl** [comment]
I'd love to help out too! I'm a technical writer/editor with some basic GraphQL experience. Let me know how I can help 😊

**Comment by guledali** [comment]
@nikolasburk  Why are you guys not using redwoodjs for the tutorial?

**Comment by mojo706** [comment]
Hi, what's the progress on the public roadmap or contributions?

**Comment by ashwamegh** [comment]
@nikolasburk I have sent you the mail regarding this 👍

**Comment by jvmazagao** [comment]
I want to contribute.

**Comment by killvung** [comment]
Can you put me in?

**Comment by TasinIshmam** [comment]
Hi, I'd love to help. @nikolasburk, I've sent you an email about this.

**Comment by nikolasburk** [comment]
Closing this issue since @TasinIshmam has been doing great work as a lead maintainer recently.
