### ISSUE TITLE
ui overflow bug in sidebar

### ISSUE THREAD

**Issue by timsuchanek** [howtographql/howtographql#109]
<img width="318" alt="screen shot 2017-07-14 at 11 24 18 am" src="https://user-images.githubusercontent.com/1094804/28206696-35607800-6887-11e7-90be-67130f64d3ec.png">

**Comment by angly-cat** [comment]
I take it that this sidebar's top fader should fade all the content underneath? It kinda doesn't make much sense to me for fader to fade just categories and bonus path. How is it indented to work?
