### ISSUE TITLE
Adding a Count to Feed results in Error: Cannot return null for non-nullable field Query.feed 

### ISSUE THREAD

**Issue by raleigh9123** [howtographql/howtographql#1090]
I am in Step 8 - Filtering, Pagination & Sorting and I am encountering the following error

" Error: Cannot return null for non-nullable field Query.feed. "

I am following along with this tutorial and typing my code as I go. I encountered this error on the last step when you change the schema to allow a " count " property on the Feed. Now whenever I run ANY query, I receive the above error. I am just learning graphql, and this error is very confusing. I copied the code directly from the tutorial and still received the error, so I am lost on how to fix.

I then run the following query in the GraphQl playground.
```
query {
 feed {
  count
  links {
    id
    description
    url
   }
  }
}
```
and receive in the playground
```
{
  "data": null,
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Query.feed.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "feed"
      ]
    }
  ]
}
```

src/schema.graphql
```
type Query {
  info: String!
  feed(filter: String, skip: Int, first: Int, orderBy: LinkOrderByInput): Feed!
}

type Feed {
  links: [Link!]!
  count: Int!
}
```

src/resolvers/Query.js
```
async function feed(parent, args, context) {
    const where = args.filter
        ? {
            OR: [
                { description_contains: args.filter },
                { url_contains: args.filter },
            ],
        }
        : {};

    const links = await context.prisma.links({
        where,
        skip: args.skip,
        first: args.first,
        orderBy: args.orderBy,
    });
    const count = await context.prisma
        .linksConnection({
            where,
        })
        .aggregate()
        .count();
    return {
        links,
        count,
    };
}
```

**Comment by jvmazagao** [comment]
@raleigh9123 I found the error, it just a js mistake, and I had it too. 

Probably you just deleted the
`module.exports {
 feed
}`
