### ISSUE TITLE
update to Prisma 2

### ISSUE THREAD

**Issue by dakkafex** [howtographql/howtographql#1091]
The documentation on the node/yoga/prisma tutorial is extremely outdated, full of broken links and the yoga project seems to be abandoned.

**Comment by w3bdesign** [comment]
https://github.com/howtographql/howtographql/issues/1077

**Comment by yashguptaz** [comment]
👍🏼 
It is also using legacy Prisma Migrate
https://www.prisma.io/docs/concepts/components/prisma-migrate

**Comment by TasinIshmam** [comment]
This has been fixed. Closing!
