### ISSUE TITLE
No correct answer available for the quiz

### ISSUE THREAD

**Issue by sourabhbagrecha** [howtographql/howtographql#1108]
If you log on to the tutorial for GraphQL and Node [here](https://www.howtographql.com/graphql-js/5-connecting-server-and-database/) you will find that in the quiz section where you can unlock the next chapter, the quiz has no correct answer in it. Please see to it. 
![image](https://user-images.githubusercontent.com/27056663/86998473-17816080-c1ce-11ea-9a3c-9ffb948fc0b9.png)

**Comment by anand-kashyap** [comment]
yes I faced this too

**Comment by ShatterPlayer** [comment]
The problem seems to be in [this file](https://github.com/howtographql/howtographql/blob/master/content/backend/graphql-js/5-connecting-server-and-database.md) in the column correctAnswer. There is no answer with index 4. I'm going to fix this issue.
