### ISSUE TITLE
Can we still use Graphcool?

### ISSUE THREAD

**Issue by jseminck** [howtographql/howtographql#1116]
Hello, today I started following the react-relay tutorial, but I quickly got stuck when trying to log in to graph.cool. Neither the Github or Google logins were working. So, I figured I would just create an account at https://www.graph.cool/ when I saw the notice banner on the top: 

_It’s so hard to say goodbye! Graphcool will be sunsetted July 1, 2020. Learn more:  Graphcool Sunset Notice._

I'm a bit confused now... can we still use graph.cool or not? At least so far, I was not able to find a way to log in to the application, so I am a bit stuck. Or is the tutorial outdated and awaiting some update?

Thanks for the effort!

**Comment by TasinIshmam** [comment]
Sorry for the super-duper delayed response. As you guessed, the tutorial is outdated and graphcool is no longer live.
