### ISSUE TITLE
Duplicate commands in Updating Prisma Client (Auth section of graphql-js)

### ISSUE THREAD

**Issue by InfiniteVerma** [howtographql/howtographql#1120]
In the Updating Prisma Client section of Authentication Chapter (Graphql-Node tutorial), there seems to be a duplicate command. 
Here, the first command asks for the migration name while in the second we enter it along as a flag. 
<img src="https://user-images.githubusercontent.com/45547198/88473622-175ac200-cf3d-11ea-99d3-59458e0b3bee.png" width=500>

**Comment by TasinIshmam** [comment]
This has been fixed, thanks for bringing it up!
