### ISSUE TITLE
Wrong answer at page https://www.howtographql.com/graphql-js/6-authentication/

### ISSUE THREAD

**Issue by VinitTomar** [howtographql/howtographql#1144]
For question
Which HTTP header field carries the authentication token?
correction answer is "Authorization", but while selecting this option is marked as wrong. 

Here is [preview](https://ibb.co/02hN71J)

**Comment by ShatterPlayer** [comment]
Issue has been resolved in pull request #1206.

**Comment by VinitTomar** [comment]
Fixed. Hence closing.
