### ISSUE TITLE
Connectors

### ISSUE THREAD

**Issue by ChuksFestus** [howtographql/howtographql#115]
i don't know why i keep getting this 
```(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: failed to connect to server [mlab.com:61012] on first connect [MongoError: connect ETIMEDOUT 107.21.227.111:61012]
(node:6644) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by marktani** [comment]
Hey @ChuksFestus could you explain in detail what you are trying to do? 🙂 
What track/chapter/... are you currently at, what's the specific command you're running, what's your `node` and `npm` versions and what's the OS you're on?

Thanks!

**Comment by ChuksFestus** [comment]
/graphql-js/4-connectors/ 
Set up MongoDB
am trying to commect to mlab but i keep getting that error
node -v "8"
npm -v "5.3"
and i use windows 8.1

**Comment by marktani** [comment]
This looks to be a deprecation warning when you don't have a catch clause for all your promises. I think as part of this tutorial, we can accept the warning fow now 🙂 
Here's more information: https://stackoverflow.com/a/41180264/1176596
