### ISSUE TITLE
GraphQL + Apollo wrong instructions server setup

### ISSUE THREAD

**Issue by ashishnagpal2498** [howtographql/howtographql#1169]
I cloned the server files using "curl" command. After that I installed the packages using yarn install.
When I tried to deploy prisma, It asks for setting up new database or using existing database with 3 options provided
1. MySQL
2. PostGres
3. MongoDB
No such option as Demo server was provided.
![image](https://user-images.githubusercontent.com/36301481/95011974-80079e80-0652-11eb-8af7-8df63526e3a3.png)
Also Once 1 selected some option, I am not able to go back to some other option as it says
"Could not connect to server at http://localhost:4466. Please check if your server is running."
![image](https://user-images.githubusercontent.com/36301481/95012013-be04c280-0652-11eb-9868-4b3f02bcc3a4.png)

**Comment by jvmazagao** [comment]
Hello, After you run `yarn prisma deploy` you will see the exact shell above
![Screen Shot 2020-10-14 at 20 55 30](https://user-images.githubusercontent.com/22477816/96057613-b669c880-0e5f-11eb-8b05-96f9ebfb95fa.png)

after press the arrow down in the second option, you will see the demo server, and you will be able to create an account or login into an existent prisma account, after that you can start the server

**Comment by ruheni** [comment]
Hi @ashishnagpal2498 👋🏾

It seems you're using Prisma 1. The React-Apollo and Node tutorials were updated to use Prisma 2. Kindly try them out and let us know if you run into any issues. We'd love to hear your feedback. 🙂

**Comment by TasinIshmam** [comment]
Hi, closing this because this refers to the outdated Prisma 1 version of the tutorial.
