### ISSUE TITLE
Bug at Filtering, Pagination and Sorting question

### ISSUE THREAD

**Issue by rsousaj** [howtographql/howtographql#1180]
Hi guys, sorry if it's not the right place to report it. When I tried to ask the chapter question, looks like something went wrong. I already checked here what is the right answer and everything looks fine.

![screenshot02](https://user-images.githubusercontent.com/12521138/97028883-154fd180-1533-11eb-9b2d-2e2fe4bddbd6.png)

**Comment by TasinIshmam** [comment]
Has been fixed. Closing.
