### ISSUE TITLE
async used in feed: but not in post:

### ISSUE THREAD

**Issue by maxxafari** [howtographql/howtographql#1184]
is there a reason for Query feed: to use async but not  Mutation Post:? 

In my testing both seem to work. But while reading its a bit confusing why async is used in one case and not in the other.
```
feed: async (parent, args, context) => {
      return context.prisma.link.findMany()
```
```
 post: (parent, args, context) => {
      const newLink = context.prisma.link.create({
...
return newLink
```

**Comment by TasinIshmam** [comment]
Thanks for bringing this up. Fixed!
