### ISSUE TITLE
tutorial inconsistences: "https://www.howtographql.com/graphql-js/2-queries/"

### ISSUE THREAD

**Issue by moigithub** [howtographql/howtographql#122]
"Now you just have to pass these resolvers when building the schema object with makeExecutableSchema:"

it dont specify where makeExecutableSchema is imported (only on source code), for a newbie like me spent almost 20min trying to figure out

import { makeExecutableSchema } from 'graphql-tools';

**Comment by mairatma** [comment]
@moigithub can you explain better what you felt was missing to understand this step? I checked the tutorial and right below this phrase it shows the source code where the code has to be added, with the file path on the top, like this:

<img width="922" alt="screen shot 2017-07-17 at 9 28 25 am" src="https://user-images.githubusercontent.com/5216049/28267882-6cf9312e-6ad2-11e7-99ed-74182ffc1cc4.png">

I could add the file path in the instruction phrase too, but I usually avoid it when the code with the path is right below it, as it seems more like extra overhead. Just want to understand better what made it confusing for you, so I don't end up changing the wrong thing trying to fix it :)

**Comment by moigithub** [comment]
hi, i know is specified on the source code (figured out after 20ish minutes
reading, source code link is small and greyish)

i knew makeExecutableSchema function had to be declared somewhere.. but i
couldnt find through all the tutorial,.. thats why confused.

...i think would be clearer if include on the tutorial the import module
line

const {makeExecutableSchema} = require('graphql-tools');

-----------
similar thing happend on:
Testing with playground

const {graphqlExpress, graphiqlExpress} = require('graphql-server-express');
// ...

app.use('/graphiql', graphiqlExpress({
  endpointURL: '/graphql',}));


i knew i defined and "generated" a schema, but how do i "connect" that
schema with that piece of code ?
after first experience,, i knew i had to check the source code.. but for a
starter i think the current code provided was too much

const {graphqlExpress, graphiqlExpress} = require('graphql-server-express');
>
import schema from './schema'

// ...
>
> app.use('/graphql', bodyParser.json(), graphqlExpress({schema}));
>


> app.use('/graphiql', graphiqlExpress({
>   endpointURL: '/graphql'
> }));


soo im wondering IF its possible to make a "simpler" code, probably with
just static data
without subscription/ mongodb/ authentication (of course after learning the
basics, an example with all those would be/ is awesome, but for a noobie
its overwhelming )

... from a noobie perspective :)

2017-07-17 7:33 GMT-05:00 Maira Bello <notifications@github.com>:

**Comment by marktani** [comment]
Hey, I think adding the `makeExecutableSchema` require statement would be helpful in this situation 🙂 I think this is the best tradeoff between simplicity and clarity here, but please share your point of views

**Comment by marktani** [comment]
I merged the PR and close this issue. Please let us know if you have any other questions, @moigithub!
