### ISSUE TITLE
graphql chapter 5 wrong next chapter

### ISSUE THREAD

**Issue by bverhoeve** [howtographql/howtographql#1228]
On [Chapter 5 of the GraphQL + Node tutorial](https://www.howtographql.com/graphql-js/5-connecting-server-and-database/) the Next Chapter button links to Chapter 7 (subscriptions) instead of Chapter 6.

I'd expect that it would link to Chapter 6 though.

I'd update the link myself, but I don't entirely know how the site is built up. Where's the link to the next chapter generated?

**Comment by remuspoienar** [comment]
i initially stumbled upon part 6 ,then went to do the full tutorial , ano noticed it was not there. [Here is the link ](https://www.howtographql.com/graphql-js/6-authentication/)

**Comment by TasinIshmam** [comment]
Has been fixed. Closing.
