### ISSUE TITLE
Missing Proxy field in package.json: create react app tries to hit localhost/graphql endpoint while making queries to graphcool

### ISSUE THREAD

**Issue by amite** [howtographql/howtographql#124]
Create React App will not allow direct request to the graphcool simple endpoint and keep returning 404 errors unless you add a proxy field to your package.json and restart your application. The value of the proxy field should be the full graphcool api endpoint url.﻿

```json
{
  "name": "hackernews-react-apollo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^15.6.1",
    "react-apollo": "^1.4.3",
    "react-dom": "^15.6.1"
  },
  "devDependencies": {
    "react-scripts": "1.0.10"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "proxy": "https://api.graph.cool/full-endpoint-url"
}
```

**Comment by nikolasburk** [comment]
Hey @amite, thanks a lot for opening this issue! Can you specify a bit more what exactly you mean? Are you running into issues when you're not including this `proxy` field? If so, what kind of issues do you see?

**Comment by nikolasburk** [comment]
Hey @amite, thanks a lot for opening this issue! Can you specify a bit more what exactly you mean? Are you running into issues when you're not including this `proxy` field? If so, what kind of issues do you see?

**Comment by nikolasburk** [comment]
I'm closing this issue assuming it was solved by the recent update to the React & Apollo tutorial. Please let me know if this is still a problem @amite and I will take a look again :)
