### ISSUE TITLE
[graphql-python] 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by richardoey** [howtographql/howtographql#1242]
I follow this tutorial [graphql-python/4-authentication](https://www.howtographql.com/graphql-python/4-authentication/)
Dependencies:

Django==2.2.17
django-filter==2.0.0
django-graphql-jwt==0.2.1
graphene==2.1.8
graphene-django==2.2.0
graphql-core==2.3.2
graphql-relay==2.0.1
PyJWT==1.7.1 _(I found error: module 'jwt' has no attribute 'ExpiredSignature' when use PyJWT==2.0.0, and fix it after downgraded it)_

and getting this error while doing
GraphQL Query:
```
mutation {
  tokenAuth(username: "joanatas", password: "123456A!"){
    token
  }
}
```
Error:
```
{
  "errors": [
    {
      "message": "'str' object has no attribute 'decode'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "tokenAuth"
      ]
    }
  ],
  "data": {
    "tokenAuth": null
  }
}
```

I fix this problem by removing `.decode('utf-8')` in the graphql_jwt/utils.py.
From:
```
def jwt_encode(payload, context=None):
    return jwt.encode(
        payload,
        jwt_settings.JWT_SECRET_KEY,
        jwt_settings.JWT_ALGORITHM,
    ).decode('utf-8')
```

to be:

```
def jwt_encode(payload, context=None):
    return jwt.encode(
        payload,
        jwt_settings.JWT_SECRET_KEY,
        jwt_settings.JWT_ALGORITHM,
    )
```
My question is, **is there any drawbacks or side effects after I do this** or is there any better way? Thank you.

**Comment by VerzCar** [comment]
Hi, have the same issue here.

My Dependencies:
Django = "^3.1.3"
django-cors-headers = "^3.5.0"
django-graphql-jwt = "^0.3.1"
django-split-settings = "^1.0"
django-axes = "^5.9"
django-csp = "^3.7"
django-health-check = "^3.16"
django-http-referrer-policy = "^1.1"
django-feature-policy = "^3.5"
django-stubs-ext = "^0.1"

graphene = "^2.1.8"
graphene-django = "^2.13.0"
graphql-core = "^2.3.2"
graphql-relay = "^2.0.1"

Any update?

**Comment by richardoey** [comment]
I still use the same approach to fix this problem. Try to remove `.decode('utf-8')` in the graphql_jwt/utils.py.
From:
```
def jwt_encode(payload, context=None):
    return jwt.encode(
        payload,
        jwt_settings.JWT_SECRET_KEY,
        jwt_settings.JWT_ALGORITHM,
    ).decode('utf-8')
```

to be:

```
def jwt_encode(payload, context=None):
    return jwt.encode(
        payload,
        jwt_settings.JWT_SECRET_KEY,
        jwt_settings.JWT_ALGORITHM,
    )
```

the error comes when your object actually have already been encoded, so you don't have to do it twice.
reference: https://stackoverflow.com/questions/28583565/str-object-has-no-attribute-decode-python-3-error

**Comment by clebio** [comment]
This comment: https://github.com/flavors/django-graphql-jwt/issues/241#issuecomment-758478589

suggests that you can use PyJWT version 1.7.0:

```sh
pip install PyJWT==1.7.0
```

Which would suggest that the getting started guide should be updated to include that:
```sh
pip install PyJWT==1.7.0 django==2.1.4 graphene-django==2.2.0 django-filter==2.0.0 django-graphql-jwt==0.1.5
```
https://www.howtographql.com/graphql-python/1-getting-started/
