### ISSUE TITLE
× Unhandled Rejection (Error): Argument id for data.postedBy.connect.id must not be null. Please use undefined instead.

### ISSUE THREAD

**Issue by somyamehta24** [howtographql/howtographql#1243]
Same error I solved previously on the graphql playground but as I am trying to pass the mutation to create a new link it's giving this error  again[](url)
![2020-12-31 (34)](https://user-images.githubusercontent.com/62494153/103397562-f0915f00-4b5e-11eb-87f4-e606ced55150.png)

**Comment by enigmatikme** [comment]
Same for me too.

**Comment by Nyamador** [comment]
Is there anything being done about this?

**Comment by KemPavel** [comment]
still the same error occurs when trying to use mutation

**Comment by TadejPolajnar** [comment]
You have to be authorized to mutate. I think its a bug, mutation should be open at the start and it should be changed later in the tutorial.
[This workaround](https://github.com/howtographql/react-apollo/issues/110) solves this issue.

**Comment by TadejPolajnar** [comment]
Mutation requires authorization. I think it is a bug, mutation should be open at that point and changed later in the next chapter.

I recommend you to continue with the [next chapter](https://www.howtographql.com/react-apollo/5-authentication/) where you implement Authorization. Then it should work! 🙂

**Comment by mosoriob** [comment]
I agree with @TadejPolajnar The resolver in the server expects the `url`, `description` and `postedBy`. However, the frontend in [section 3: Mutations: Creating Links](https://www.howtographql.com/react-apollo/3-mutations-creating-links/) doesn't provide the user.

The resolver:

```js
async function post(parent, args, context, info) {
  const { userId } = context;

  const newLink = await context.prisma.link.create({
    data: {
      url: args.url,
      description: args.description,
      postedBy: { connect: { id: userId } }
    }
  });
  context.pubsub.publish('NEW_LINK', newLink);
  return newLink;
}
```

**Comment by MadaShindeInai** [comment]
> Mutation requires authorization. I think it is a bug, mutation should be open at that point and changed later in the next chapter.


Thank you. Hope this helps.

**Comment by dmoore375** [comment]
Looking at the history, it seems that the server was originally open for posts without users. You can see the change in the tutorial in this diff: https://github.com/howtographql/howtographql/commit/2626d4d2d52b2a4dc1d452c4808ce60e1deecccb?short_path=10c99a2#diff-10c99a2b9f281c9294b7e07edee09694de686db66bf030017c26de5f849bae12
The old server code allowed for no user, while the new server code doesn't. In order to unbreak this tutorial, the server would need to be modified.

**Comment by cristiancota** [comment]
Since `post` mutation is expecting to insert a user for the new link created, you could force to use the existing user. In `server/src/Mutation.js`

```js
async function post(parent, args, context, info) {
  // const { userId } = context;
  const userId = 2;
  ...
}
```

That should work. If somehow you have a different userId in your database, use this query to get the actual id.

```graphql
query {
  feed(take:1) {
    links {
      postedBy {
        id
      }
    }
  }
}
```

**Comment by clebio** [comment]
Related:

* https://github.com/howtographql/howtographql/issues/1217
* https://github.com/howtographql/react-apollo/issues/110
* https://github.com/howtographql/howtographql/issues/1227

Though, also: issue 1070 says they need maintainers. 🤷🏻‍♂️

**Comment by dnhynh** [comment]
Ran into this issue as well. As people have mentioned it seems that it's because creating posts requires authentication but this isn't addressed till later. Perhaps changing the order in the tutorial to handle authentication first would be the best fix for addressing this issue.

**Comment by jakeecolution** [comment]
I second @Vicbouret. I was going to add this solution to the issue as well and got the correct response from the server.
