### ISSUE TITLE
GraphQL Node  backend is missing the authentication module in the tutorial.

### ISSUE THREAD

**Issue by fanyui** [howtographql/howtographql#1244]
Following the tutorial at [https://www.howtographql.com/graphql-js/5-connecting-server-and-database/](5-connecting-server-and-database) it shows that immediately after the connecting server and database is supposed to be the authentication module However this is not available there. For some reason I can see it in the readme file but not while following the tutorial. See image below.
<img width="1284" alt="Screen Shot 2021-01-03 at 18 50 02" src="https://user-images.githubusercontent.com/12346597/103485152-a0332f00-4df4-11eb-9c20-8d33371dedb7.png">
 Also there was a clear change in the file system which wasn't mentioned in the tutorial ie the splitting of the index.js into mutations resolvers etc

**Comment by masonlouchart** [comment]
This issue leads to a mismatch between the tutorial and the actual source code we have. Unable to continue the tutorial without spending time to figure out the authentication layer implementation, database schema migrations, code splitting and so on. Not impossible but it vanished all the fun I had so far to discover GraphQL through this beautiful tutorial. 😢

**Comment by TasinIshmam** [comment]
Hi, I think this was a bug that has been fixed at some point since you first raised this issue. The [authentication module](https://www.howtographql.com/graphql-js/6-authentication/) is available and visible on the website. 

I'll close this issue.
