### ISSUE TITLE
Typos on how to graphql tutorial 

### ISSUE THREAD

**Issue by hyungmogu** [howtographql/howtographql#1265]
Hello,

I found small typos on this page https://www.howtographql.com/graphql-js/7-subscriptions/. 

![image](https://user-images.githubusercontent.com/6856382/106322881-deb7ee80-62b9-11eb-84e5-9c45f23fa0cf.png)

Shouldn't the above be `const { PubSub } = require('apollo-server');`?

Also, shouldn't there be a comma after `pubsub`?

![image](https://user-images.githubusercontent.com/6856382/106327314-33ab3300-62c1-11eb-9979-c69703f7c70d.png)

Thank you so much for your time looking at this issue.

**Comment by adriantam** [comment]
Looks like the spollo-server is fixed already.  However, the missing comma still remains.
