### ISSUE TITLE
Realtime GraphQL Subscriptions - Cannot read property 'authorization' of undefined

### ISSUE THREAD

**Issue by AasmundEndresen** [howtographql/howtographql#1287]
This error appears when following the tutorial.

It appears after making the suggested changes to the `post()` function here:

![image](https://user-images.githubusercontent.com/28097617/110338606-7f22d080-8027-11eb-8d59-bbff4a100415.png)

It produces the following result when attempting to create a new post:

![image](https://user-images.githubusercontent.com/28097617/110338804-b7c2aa00-8027-11eb-8469-60368f5ab23d.png)

The post function works fine up until making the above changes to the `post()` function.

**Comment by JuliaMV** [comment]
see path in PR https://github.com/howtographql/howtographql/pull/1346

**Comment by TasinIshmam** [comment]
Fixed with #1346  

Thanks @JuliaMV!
