### ISSUE TITLE
wrong answer in tutorial question

### ISSUE THREAD

**Issue by scandar** [howtographql/howtographql#1306]
[ this question ](https://github.com/howtographql/howtographql/blob/master/content/backend/graphql-js/8-filtering-pagination-and-sorting.md) 
the correct answer is option 1 but for some reason it was 2 when i tried to solve it [here](https://www.howtographql.com/graphql-js/8-filtering-pagination-and-sorting/) 
![image](https://user-images.githubusercontent.com/25529286/113521139-cef9a680-9597-11eb-8056-59b588adddf5.png)

**Comment by weedent1** [comment]
I was just about to log this issue but then saw this. I am also experiencing this issue. Thanks for logging the issue. 
![image](https://user-images.githubusercontent.com/60558239/114806453-6619e780-9d6a-11eb-988e-37abfbf2604f.png)

**Comment by TasinIshmam** [comment]
Fixed by #1277
