### ISSUE TITLE
GraphQL-Node tutorial omits installation of graphql 

### ISSUE THREAD

**Issue by withinsight** [howtographql/howtographql#1311]
Running through this tutorial as a first time GraphQL user, and encountered this when attempting to run the server:

`Error: Cannot find module 'graphql'`

The tutorial has you install apollo-server, however graphql is obviously required, and the tutorial author likely already had it installed globally so it 'just worked'.

**Comment by withinsight** [comment]
Yes, I realized quickly how to remedy; posted here more so the tutorial author might consider updating.

**Comment by TasinIshmam** [comment]
Hi, this has been fixed in #1308
