### ISSUE TITLE
5-common-questions - Outdated Graphcool link

### ISSUE THREAD

**Issue by maltehain** [howtographql/howtographql#1317]
An outdated link to Graphcool exists within the 5-common-question page ([content/graphql/advanced/5-common-questions.md](https://github.com/howtographql/howtographql/blob/fe67b8e74057c8973d1bfffe9f055ca1b08da4d2/content/graphql/advanced/5-common-questions.md)). Graphcool closed on July 1, 2020, thus the content is no longer available through the link.

Part with the outdated link:
> If you want to have some inspiration on how to implement authorization, you can take a look at [Graphcool’s permission rules.](https://www.graph.cool/docs/reference/auth/overview-ohs4aek0pe)

Haven't found the website in the internet archive, so I'm not sure what the exact content was provided on the referenced page. Maybe some of these could be a replacement?

- [GraphQL Directive Permissions — Authorization Made Easy](https://www.prisma.io/blog/graphql-directive-permissions-authorization-made-easy-54c076b5368e)
- [Access Control in GraphQL](https://www.apollographql.com/blog/auth-in-graphql-part-2-c6441bcc4302/)

**Comment by TasinIshmam** [comment]
Thanks for bringing this up! 

Has been fixed by #1322
