### ISSUE TITLE
"A Simple Mutation" optional challenge not working

### ISSUE THREAD

**Issue by georgetye** [howtographql/howtographql#1327]
For [this chapter](https://www.howtographql.com/graphql-js/3-a-simple-mutation/):
<img width="898" alt="image" src="https://user-images.githubusercontent.com/15068475/120839559-16b89200-c537-11eb-88e3-4f3f20a73c14.png">

I get this result:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/15068475/120839594-220bbd80-c537-11eb-8744-a827ba2708b1.png">

Here's my schema file:
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/15068475/120839624-2b952580-c537-11eb-84d2-2eeeaf26c101.png">

EDIT - Just realized I probably need to add a resolver:
<img width="181" alt="image" src="https://user-images.githubusercontent.com/15068475/120841172-2d5fe880-c539-11eb-9ec1-953b65103089.png">

Now I'm getting this result:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/15068475/120841238-436da900-c539-11eb-9750-de3a869a5b47.png">

**Comment by cgodkin** [comment]
I think you need to do a little more work in your resolver for `link`.  Here's one way to do it:
```
const linkById = (id) => {
  return links.find((value) => value.id === id);
};

let idCount = links.length;
const resolvers = {
  Query: {
    info: () => `This is the API of a Hackernews Clone`,
    feed: () => links,
    // Fetch a single link by its `id`
    link: (parent, args) => linkById(args.id),
...
```

**Comment by TasinIshmam** [comment]
Closing as this is not an issue with the tutorial
