### ISSUE TITLE
Broken links to GraphQL Relay Specification

### ISSUE THREAD

**Issue by DrumsnChocolate** [howtographql/howtographql#1335]
There are multiple references to a GraphQL Relay Specification, such as in the [summary of Chapter 5](https://github.com/howtographql/howtographql/blob/master/content/backend/graphql-python/10-summary.md):
![image](https://user-images.githubusercontent.com/32799956/124596806-fd22a700-de62-11eb-907c-afa44473eedc.png)

When clicked, a page not found is shown:
![image](https://user-images.githubusercontent.com/32799956/124596917-1af00c00-de63-11eb-9c18-f148fd217f76.png)

I think the page has been moved from https://relay.dev/docs/en/graphql-server-specification.html
to https://relay.dev/docs/guides/graphql-server-specification/

If someone could update the references, that would be nice for future participants in the tutorial. I haven't tried to find all links to the specification, so there are probably more places where this URL is used.

**Comment by TasinIshmam** [comment]
Thanks for bringing this up and for the fix!
