### ISSUE TITLE
On-page code not runnable as stated in the video

### ISSUE THREAD

**Issue by alirezaghey** [howtographql/howtographql#1337]
The video on [this page](https://www.howtographql.com/basics/2-core-concepts/), at about 14:00, states that some of the examples on the page are runnable. According to the video [this snippet](https://github.com/howtographql/howtographql/blame/11ec3d88f98b3f200bb685aba72df0b0983e8419/content/graphql/basics/2-core-concepts.md#L58-L68), for instance, should be runnable. But it's not.
Looking further into the file history, I learned that [this may be by design](https://github.com/howtographql/howtographql/commit/049dc6e4feabb28260a91eaa8c43be265ade48a2#diff-6318c0b55704ca825e273a9840ebac59586327a369d94ebbc746b21e3484162c), but it would be helpful if you could add a notice or something about the removal or an alternative, so that beginners like me are not confused about whether there is something wrong with their system or the page has just changed.

Thank you for your great work.

**Comment by TasinIshmam** [comment]
Hey, thanks for bringing this up! Fixed.
