### ISSUE TITLE
Unknown answer in the chapter 7 of React+Apollo guide

### ISSUE THREAD

**Issue by jasur-n** [howtographql/howtographql#1343]
In the question at the bottom of the [7th chapter](https://www.howtographql.com/react-apollo/7-filtering-searching-the-list-of-links/), it is asked about the purpose of `withApollo` function. However, I couldn't find any information related to this function in the given chapter. Is the answer in some other parts of the guide or should we google to get information about asked function?

**Comment by TasinIshmam** [comment]
Hi, thanks for bringing this up :D 

I updated the question to be more relevant with the content of the chapter.
