### ISSUE TITLE
Routing: Attempted import error: 'Switch' is not exported from 'react-router-dom'

### ISSUE THREAD

**Issue by giovannipds** [howtographql/howtographql#1387]
When doing [routing](https://www.howtographql.com/react-apollo/4-routing/), we can't go forward with the `Switch` mentioned. `react-router-dom` updated its syntax, I already opened a PR to fix this, please check #1386.

**Comment by AMEENANAS** [comment]
Attempted import error: 'Switch' is not exported from 'react-router-dom'.

**Comment by giovannipds** [comment]
@AMEENANAS yes, I already know that, that's why I already opened a PR to fix it. Check #1386. Thx.

**Comment by RusJaI** [comment]
I found this on stackoverflow. Hope this would help you

https://stackoverflow.com/a/69849271/11026123

**Comment by danny-votez** [comment]
> Attempted import error: 'Switch' is not exported from 'react-router-dom'.

Replace "Switch" with "Routes"

**Comment by rabeexxxx** [comment]
Routes Not working also

**Comment by rabeexxxx** [comment]
import { Switch, Route } from "react-router-dom";
to

import { Routes ,Route } from 'react-router-dom';
You also need to update the Route declaration from

<Route path="/" component={Home} />
to

<Route path='/welcome' element={<Home/>} />

**Comment by credleo95** [comment]
Hello, I️ came across this thread because I️ was working on an individual project and it seems like this has been answered. However, I️ haven't seen anyone link to the react-router docs with a full explanation yet. I️ hope this is helpful as well. Here's a [link](https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-all-switch-elements-to-routes).

**Comment by kstoev9316** [comment]
import {BrowserRouter, Route, Switch,NavLink} from 'react-router-dom';
TO
import {BrowserRouter, Route, Routes ,NavLink} from 'react-router-dom';

and

<Switch>
        <Route path='/home' component={Home}/>
TO
<Routes>
        <Route path='/home' element={Home}/>

**Comment by waclawek** [comment]
as @kstoev9316 said but remember in the element you need to add </> 

element={<Home/>}

**Comment by giovannipds** [comment]
**Please stop posting on this issue**, I only left it open until we're sure the whole documentation is updated.

Fox fixing this, just check it here https://stackoverflow.com/a/69849271/842768 and its comments if needed.

Thank you for your understanding (thumb this up)!

**Comment by sam19000** [comment]
this is bcz react-router-dom @6 was install in npm , so uninstall react-router-dom form npm
type in terminal -  npm uninstall react-router-dom after that install   npm install react-router-dom@5.3.0 and Switch will work

Thank you

**Comment by TabotCharlesBessong** [comment]
> > Attempted import error: 'Switch' is not exported from 'react-router-dom'.
> 
> Replace "Switch" with "Routes"

Sorry but i just tried this but it is not working

**Comment by PromiseUdo** [comment]
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom'
import SigninPage from './pages/signin'
import Home from './pages'


function App() {
  return (
    <Router>
      <Routes>
        <Route path='/' element={<Home />} />
        <Route path='/signin' element={<SigninPage />} />
      </Routes>
    </Router>
  )
}

Find example from the docs https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-all-switch-elements-to-routes

**Comment by vmutlu** [comment]
@danny-votez thanks man you saved me from calling

**Comment by ausama** [comment]
Hi,  Solution is to install Switch by entering:
npm install react-router-dom@5

**Comment by oliverwatkins** [comment]
I would forget about react router v6.x . 

It installs v5.x in the @types .

It just smells broken. Stick to v5.x

**Comment by Thetwin21** [comment]
@sa@sam19000 thanks man. 
It worked 🤗

**Comment by japhethdleung** [comment]
<Routes>
      <Route path = '/' element = {<Home/>} />
      <Route path = '/auth' element = {<Auth/>} />
  </Routes>

**Comment by zackha** [comment]
you can run:

### `npm install --save react-router-dom@5.2.0`

**Comment by Ajanta28** [comment]
npm 
npm install react-router-dom@5.3.3

It's work try this

**Comment by PratyayChakraborty** [comment]
> I found this on stackoverflow. Hope this would help you
> 
> https://stackoverflow.com/a/69849271/11026123

>it s helpfull
