### ISSUE TITLE
React+Relay: graphqlbin.com/hn-relay-full.graphql needs to be updated

### ISSUE THREAD

**Issue by MikaelCarpenter** [howtographql/howtographql#143]
## Issue
The [schema file](https://graphqlbin.com/hn-relay-full.graphql) that is mentioned in `/react-relay/2-queries-loading-links/` has duplicate inputs. You define `SignupUserInput` on L511 and L567 which causes errors when compiling.

## Reproduce
- Make sure your `package.json` contains the relay script
```
"scripts": {
  "relay": "relay-compiler --src ./src --schema ./schema.graphql"
}
```
- Go to the [schema file](https://graphqlbin.com/hn-relay-full.graphql) mentioned in the tutorial and copy its contents. 
- Replace your local `schema.graphql` file with the copied contents.
- In your project directory in terminal do `yarn run relay`
- You will see `Error: Type "SignupUserInput" was defined more than once.`

## Proposed Solution
Someone with access privileges can go alter the [schema file](https://graphqlbin.com/hn-relay-full.graphql) to remove the one defined on L567. _(that one does have `authProvider: AuthProviderSignupData!` in it)_ .

**Comment by nikolasburk** [comment]
Thanks for the hint, just fixed this... a bit strange though that the issue never came up - I've always used the same schema and the compiler never complained.
