### ISSUE TITLE
Typo in the Authentication section

### ISSUE THREAD

**Issue by sagar1025** [howtographql/howtographql#1445]
Noticed a typo under the "**Extending the GraphQL schema with the `User` type**" part in the [Authentication](https://www.howtographql.com/typescript-apollo/6-authentication/) section. See the highlighted part in the image (last paragraph)

![image](https://user-images.githubusercontent.com/12006198/180614453-2b057a8c-fba5-45a8-afde-e609d7abf878.png)

The sentence is "You are using the parent argument which contains the all the fields of the user that you are trying to resolve." but it should be "You are using the parent argument which contains all the fields of the user that you are trying to resolve."

There's an extra "the" that should be removed.

**Comment by sagar1025** [comment]
Created #1446 for fix

**Comment by TasinIshmam** [comment]
Fixed. Thanks!
