### ISSUE TITLE
React + Relay Video missing in /3-mutations-creating-links/

### ISSUE THREAD

**Issue by MikaelCarpenter** [howtographql/howtographql#146]
# Issue
When loading the page for the [mutation section](https://www.howtographql.com/react-relay/3-mutations-creating-links/) the video doesn't load. This appears to be due to the video being re-uploaded on the YT channel with a new id. 
![screen shot 2017-07-21 at 3 40 10 pm](https://user-images.githubusercontent.com/8742292/28485044-5d749bce-6e2b-11e7-8f3a-962dc4898e15.png)

## Reproduce
- Go to the [mutation section](https://www.howtographql.com/react-relay/3-mutations-creating-links/)
- Try to press play on the video
- Should see `This video is unavailable.`

## Proposed Solution
I went to the channel and found a new video for the section. I can update the `videoId` for that file to match the [new video](https://www.youtube.com/watch?v=eIsctkVmq4Y)

**PR incoming for that**

**Comment by marktani** [comment]
thanks :tada:
