### ISSUE TITLE
React + Relay: Mutation section is incomplete on render

### ISSUE THREAD

**Issue by MikaelCarpenter** [howtographql/howtographql#148]
## Issue
When going through the [mutation section](https://www.howtographql.com/react-relay/3-mutations-creating-links/) on the react+relay tutorial there is a code snippet that implements a mutation and then it is immediately followed by a quiz. This is odd because the snippet has annotations that normally indicate an upcoming explanation, but there was nothing. I checked the code and sure enough there is meant to be more content.

## Reproduce
- Go to the [mutation section](https://www.howtographql.com/react-relay/3-mutations-creating-links/)
- Scroll to the bottom of the tutorial
- You should see a code snippet with no explanation followed by a quiz to end the section

## Proposed Solution
So I checked the code and it looks like this is caused by a tag issue. There's a code snippet wrapped with two `<Instruction>` tags rather than `<Instruction>...</Instruction>`. Then nothing after that renders to the page, so fixing that second tag should fix the problem?

**PR incoming**

**Comment by marktani** [comment]
Thanks for all your glorious help, @MikaelCarpenter! One minor suggestion though, if you add the commit message

> Closes #148
