### ISSUE TITLE
Is it possible to have completed repos? 

### ISSUE THREAD

**Issue by ryanking1809** [howtographql/howtographql#171]
Is it possible to have completed repos to ensure we've completed the tutorials correctly?

I'm currently having issues with apollo-react and it's hard to pinpoint the exact problem.(https://stackoverflow.com/questions/20954944/stop-lastpass-filling-out-a-form)

Being able to clone the completed tutorial app would eliminate any errors created on my behalf.

**Comment by nikolasburk** [comment]
Hi @ryanking1809! Every tutorial is backed by an open-source repository that contains the fully implemented project and can also be found in the howtographql GitHub organization. The one for the React & Apollo tutorial can be found here: https://github.com/howtographql/react-apollo/
