### ISSUE TITLE
Add "Tutorial Name" to the Title of the introduction page 

### ISSUE THREAD

**Issue by nikolasburk** [howtographql/howtographql#172]
The first page (i.e. the _Introduction_) of each tutorial should have the "name" of the tutorial in the title. For example, for the React & Apollo tutorial, the title should be:

`React & Apollo Tutorial - Introduction`

or for graphql-ruby:

`graphql-ruby Tutorial - Introduction`

**Comment by angly-cat** [comment]
This is already implemented in live version of the site.
