### ISSUE TITLE
Authentication Setup - Missing instructions 

### ISSUE THREAD

**Issue by caseychoiniere** [howtographql/howtographql#183]
I noticed that when I get to step 5 - Authentication that the  Email-Password-Auth-integration is not available in the integrations tab of the Graphcool console.

![screen shot 2017-08-08 at 1 24 27 pm](https://user-images.githubusercontent.com/10411174/29092954-f2cbbfb2-7c3c-11e7-8760-91c3b0325435.png)

The tutorial says:
>This will open up the Graphcool Console - the web UI that allows you to configure your Graphcool project.
>Select the Integrations-tab in the left side-menu and then click on the Email-Password-Auth-integration.

But when I check the authentication examples at https://github.com/graphcool-examples/functions/tree/master/authentication/email-user-management it says that you need to setup your schema with `graphcool init --schema email-user-management.graphql`

Unfortunately in step 1 - Getting Started we are instructed to initiate our schema as so `graphcool init --schema https://graphqlbin.com/hn-starter.graphql --name Hackernews` 

I'm wondering if this is why the integration is not available to me? Is there a way around this without recreating my schema again? I've searched but can't seem to find an answer anywhere.

Thanks for your time

**Comment by caseychoiniere** [comment]
SOLUTION:

I figured out the solution to this problem and am posting it here to hopefully help others figure this out. It ended up being a pretty big waste of time. The email-password-auth integration only comes up if you click on the Auth0 integration tab. This is really unintuitive though and should either be changed in the tutorial or in the integrations window itself. It actually seems like a bug to me because even after I disabled the email-password-auth integration, it now shows up in the integrations window as expected. 

Steps to reproduce: 

1.) Create a new schema using `graphcool init --schema https://graphqlbin.com/hn-starter.graphql --name Hackernews` 

2.) In the directory where project.graphcool is located, type `graphcool console`

3.) Select the Integrations-tab in the left side-menu and then click on the Email-Password-Auth-integration. You should have these options 
![image](https://user-images.githubusercontent.com/10411174/29093612-427ea086-7c3f-11e7-9b4b-e5b1f527fb9e.png)

4.) Click on the Auth0 integration option

5.) In a new popup you should see the options that were missing from before 
![screen shot 2017-08-08 at 1 42 00 pm](https://user-images.githubusercontent.com/10411174/29093669-6ffc466c-7c3f-11e7-98bc-025cf93bd5be.png)

6.) Select `Email` option in the left and then enable it

7.) Now you should see all of the options in the integrations window

![screen shot 2017-08-08 at 1 43 23 pm](https://user-images.githubusercontent.com/10411174/29093703-92dfb0ec-7c3f-11e7-8b86-1b3f0da21f4a.png)

**Comment by angly-cat** [comment]
It seems like it's fixed to date.

**Comment by radicand** [comment]
If like me, you don't see an Integrations tab at all, just update the URL manually to be `/<your-project>/integrations` and it'll take you to the right place.

**Comment by nikolasburk** [comment]
Thanks for pointing this out and posting a solution @caseychoiniere 🙌  With the latest update to Prisma and Apollo Client 2.0, the problem also doesn't apply any more as no integrations are required any more at all 🙂
