### ISSUE TITLE
The need for SigninResolver in Authentication Chapter in Graphql-Java 

### ISSUE THREAD

**Issue by dpulluri** [howtographql/howtographql#186]
This is not an issue but more of a question to understand the tutorial. Did not know what is the right forum to get this answered. Sorry in advance, not my intention to clutter the issues. 

I did not understand why we have to write the [signinresolver](https://github.com/howtographql/graphql-java/blob/master/src/main/java/com/howtographql/hackernews/SigninResolver.java) class. The tutorial does mention that "Because SigninPayload data class contains a complex (non-scalar) object User, it needs a companion resolver class" but I did not write it and I got the response back fine with token and user details. Could someone please explain why?

Great resources by the way. Love the way it is structured.

**Comment by kaqqao** [comment]
I think this is only because there used to be a bug in graphql-java-tools, so you're probably right that it's not needed. I have to update the tutorial very soon to use the current library versions, so I'll remove that step as well. Thanks!

**Comment by dpulluri** [comment]
Thank you.
