### ISSUE TITLE
4-Routing question is wrong

### ISSUE THREAD

**Issue by alexandru-calinoiu** [howtographql/howtographql#189]
The question asks:

`What's the role of the Link component that you added in this chapter?`

It should probably be

`What's the role of the Header component that you added in this chapter?`

**Comment by angly-cat** [comment]
If you're referring the same `It lets you navigate to a different URL` answer, then it's not. `Header` components doesn't let you navigate to a different URL. It's just a container. But `Link` components do that.

**Comment by nikolasburk** [comment]
Thanks for opening this issue  @alexandru-calinoiu. I believe @angly-cat is right on this one and it is indeed the `Link` component that takes care of routing to a different URL. Let me know if you have any further questions 🙂
