### ISSUE TITLE
Graphene shouldn't be shown as "Coming soon"

### ISSUE THREAD

**Issue by vpanjganj** [howtographql/howtographql#197]
https://github.com/graphql-python/graphene/releases
Graphene is on version 1.4.1 at the moment.

**Comment by marktani** [comment]
Thanks for your feedback! The coming soon is not referring to Graphene itself, but to the tutorial track covering Graphene, which, in fact, is coming soon 😄

**Comment by vpanjganj** [comment]
oops :D
