### ISSUE TITLE
Relay compiler cannot be invoked

### ISSUE THREAD

**Issue by sderungs99** [howtographql/howtographql#198]
In chapter https://www.howtographql.com/react-relay/2-queries-loading-links/, it is not possible to invoke the relay-compiler as described, because it has not been installed globally before. The instruction to install globally may be missing in the previous chapter?

**Comment by thecodejunkie** [comment]
I had the same issue and ended up calling it from my `node_modules` folder, i.e `./node_modules/relay-compiler/bin/relay-compiler --src ./src --shema ./schema.graphql`

**Comment by conradwt** [comment]
@sderungs99 @thecodejunkie Yes, I thought it was just me but it seems that the tutorial should be updated to either install the `relay-compiler` globally or use the relative path to it.

**Comment by nicerr** [comment]
> I had the same issue and ended up calling it from my node_modules folder, i.e `./node_modules/relay-compiler/bin/relay-compiler --src ./src --shema ./schema.graphql`

`--shema` spelling... ;) this works:

`./node_modules/relay-compiler/bin/relay-compiler --src ./src --schema ./schema.graphql`

**Comment by thecodejunkie** [comment]
Whops! Fixed 😄

**Comment by gustavo-depaula** [comment]
You can invoke `npm i -g relay-compiler` too, so that relay-compiler becomes available globally

**Comment by nikolasburk** [comment]
Thanks for pointing this out @sderungs99 and my sincere apologies for the delayed response! I just updated the tutorial to include global install instructions 🙌

**Comment by yangshun** [comment]
I had to manually install the `graphql` package now before I could run it. It seems to have become a peer dependency of `relay-compiler` now.
