### ISSUE TITLE
Write Polymer 2.x or 3.x hands-on tutorial

### ISSUE THREAD

**Issue by MungTheWicked** [howtographql/howtographql#202]
I see that there's a repo for [Polymer](https://github.com/howtographql) that's already been created. Being as there's an [existing resource](https://github.com/aruntk/polymer-apollo) for Polymer + GraphQL, can the hands-on tutorial be implemented?

Depending on when the tutorial is created, it seems that there is a chance that Polymer 3.x could be released.

**Comment by nikolasburk** [comment]
Hey thanks a lot for pointing that out, we have found a contributor for a Polymer tutorial but he's currently busy - however I'm confident that the tutorial will be released soon.
