### ISSUE TITLE
Tutorial Pages not updating

### ISSUE THREAD

**Issue by nate01776** [howtographql/howtographql#207]
I am working through the tutorial (site is a terrific resource), and found that the website renders the same 'Introduction' page regardless of the URL/step that I am looking to view when in chrome. Works without issue in Opera. 

![image](https://user-images.githubusercontent.com/18563085/29681900-30c2f546-88d7-11e7-81c3-88f00a83f8bd.png)

**Comment by nikolasburk** [comment]
Hey @nate01776, thanks a lot for opening the issue and my sincere apologies for the delay! I can't reproduce the problem, can you confirm it's still an issue for you? If so, feel free to reopen the issue again and I'll look into it again.
