### ISSUE TITLE
ruby tutorial seems to be out of date

### ISSUE THREAD

**Issue by roberthopman** [howtographql/howtographql#209]
The Mutation gets autogenerated which changes the order a bit. Can I just make a pull request to improve the tutorial ?

**Comment by Freddy-Meijer** [comment]
In the Authentication section the controller does not require require './app/graphql/tutorial_schema' resulting the following error:

NameError (uninitialized constant GraphqlController::GraphqlTutorialSchema):
app/controllers/graphql_controller.rb:11:in `execute'

Also in sign_in_user.rb, it should not be ctx[ ...  should be _ctx[:session][:token] = token

**Comment by nikolasburk** [comment]
I believe this was fixed in #208, thanks again @roberthopman!
