### ISSUE TITLE
React & Relay-Part 4(Mutations: Creating Links): Compile Error: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mooqoo** [howtographql/howtographql#220]
I am getting error msg after running ``` relay-compiler --src ./src --schema ./schema.graphql``` to compile

```
ERROR:
Error writing modules:
RangeError: Maximum call stack size exceeded
```

Is anyone getting the same issue or knows what is going on here? thanks

**Comment by thecodejunkie** [comment]
I just got to this step and ended up with the exact same error message. I've verified that everything is entered as needed (or at least as far as I've been able to tell) and can't get past this point at the moment

**Comment by thecodejunkie** [comment]
I just went back to https://www.howtographql.com/react-relay/2-queries-loading-links/ and I noticed I had missed this important piece of information

![image](https://user-images.githubusercontent.com/50543/30267448-ece8ec94-96e2-11e7-9302-b4222d7ae046.png)

Once I had updated my `schema-graphql` with the content of https://graphqlbin.com/hn-relay-full.graphql I was able to run `relay-compiler` again 👍 

Hopefully this will get you unstuck as well @mooqoo

**Comment by mooqoo** [comment]
Thanks @thecodejunkie 
That fix my problem! You save my day!
Then I'm going to close this issue.
