### ISSUE TITLE
addGraphQLSubscriptions has been deprecated

### ISSUE THREAD

**Issue by dennisbrandenberger** [howtographql/howtographql#226]
I am doing the vue-apollo tutorial

According to this: https://github.com/apollographql/subscriptions-transport-ws/issues/169, addGraphQLSubscriptions has been deprecated and I get an error (require not working)

So I'm using this instead: 
```
import { SubscriptionClient } from 'subscriptions-transport-ws'
import { addGraphQLSubscriptions } from 'add-graphql-subscriptions';
```

However a new problem occurs:
```
vue.esm.js?65d7:479 [Vue warn]: Error in created hook: "TypeError: wsClient.subscribe is not a function"

found in

---> <LinkList> at src/components/LinkList.vue
       <App> at src/App.vue
         <Root>
```
Anyone know a workaround for this ?

For now I'm just using the older subscriptions-transport-ws version (^0.6.0) and it seams to work

**Comment by lednhatkhanh** [comment]
Any updates on this?

**Comment by MattDionis** [comment]
I will take a look when I get a chance and get the tutorial and repo updated accordingly. I have a new baby 👶 at home so it might take a few days.
For now the best bet is indeed to use an older version of subscriptions-transport-ws such as 0.6.0.

**Comment by TheoMer** [comment]
Hi @MattDionis I'm just now experiencing this issue, and can confirm that running:

```
"subscriptions-transport-ws": "^0.9.0"
```
causes the application to break, while installing:

```
"subscriptions-transport-ws": "0.6.0"
```

works fine. 

The funny thing is that I'm running an apollo/react project using subscriptions-transport-ws (0.9.0), which works just fine. 

So what's the issue here?

**Comment by sandroqz** [comment]
It's also happening on React + Apollo tutorial.

**Comment by bakumn** [comment]
how to fix it.
addGraphQLSubscriptions is not a function

**Comment by bakumn** [comment]
so, which function use?

**Comment by bakumn** [comment]
how to subscriptions on  "subscriptions-transport-ws" version 0.9.0"?

**Comment by Matt-Dionis** [comment]
I'm going to dig into finding the proper solution here. In the meantime, do folks think it would be helpful to temporarily update the tutorial to have users install `subscriptions-transport-ws@0.6.0`? This would be a "band-aid fix" until I figure out the necessary changes for the latest version.
Thoughts?

**Comment by TheoMer** [comment]
@Matt-Dionis Yes, that would be a good idea.

**Comment by graph1994** [comment]
Looks like a possible solution is mentioned here: apollographql/subscriptions-transport-ws#275

**Comment by bschwartz757** [comment]
Sounds like this is not a straightforward issue https://github.com/apollographql/subscriptions-transport-ws/issues/169

**Comment by graph1994** [comment]
Hey @bschwartz757, I set it in package.json to `"subscriptions-transport-ws": "0.8.0"`.  It still throws a warning about becoming deprecated but otherwise works. I think by having the ^ it updates the minor and patch versions so '0.x.x', I think you would want to use ~ for just patch versions '0.0.x'

**Comment by n2ctech** [comment]
last version to work is "0.8.3"

**Comment by graph1994** [comment]
So I was able to come up with a solution that works utilizing apollo-link

``` javascript
const uri = 'https://api.graph.cool/simple/v1/cj7yuh1df1tnt0147ihz25bgi'
const wsClient = { 
 uri: 'wss://subscriptions.graph.cool/v1/cj7yuh1df1tnt0147ihz25bgi',
 options: {
     reconnect: true,
     connectionParams: {
        authToken: localStorage.getItem(GC_AUTH_TOKEN),
     }
  }
}


const link = ApolloLink.split(
  operation => { // check if it is a subscription 
  	const operationAST = getOperationAST(operation.query, operation.operationName);
  	return !!operationAST && operationAST.operation === 'subscription';
  },
  new WebSocketLink(wsClient),
  new HttpLink({ uri }),
);


const client = new ApolloClient({
  networkInterface: link
})
```
Heres the [docs](https://github.com/apollographql/apollo-link/blob/master/docs/implementation.md) for ApolloLink.split

Although there is another issue caused by subscribeData returning a nested data object so you have to use `subscriptionData..data.data.Vote.node.link`... not sure what that is about..

**Comment by bschwartz757** [comment]
@graph1994 thanks for the answer! Using 0.8.3 did help, I think, but there was also another issue with the tutorial - 
```const networkInterface = createNetworkInterface({uri: 'https://api.graph.cool/simple/v1/<project-Id>'})```
needs to be:
```const networkInterface = createNetworkInterface({uri: 'https://api.graph.cool/simple/v1/cj6duaasd3jwe0101a55zyvwe'})```
(or whatever the end of your subscription endpoint is). Without this, the app kept throwing errors and wouldn't display the root page view properly in the browser. Your answer above gave me the idea to change that and now it works as expected.

Thanks for the great tutorial and the help figuring this out!

**Comment by Matt-Dionis** [comment]
Hi, @bschwartz757! Anywhere in the tutorial where you see double underscores surrounding a variable in all caps (`__SIMPLE_API_ENDPOINT__`) that string should be replaced with your endpoint, ID, etc. Those are simply placeholders.

**Comment by bschwartz757** [comment]
Hi @Matt-Dionis , thanks - the tutorial does cover replacing that one (only the `wss...` SubscriptionClient parameter is indicated with double underscores.) The `https` createNetworkInterface one, however, is indicated in brackets - which, being someone who is not super experienced in React looks like it could possibly be some kind of variable. 

As far as I can tell, there isn't a place in the Subscriptions video where the user is told to replace that so I just figured I'd point it out. Thanks!

**Comment by Matt-Dionis** [comment]
Ahhh didn't realize you were referencing the React tutorial. I wrote the Vue tutorial and assumed this was in reference to that.

**Comment by bschwartz757** [comment]
@Matt-Dionis  No worries, thanks for the response - hoping to try the Vue tutorial soon here.

**Comment by michaelcbrook** [comment]
For anyone who might come across this in the future, I've taken a lot of these pain points and have tried to make a comprehensive guide for upgrading to Apollo 2.0 [here](https://medium.com/@michaelcbrook/how-to-get-apollo-2-0-working-with-graphql-subscriptions-321388be030c), with an example app in Meteor [here](https://github.com/Pitchlyapp/meteor-apollo2). Maybe that will help someone.
