### ISSUE TITLE
Confusing use of Slice in vue-apollo tutorial

### ISSUE THREAD

**Issue by martinpeck** [howtographql/howtographql#239]
In Chapter 8 of the vue-apollo tutorial the user defines an `updateQuery` function. In this function you can see the following line of code...

`allLinks: newAllLinks.slice(0, 5)`

(see https://github.com/howtographql/vue-apollo/blob/master/src/components/LinkList.vue#L112)

At this point in the tutorial, the number `5` is not explained. 

Later, in Chapter 9, it becomes apparent that the 5 is related to the pagination (5 links are shown per page), but when the user encounters this line of code it's unclear why they're taking just the first  5 items from the `newAllLinks` array.

I realise that this entire section of the tutorial is "at risk" because of the change to how subscriptions work (see #226), so I'm not sure if this issue is worth fixing until that's resolved

I suggest one of the following:

1. explain where the number 5 comes from
2. remove the number 5, and in Chapter 9 get the user to come back and add it (once the pagination is explained)
3. do nothing, until #226 is resolved

**Comment by martinpeck** [comment]
I'm happy to issue a PR for either option 1 or 2 (above)...just let me know which you think is the better choice.

**Comment by marktani** [comment]
Could a comment above the code line in question be already enough of context here? That could be a small but effective change.

**Comment by marktani** [comment]
What do you think, @Matt-Dionis? 🙂

**Comment by Matt-Dionis** [comment]
I feel like option 2 mentioned above by @martinpeck is the best solution. This will involve changing the line in question from `allLinks: newAllLinks.slice(0, 5)` to `allLinks: newAllLinks` in chapter 8 and then updating this line to `allLinks: newAllLinks.slice(0, 5)` in chapter 9 and explaining why briefly.
If I get a couple 👍 from you guys, I'll move forward with this solution.
