### ISSUE TITLE
What is a Viewer type exactly?

### ISSUE THREAD

**Issue by mraak** [howtographql/howtographql#242]
Graphcool doesn't work in the corporate environment so I made my own GraphQL Relay server in Python. M endpoints are working through _graphiql_ and my other types compile successfully but I get this error:
```

ERROR:
You supplied a GraphQL document with validation errors:
components/OrgsList.js: Unknown type "Viewer".
```

Looking at this example: https://graphqlbin.com/hn-relay-full.graphql

Viewer seems like a collection of all master queries or something similar. Do I have to implement something on the server or simply declare it in _schema.graphql._ 

This is the issue I'm facing plus it would be a great addition to explain the Viewer more in tutorial.

**Comment by nikolasburk** [comment]
Hi @mraak, my sincere apologies for the late reply!

The `Viewer` represents the currently logged in user and her perspective into the data graph. It's a convention that's used in Relay (actually in Relay Classic it was required, but with with Relay Modern it's not any more.) You can read more about it [here](https://stackoverflow.com/questions/37635328/what-is-the-meaning-of-viewer-field-in-graphql).
