### ISSUE TITLE
Schema issue in Basics tutorial part 2: All models must specify the `id` field: `id: ID! @isUnique`

### ISSUE THREAD

**Issue by g00ntar** [howtographql/howtographql#243]
Hello.
After click every button Run in Sandbox in [Core Concepts](https://www.howtographql.com/basics/2-core-concepts/) I get response from server that looks like this:

`{"locations":[{"line":2,"column":9}],"path":["addProject"],"code":2040,"message":"The schema is invalid:
All models must specify the 'id' field: 'id: ID! @isUnique'
All models must specify the 'id' field: 'id: ID! @isUnique'","requestId":"eu-west-1:system:cj8043lcx0ak90113oi19qav7"}`

**Comment by timsuchanek** [comment]
Thanks for reporting. This is fixed now :)
