### ISSUE TITLE
react-apollo tutorial chapter 5

### ISSUE THREAD

**Issue by integratedinfosys** [howtographql/howtographql#251]
Hi,

In the 5th chapter of react-apollo tutorial after I insert a new link, the app goes to the link page, but the newly inserted link doesn't appear in the list. However, on a refresh, the new link does appear in the list.

**Comment by angly-cat** [comment]
That's the intended behavior for that chapter. Check 6th chapter for implementation of new link insertion into the list right after it's creation.
