### ISSUE TITLE
react-apollo - 1-getting-started - The schema is invalid

### ISSUE THREAD

**Issue by jamessdixon** [howtographql/howtographql#257]
I am working through the tutorial.  When I execute this command:

graphcool init --schema https://graphqlbin.com/hn-starter.graphql --name Hackernews

I get this:

![image](https://user-images.githubusercontent.com/1394644/31497245-7f558680-af2c-11e7-8892-70751c3a3923.png)

**Comment by ziopod** [comment]
Same problem with "Graphcool tutorial" https://www.howtographql.com/graphcool/0-introduction/

**Comment by alassiter** [comment]
I've requested an issue on graphcool, to address using graphcool init.

They are updating a lot on the CLI in prep for a big shift, but the `init` should be one of those things that still works. It will help if graphqlbin updates the schema with the @model directive

**Comment by ekeyur** [comment]
Did anyone get pass the error message: I get the message of  unknown Flag --schema where running: graphcool init --schema https://graphqlbin.com/hn-starter.graphql --name Hackernews

**Comment by angly-cat** [comment]
I've read somewhere that the schema file at https://graphqlbin.com/hn-starter.graphql was updated after recent graphcool updates and now `graphcool init --schema https://graphqlbin.com/hn-starter.graphql --name Hackernews` works as intended. Is this still an issue for you?

**Comment by G3oo79** [comment]
Hello new to this thread I am also having the same error: Error Unknown flag --schema. while initializing graphcool init --schema https://graphqlbin.com/hn-starter.graphql --name Hackernews. any suggestions??

**Comment by angly-cat** [comment]
@G3oo79 what is the version of your `graphcool`? Check with `graphcool version`.

**Comment by G3oo79** [comment]
thank you for the quick response running version 0.8.5

**Comment by angly-cat** [comment]
@ekeyur @G3oo79 That's the issue. As you can read in the `NOTE` in the top part of [Introduction](https://www.howtographql.com/react-apollo/0-introduction/). the tutorial uses the legacy `0.4` version of `graphcool`.

I, personally, somehow, don't remember how exactly, ended up with version `1.3.7` which worked fine for me. I don't understand this versioning and what which versions are meant to be.

**Comment by G3oo79** [comment]
@angly-cat thank you for the info. So i installed version 0.4 and it worked the problem now is with createNetworkInterface from react-apollo. For what i have been searching it looks like is also a version problem. I get TypeError: Object(...) is not a function from const networkInterface = createNetworkInterface({ uri: '  https:// Simple api'})

**Comment by angly-cat** [comment]
@G3oo79 Oh, about that. Apparently tutorial also uses obsolete `1.x` versions of Apollo and `react-apollo`, with `2.x` versions of these packages to be latest to date.

Maybe someone someday (maybe even me 😺) will make a PR to update this tutorial with `2.x` versions of `apollo-client` and `react-apollo`.

**Comment by G3oo79** [comment]
@angly-cat Cool thank you again if I have the time to troubleshoot and push the new version implementations I will let you now.

**Comment by angly-cat** [comment]
@G3oo79 I'm still learning just like you. And in my own learning process of this tutorial I've kinda already done all tasks (up to chapter 6, inclusive) with `2.x` version of `react-apollo`. That made me add several other packages to implement the same functionality (`apollo-client`, `apollo-client-preset`, `apollo-link-context`), though. So maybe after I finish this tutorial, it would be rather easy for me to make a PR with all that code ready, I think.

**Comment by nikolasburk** [comment]
Hi @jamessdixon, thanks a lot for opening this issue and my sincere apologies for the late reply. 

The issue came from the change from the Graphcool BaaS to the open-source Graphcool Framework.

However, the entire tutorial has recently been updated to use a custom GraphQL server from the beginning, so this issue is now out-of-date. Let me know if you have any further questions, happy to help 🙂 🙌
