### ISSUE TITLE
React + Apollo (9/10) Subscriptions - Not working

### ISSUE THREAD

**Issue by KeevanDance** [howtographql/howtographql#267]
I have been stuck on this for the past 3 or so hours. I saw there was some issues with `addGraphQLSubscriptions` from `subscriptions-transport-ws` and so I tried downgrading as well as switching to `add-graphql-subscriptions` however neither works for me.

When adding a new Link through the playground, the browser does not actually show the new Link without reloading the page.

As you can see in my **LinkList.js**, I have added some console.logs to try and debug. All of them, except `console.log('updating...')` appear in the console.

Here are some snippits of my code:

**index.js**
```javascript
import React from 'react'
import ReactDOM from 'react-dom'
import { BrowserRouter } from 'react-router-dom'
import { ApolloProvider, createNetworkInterface, ApolloClient } from 'react-apollo'
import { SubscriptionClient, addGraphQLSubscriptions } from 'subscriptions-transport-ws'
// import { addGraphQLSubscriptions } from 'add-graphql-subscriptions'

import { GC_AUTH_TOKEN } from './constants'

import App from './components/App'
import registerServiceWorker from './registerServiceWorker'
import './styles/index.css'


const networkInterface = createNetworkInterface({
  uri: 'https://api.graph.cool/simple/v1/cj8xchn5x0arg0120ljnt2nhw'
})

const wsClient = new SubscriptionClient('wss://subscriptions.graph.cool/v1/cj8xchn5x0arg0120ljnt2nhw', {
  reconnect: true,
  connectionParams: {
    authToken: localStorage.getItem(GC_AUTH_TOKEN)
  }
})

const networkInterFaceWithSubscriptions = addGraphQLSubscriptions(
  networkInterface,
  wsClient,
)

networkInterface.use([{
  applyMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {}
    }
    const token = localStorage.getItem(GC_AUTH_TOKEN)
    req.options.headers.authorization = token ? `Bearer ${token}` : null
    next()
  }
}])

const client = new ApolloClient({
  networkInterface: networkInterFaceWithSubscriptions
})

ReactDOM.render(
  <BrowserRouter>
    <ApolloProvider client={client}>
      <App />
    </ApolloProvider>
  </BrowserRouter>
  , document.getElementById('root')
)
registerServiceWorker()
```

**LinkList.js**
```javascript
import React from 'react'
import { graphql, gql } from 'react-apollo'
import Link from './Link'

class LinkList extends React.Component {

  _updateCacheAfterVote = (store, createVote, linkId) => {
    const data = store.readQuery({ query: ALL_LINKS_QUERY })

    const votedLink = data.allLinks.find(link => link.id === linkId)
    votedLink.votes = createVote.link.votes

    store.writeQuery({ query: ALL_LINKS_QUERY, data })
  }

  _subscribeToNewLinks = () => {
    console.log('subscribing...')
    this.props.allLinksQuery.subscribeToMore({
      document: LINKS_SUBSCRIPTION,
      updateQuery: (previous, { subscriptionData }) => {
        console.log('updating...')
        const newAllLinks = [
          subscriptionData.data.Link.node,
          ...previous.allLinks
        ]
        const result = {
          ...previous,
          allLinks: newAllLinks
        } 
        return result
      } 
    })
  } 

  componentDidMount() {
    console.log('mounting...')
    this._subscribeToNewLinks()
  }

  render() {
    
    if (this.props.allLinksQuery && this.props.allLinksQuery.loading) {
      return <div>Loading</div>
    }

    if (this.props.allLinksQuery && this.props.allLinksQuery.error) {
      return <div>Error</div>
    }

    const linksToRender = this.props.allLinksQuery.allLinks

    return (
      <div>
        {linksToRender.map((link, index) => (
          <Link 
            key={link.id} 
            updateStoreAfterVote={this._updateCacheAfterVote} 
            index={index} 
            link={link} 
          />
        ))}
      </div>
    )
  }
}

const LINKS_SUBSCRIPTION = gql`
  subscription {
    Link(filter: { mutation_in: [CREATED] }) {
      node {
        id
        url
        description
        createdAt
        postedBy {
          id
          name
        }
        votes {
          id
          user {
            id
          }
        }
      }
    }
  }
`

export const ALL_LINKS_QUERY = gql`
  query AllLinksQuery {
    allLinks {
      id
      createdAt
      url
      description
      postedBy {
        id
        name
      }
      votes {
        id
        user {
          id
        }
      }
    }
  }
`

export default graphql(ALL_LINKS_QUERY, { name: 'allLinksQuery' }) (LinkList)
```

**Comment by oredi** [comment]
Hey @KeevanDance,

I found this by accident by maybe you can try locking your dependencies to the version found in package.json -> https://github.com/howtographql/react-apollo/blob/master/package.json. I believe this is the sample code of the tutorial. 

But if you want to live on the edge, I build a version for the new Apollo Client 2.0.
https://github.com/oredi/howtographql-react-apollo. There are some minor syntactical differences but it should behave the same.

**Comment by KeevanDance** [comment]
Yes, I believe this solved it. Thanks so much :)

**Comment by oredi** [comment]
@janzheng You can look at https://github.com/oredi/howtographql-react-apollo then. That uses Apollo 2.0

**Comment by janzheng** [comment]
@oredi very helpful, thanks very much

**Comment by lukehamilton** [comment]
I'm still unable to get subscriptions working. Specifically  `updateQuery` is not firing.

**Comment by speedtreammanga** [comment]
Having the same issue, `updateQuery` does not fire when a new Link is posted...

**Comment by nenjamin2405** [comment]
Having the same issue in the subscription, link list is not updated !
Moreover, the implementation of updating for adding new links in section 7/10 make the loading state in Link List component changed to true... I don't know why ?!. Does anyone have the same issue?

**Comment by smithaitufe** [comment]
@nenjamin2405 Where you are able to resolve this?

**Comment by nenjamin2405** [comment]
@smithaitufe I'm not sure because currently I'm using Rails as a backend for my app, so the implementation of subscription may be different from this. I see that there are some minor changes in github repository of this section, you can give it a try.

**Comment by smithaitufe** [comment]
@nenjamin2405 

Thanks for your reply. Which Github repository are you referring to particularly?

**Comment by nenjamin2405** [comment]
@smithaitufe
You can reference to this https://github.com/howtographql/react-apollo

**Comment by jonocodes** [comment]
Having the same problem here. My apollo-client is 2.3.4
If I 'submit' a new entry, it redirects back to the root which just does not include the new entry. This is true for the browser that submitted the entry. And the same goes for another browser watching the subscription. Which makes me think this is not related to subscriptions.

**Comment by amazing-space-invader** [comment]
Guys, do you have any solutions about `updateQuery`?

![image](https://user-images.githubusercontent.com/12794753/47001312-d3fddd80-d132-11e8-82e5-4b9cf4ee950f.png)
