### ISSUE TITLE
Write Expo Content

### ISSUE THREAD

**Issue by nikolasburk** [howtographql/howtographql#27]

**Comment by cseelus** [comment]
So from the looks of it, the Expo+Apollo tutorial is nothing to wait for, or am I missing something?

**Comment by TasinIshmam** [comment]
@cseelus  I'm afraid you're right. 

There isn't any notable progress on the Expo+Apollo tutorial at the moment and I wouldn't expect it to be published anytime soon. 

If we end up restarting this initiative, we will reopen this issue.

**Comment by brentvatne** [comment]
indeed, this is was something that we started working on in the days of graphcool but put on hold for a bit and then graphcool became prisma
