### ISSUE TITLE
Why am i getting just a text saying 'Loading' when i go to localhost:3000/graphiql

### ISSUE THREAD

**Issue by suyesh** [howtographql/howtographql#283]

**Comment by angly-cat** [comment]
Where did you get that link even? Is it from a path or..?

**Comment by suyesh** [comment]
its from this tutorial here https://www.howtographql.com/graphql-ruby/2-queries/

**Comment by nikolasburk** [comment]
Hi @suyesh, thanks a lot for opening the issue! This should have been fixed with the latest update for the Node tutorial 🙂
