### ISSUE TITLE
Graphene-Django released v2.0 - Tutorial Needs Updated

### ISSUE THREAD

**Issue by evanheckert** [howtographql/howtographql#285]
Since a graphene-django version isn't specified in the tutorial, the new v2.0 will be installed. There are breaking changes. Perhaps specifying the old version number prior to a new tutorial being written?

**Comment by rezaprimasatya** [comment]
Got some deprecated and when try to run mutation got error "graphql.error.located_error.GraphQLLocatedError: mutate() got an unexpected keyword argument 'url' "

**Comment by jonatasbaldin** [comment]
Yes, I know :( I need to update the tutorial to the version 2.0. 

Will do this ASAP.

**Comment by evanheckert** [comment]
@jonatasbaldin  Really appreciate it. I'm having a heck of a time trying to work my way around the very limited graphene-django documentation to get authentication working. Cheers!!

**Comment by joeydebreuk** [comment]
Can someone at least list all versions used with this tutorial?

**Comment by jonatasbaldin** [comment]
It's version `1.4.1`.

**Comment by jonatasbaldin** [comment]
I'll update everything this weekend, sorry for the delay folks :(

**Comment by jonatasbaldin** [comment]
The tutorial is updated! This can be closed 🎉
