### ISSUE TITLE
Authentication with GraphQL, React template email template returns "Unknown command: unknown"

### ISSUE THREAD

**Issue by kaspar-naaber** [howtographql/howtographql#295]
I have double checked everything and in my opinion I have followed the tutorial 100%. But I am stuck here: 

https://github.com/howtographql/howtographql/blob/master/content/frontend/react-apollo/5-authentication.md#enabling-email-and-password-authentication--updating-the-schema

The app runs fine on http://localhost:3000 but it seems that my project doesn't have *server* folder at all. Whenever I try to run this command – `graphcool add-template graphcool/templates/auth/email-password` – in the project's root folder it returns `Unknown command: unknown`.

Have I missed some tasks that should have generated the *server* folder?

**Comment by PaquitoSoft** [comment]
Same issue here
My "graphcool" version is 0.4.9

**Comment by angly-cat** [comment]
> I have followed the tutorial 100%

In "Getting Started" there's the instruction:
![](https://i.imgur.com/Sl2sbxR.png)

And project's folder structure with `server` folder:
![](https://user-images.githubusercontent.com/5000549/32797667-b2a6b34e-c99c-11e7-8183-771594aac48a.png)

**Comment by nikolasburk** [comment]
Thanks a lot for pointing this out @kaspar-naaber! This problem should have been fixed with the latest update to the React & Apollo tutorial?
