### ISSUE TITLE
Error Upon Creating New Link

### ISSUE THREAD

**Issue by cfisher440** [howtographql/howtographql#302]
I receive the following error message in the console when I create a link:

Warning: Encountered two children with the same key, `cj9sjedcyrdu90116q5fj8o0x`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

**Comment by angly-cat** [comment]
In which tutorial have you encountered this issue?

**Comment by nikolasburk** [comment]
Hi @cfisher440, thanks a lot for opening this issue 🙂  can you please specify when exactly you're seeing this message? Assuming it was in the React & Apollo tutorial, I believe it was fixed with the latest update. Please let know if you need further assistance and I'll reopen the issue 👍
