### ISSUE TITLE
Authentication Issue and Fix

### ISSUE THREAD

**Issue by cfisher440** [howtographql/howtographql#303]
This wasn't working for me. I was not able to log in. But I did fix it. I had to change the AUTHENTICATE_USER_MUTATION from this:

`const AUTHENTICATE_USER_MUTATION = gql`
  mutation AuthenticateUserMutation($email: String!, $password: String!) {
    authenticateUser(email: {
      email: $email,
      password: $password
    }) {
      token
      user {
        id
      }
    }
  }
``

to this:

`const AUTHENTICATE_USER_MUTATION = gql`
  mutation AuthenticateUserMutation($email: String!, $password: String!) {
    authenticateUser(email: $email, password: $password) {
      token
      id
      }
    }
``

I figured this out from the Graphcool playground where the mutations arguments and details lined up with what I changed the mutation to. Hope this helps someone having similar issues to me.﻿

You may even want to update the tutorial with this?

**Comment by nikolasburk** [comment]
Thanks for pointing this out @cfisher440, this was fixed with the latest update to the React & Apollo tutorials 🙂
