### ISSUE TITLE
CREATE_VOTE_MUTATION Problem / Fix

### ISSUE THREAD

**Issue by cfisher440** [howtographql/howtographql#304]
I was receiving an error in the console when I did an upvote: 

Store error: the application attempted to write an object with no provided id but the store already contains an id of Link:cj9sili1zqvn501310yix1dwt for this object. The selectionSet that was trying to be written is:
link {
  votes {
    id
    user {
      id
      __typename
    }
    __typename
  }
  __typename
}

I changed the CREATE_VOTE_MUTATION from this:

`const CREATE_VOTE_MUTATION = gql`
  mutation CreateVoteMutation($userId: ID!, $linkId: ID!) {
    createVote(userId: $userId, linkId: $linkId) {
      id
      link {
        votes {
          id
          user {
            id
          }
        }
      }
      user {
        id
      }
    }
  }
``

to this:

`const CREATE_VOTE_MUTATION = gql`
  mutation CreateVoteMutation($userId: ID!, $linkId: ID!) {
    createVote(userId: $userId, linkId: $linkId) {
      id
    link {
      id
    }
    user {
      id
    }
  }
}
``
And it fixed the problem. No more error messages. Hope this helps someone :-)﻿
You may want to update the tutorial?

**Comment by nikolasburk** [comment]
Thanks again @cfisher440 🙂  this also was fixed with the latest update! 👍
