### ISSUE TITLE
graphql-java graphiQL does not work

### ISSUE THREAD

**Issue by candysmurf** [howtographql/howtographql#306]
I cloned this repo for graphql-java. When going to http://localhost:8080 and explore schema from `doc`, it showed `No Schema Available`. When executing the below query, it returned empty string: ""
```
{
  allLinks {
    url
  }
}
```
When I went to this link:  http://localhost:8080/graphql?query={allLinks{url}} , I saw some data as below:
``` 
{"data":{"allLinks":[{"url":"http://howtographql.com5"},{"url":"http://howtographql.com5"},{"url":"http://howtographql.com6"},{"url":"http://www.graph.cool"}]}}
```
Did I miss anything for the embeded GraphQL IDE?

**Comment by candysmurf** [comment]
It's fine now.

**Comment by venkat86** [comment]
Hi candy,How to solve this problem?can u help me

**Comment by venkat86** [comment]
Hi candy,How to solve this problem?can u help me

**Comment by AbhinavA1990** [comment]
How to solve this @candysmurf
