### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by integratedinfosys** [howtographql/howtographql#307]
I am on https://www.howtographql.com/react-apollo/5-authentication/
Somehow I am unable to create new user. I am attaching the zipped files.

[hackernews-react-apollo.zip](https://github.com/howtographql/howtographql/files/1460956/hackernews-react-apollo.zip)

**Comment by janpauldahlke** [comment]
check here, maybe this?
https://github.com/howtographql/howtographql/issues/341

**Comment by thauvette** [comment]
I'm having the same issue. That fix did not work for me. I get the following error...

> DOMException: Failed to execute 'postMessage' on 'Window': Error: GraphQL error: function execution error: An unexpected error occured during signup. could not be cloned.

**Comment by thauvette** [comment]
I've got it working. I followed [this...](https://www.graph.cool/docs/tutorials/auth/authentication-with-email-and-password-for-react-and-apollo-cu3jah9ech) and changed my signup.ts to match [this...](https://github.com/graphcool-examples/react-graphql/blob/master/authentication-with-email-and-apollo/server/src/email-password/signup.js). 

Hope that helps.

**Comment by nikolasburk** [comment]
Hi @integratedinfosys, thanks a lot for opening this issue! 🙂  The problem was fixed with the latest update to the React & Apollo tutorial 👍
