### ISSUE TITLE
Apollo-React Lesson 3 yarn start not working

### ISSUE THREAD

**Issue by dd-beanz** [howtographql/howtographql#323]
When doing `yarn start` after writing and double checking everything `localhost:3000` is constantly loading and the linksToRender does not render on the page.

**Comment by nikolasburk** [comment]
Hi @dd-beanz, thanks a lot for opening this issue! 🙏  This should have been fixed with the latest update to the React & Apollo tutorial, please let me know if you have further questions 🙂
