### ISSUE TITLE
Build VulcanJS Example

### ISSUE THREAD

**Issue by nikolasburk** [howtographql/howtographql#33]

**Comment by Apollinaire** [comment]
Hello @nikolasburk ! 
I'm currently starting a new project and in the process of choosing the stack we're going to use. While Vulcan is definitely an option, the Graphcool framework + Apollo + React is too. 
So i was wondering what would be the contents of this example, would it be a pure Vulcan example as we can see some already [on their docs](http://docs.vulcanjs.org/example-movies.html), or something else, like a Graphcool backend with Vulcan on the front (if that is even possible).
Thanks!
