### ISSUE TITLE
youtube video captions

### ISSUE THREAD

**Issue by derevandal** [howtographql/howtographql#334]
Hi, could anyone turn on translations by community contributions?﻿
I wanna translate to PT-BR.

**Comment by klud1** [comment]
I could translate to latam spanish.

**Comment by nikolasburk** [comment]
Thanks for opening this issue @derevandal! I just enabled community contributions on the Fundamentals videos: https://www.youtube.com/watch?v=oCT4HOJsUZQ&list=PLn2e1F9Rfr6lrHAiPTCFtw9utqDUPwkrc

The other videos are outdated and will be replaced soon.

**Comment by ulm0** [comment]
@nikolasburk Great, will work on it asap.
