### ISSUE TITLE
Fourth answer is needed for angular/apollo/3-mutations-creating-links

### ISSUE THREAD

**Issue by jwestman-activelamp** [howtographql/howtographql#337]
The angular/apollo/3-mutations-creating-links section is missing its fourth answer which causes the question area to appear broken. I'm not sure what a good question would be... so I am creating an issue.
https://github.com/howtographql/howtographql/blob/master/content/frontend/angular-apollo/3-mutations-creating-links.md
![screen shot 2017-11-21 at 11 20 03 pm](https://user-images.githubusercontent.com/5176620/33112962-1d361878-cf13-11e7-969c-510624d94cc4.png)

**Comment by nikolasburk** [comment]
Thanks for pointing that out @jwestman-activelamp 🙏  I just added a new answer option 🙂
