### ISSUE TITLE
Some command not working (Graphcool tutorial)

### ISSUE THREAD

**Issue by Tankerxyz** [howtographql/howtographql#343]
Passing Graphcool tutorial, I noticed that command

```
graphcool init --schema https://graphqlbin.com/hn-starter.graphql --name Hackernews
```

not properly working. 
Graphcool prints:
```
Unknown flag --schema
```

**Comment by epitaphmike** [comment]
I can reproduce the issue with graphcool@0.10.1

**Comment by hoodsy** [comment]
Same here. Any way around this?

**Comment by Tankerxyz** [comment]
I think need to update tutorial, because in the new graphcool api we can't
use custom templates.

2017-12-09 23:14 GMT+02:00 Logan Bernard <notifications@github.com>:

**Comment by hoodsy** [comment]
It seems that they are rewriting tutorials to accommodate `graphcool-cli` changes: [Outdated Freecom Graphcool Tutorial](https://www.graph.cool/docs/tutorials/freecom/overview-e8a6ajt8ax)

Really hoping to use Graphcool once one of the tutorials is updated 😄

**Comment by HwasungKim** [comment]
I have an issue on making mutations with links because the description is not an attribute on the original scheme of hacker news 

 https://www.howtographql.com/react-relay/1-getting-started/

**Comment by nikolasburk** [comment]
Thanks a lot for pointing that out @Tankerxyz 🙏 The Graphcool Framework tutorial was removed in favor of an updated Node tutorial based on Prisma  🙂

**Comment by peterhchen** [comment]
> graphcool --help
The new version of graphcool does not have "--schema" or "--name" option.
I just use 
> graphcool init 
or
> graphcool init Hackernews
The files are created under the "Hackernews" folder.
