### ISSUE TITLE
issues about 5-authentication "authProvider" "signinUser"

### ISSUE THREAD

**Issue by HeathKang** [howtographql/howtographql#357]
Hi, I followed the tutorial about authentication by angular & apollo, but got some problems here.
1.in ```src/app/graphql.ts ```, I really confused by ```authProvider``` argument, because I didn't see this argument on the backend Mutation.
2.in same file, I didn't see ``` signinUser``` in backend Mutation too, maybe this means ``` authenticateUser```? 
```
import {Link, User} from './types';
// ...
export const CREATE_USER_MUTATION = gql`
  mutation CreateUserMutation($name: String!, $email: String!, $password: String!) {
    createUser(
      name: $name,
      authProvider: {
        email: {
          email: $email,
          password: $password
        }
      }
    ) {
      id
    }

    signinUser(email: {
      email: $email,
      password: $password
    }) {
      token
      user {
        id
      }
    }
  }
`;
```
I am a noob in angular and graphQL, so really need your help. Thanks a lot!

**Comment by HeathKang** [comment]
I fix this issues by changing my codes.
1.changed ```graphql.ts``` module``` CREATE_USER_MUTATION ``` and ```SigninUserMutation```  to(``` CreateUserMutation interface ``` and ``` SigninUserMutation interface ``` dosen't matter now):
```
export const CREATE_USER_MUTATION = gql`
  mutation CreateUserMutation($name: String!, $email: String!, $password: String!){
    signupUser(
      name: $name,
      email: $email,
      password: $password
    ){
      id
    }

    authenticateUser(
      email: $email,
      password: $password,
    ){
      token
      id
    }
  }
`;

export const SIGHIN_USER_MUTATION = gql`
mutation SigninUserMutation($email: String!, $password: String!) {
  authenticateUser(
    email: $email,
    password: $password
  ) {
    token
    id
  }
}
`;
```

2. changed ```login.component.ts``` ```confirm()```method to :
```
confirm() {
    if (this.login) {
      this.apollo.mutate({
        mutation: SIGHIN_USER_MUTATION,
        variables: {
          email: this.email,
          password: this.password
        },
      }).subscribe((result) => {
        console.log(result);
        const id = result.data.authenticateUser.id;
        const token = result.data.authenticateUser.token;
        this.saveUserData(id, token);

        this.router.navigate(['/']);
      }, (error) => {
        alert(error)
      });
    } else {
      this.apollo.mutate({
        mutation: CREATE_USER_MUTATION,
        variables: {
          name: this.name,
          email: this.email,
          password: this.password,
        }
      }).subscribe((result) => {
        const id = result.data.authenticateUser.id;
        const token = result.data.authenticateUser.token;

        this.saveUserData(id, token);

        this.router.navigate(['/']);
      }, (error) => {
        alert(error)
      })
    }
  }

```

And it works now. 
The new issue is I can't turn return data to adapt ```CreateUserMutationResponse``` interface , so  I can't unpack data to ``` result.data.signinUser.id ``` and ``` result.data.signinUser.token```.

**Comment by prashanthpi** [comment]
This worked for both Signup and Signin!!

/graphql.ts
...
export const CREATE_USER_MUTATION = gql`
mutation CreateUserMutation($name: String!, $email: String!, $password: String!){
    signupUser(
      name: $name,
      email: $email,
      password: $password
    ){
      id
    }

    authenticateUser(
      email: $email,
      password: $password,
    ){
      token
      id
    }
  }
`;

export interface CreateUserMutationResponse {
  loading: boolean;
  createUser: User;
  signinUser: {
    token: string,
    user?: User
  };
}

export const SIGNIN_USER_MUTATION = gql`
mutation SigninUserMutation($email: String!, $password: String!) {
    authenticateUser(
      email: $email,
      password: $password
    ) {
      token
      id
    }
  }
`;


export interface SigninUserMutationResponse {
  loading: boolean;
  signinUser: {
    token: string,
    user?: User
  };
}
...

/login.component.ts
...
confirm() {
    if (this.login) {
      this.apollo.mutate({
        mutation: SIGNIN_USER_MUTATION,
        variables: {
          email: this.email,
          password: this.password
        },
      }).subscribe((result) => {
        console.log(result);
        const id = result.data.authenticateUser.id;
        const token = result.data.authenticateUser.token;
        this.saveUserData(id, token);

        this.router.navigate(['/']);
      }, (error) => {
        alert(error)
      });
    } else {
      this.apollo.mutate({
        mutation: CREATE_USER_MUTATION,
        variables: {
          name: this.name,
          email: this.email,
          password: this.password,
        }
      }).subscribe((result) => {
        const id = result.data.authenticateUser.id;
        const token = result.data.authenticateUser.token;

        this.saveUserData(id, token);

        this.router.navigate(['/']);
      }, (error) => {
        alert(error)
      })
    }
  }
...

**Comment by nikolasburk** [comment]
Thanks a lot for pointing that out @HeathKang 🙏 The issue was fixed in the latest update to the React & Apollo tutorial 🙂

**Comment by MooDySmiles** [comment]
Hi!

Even the authentication tutorial for [Angular Apollo](https://www.howtographql.com/angular-apollo/5-authentication/), as it is rigth now, isn't working properly.

In the tutorial `authProvider` is used, but it is never explained and, more important, it's not a known element of the mutation (this is said by the error response when I try to execute the mutation). 

The solution proposed by @prashanthpi saved my day, many thanks to you!!
