### ISSUE TITLE
Adonis Example

### ISSUE THREAD

**Issue by lednhatkhanh** [howtographql/howtographql#360]
Since we now have the `apollo-server-adonis` package and Adonis Framework is getting more popularity in community. I think it would be great to have an example for Adonis.

**Comment by nikolasburk** [comment]
Hi @lednhatkhanh, thanks a lot for the suggestion! Do you know anyone who could contribute such a tutorial? If so, please [put them in touch with me](mailto:nikolas@graph.cool)  🙂
