### ISSUE TITLE
Connectors tutorial doesn't work with mongodb@3.0.0-rc0

### ISSUE THREAD

**Issue by vcanales** [howtographql/howtographql#363]
When doing `npm i mongodb`, I get that version by default, which doesn't work right out of the bat with the tutorial.

`npm i mongodb@^2` works.

Maybe consider specifying mongodb version while `^3` is still an `rc`, and later updating to the new API.

**Comment by blogscot** [comment]
To run the Connectors tutorial using "mongodb": "^3.0.1" you'll need to modify the code as follows:

```js
module.exports = async () => {
  const client = await MongoClient.connect(MONGO_URL)
  const db = client.db('hackernews')
  return { Links: db.collection('links') }
}
```

**Comment by vcanales** [comment]
Tackled in https://github.com/howtographql/howtographql/pull/395, just to keep track :)

**Comment by nikolasburk** [comment]
Thanks a lot for pointing that out @vcanales  🙏  As mentioned in #395, the issue was fixed in the latest update of the Node tutorial.
