### ISSUE TITLE
Where to find apollo.config.ts file while Configuring the ApolloClient? Angulat+Graphql

### ISSUE THREAD

**Issue by javatutoronline** [howtographql/howtographql#369]
I am following the guide https://www.howtographql.com/angular-apollo/1-getting-started/ to integrate angular with graphql.

I am not able to find the apollo.config.ts file in the generated folder structure.

Can anybody help.

**Comment by MohammedSiddiqui10p** [comment]
You have to create a new ts file inside your app folder.
hence the path would be src/app/apollo.config.ts
and then copy the contents shown in the example into this file.

**Comment by nikolasburk** [comment]
Thanks @MohammedSiddiqui10p for answering the question! Please let me know if you have further issues @javatutoronline 🙌
