### ISSUE TITLE
Java and Javascript Tutorials Have Titles Switched

### ISSUE THREAD

**Issue by machineghost** [howtographql/howtographql#371]
https://www.howtographql.com/graphql-js/8-error-handling/ (note the `-js` part) has a `<title>` of "Error Handling with GraphQL &amp; Java Tutorial" (note the "Java").

Similarly https://www.howtographql.com/graphql-java/7-error-handling/ (note the `-java` part) has a `<title> of "Error Handling with GraphQL &amp; Javascript Tutorial" (note the "Javascript").

It seems that someone mistakenly switched these.

**Comment by nikolasburk** [comment]
Thanks a lot @machineghost, I just fixed the issue 🙌
