### ISSUE TITLE
subscriotions-transport-ws unresolved

### ISSUE THREAD

**Issue by janat08** [howtographql/howtographql#375]
./node_modules/apollo-link-ws/lib/webSocketLink.js
Module not found: Can't resolve 'subscriptions-transport-ws' in '/home/jk/Documents/graphTutorial/hackernews-react-apollo/node_modules/apollo-link-ws/lib'

Sounds like an actual lib problem, but wtv. Following subscriptions chapter in apollo/react.

**Comment by JohnIrle** [comment]
I just did 'yarn add subscriptions-transport-ws' and it worked. It does feel like a workaround though.

**Comment by supergoat** [comment]
any updates on this?

**Comment by nikolasburk** [comment]
Hi @janat08, thanks a lot for pointing this out! 🙏  This was fixed in the latest update of the tutorial 🙂
