### ISSUE TITLE
Graphcool server start problem -graphcool-framework init server

### ISSUE THREAD

**Issue by javatutoronline** [howtographql/howtographql#387]
After doing npm install -g graphcool-framework
When I am doing   graphcool-framework init server
I am getting this error

 !    'ENOENT': ENOENT: no such file or directory, lstat 'C:\Users\pchin\.graphcool'

**Comment by lunchboxer** [comment]
see [graphcool-framework #1451](https://github.com/graphcool/framework/issues/1451). I believe you can fix this problem by creating a .graphcool directory in your user directory. Otherwise, just use an earlier version of graphcool

**Comment by nikolasburk** [comment]
Hi @javatutoronline, thanks again for opening this issue! This should have been fixed with the latest tutorial update 🙂
