### ISSUE TITLE
Error when using mongodb 3

### ISSUE THREAD

**Issue by cmarchena** [howtographql/howtographql#391]
(node:12420) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: db.collection is not a function
(node:12420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Downloading to 2.2.33 solves the problem

**Comment by KevinAsher** [comment]
Updating the mongo-connector.js to the following code fixed the problem.

```
const { MongoClient } = require('mongodb');

const MONGO_URL = 'mongodb://localhost:27017';

module.exports = async () => {
    const client = await MongoClient.connect(MONGO_URL);    
    const db = client.db('hackernews');
    return { Links: db.collection('links') };  
}
```

**Comment by vcanales** [comment]
Duplicate: https://github.com/howtographql/howtographql/issues/363

**Comment by nikolasburk** [comment]
Thanks a lot for pointing that out @cmarchena 🙏 The issue was fixed in the latest update to the Node tutorial 🙂
