### ISSUE TITLE
Error while creating link in React-Apollo hackernews tutorial.

### ISSUE THREAD

**Issue by Reyhanahmed** [howtographql/howtographql#394]
I have been following the React-Apollo Hackernews course but I am stuck with an issue.
While I am creating new link an error seems to pop up.

`createLink error GraphQL error: Variable '$postedById' of type 'ID!' used in position expecting type 'LinkpostedByUser'. (line 1, column 67):
mutation CreateLinkMutation($description: String!, $url: String!, $postedById: ID!) {
                                                                  ^
 (line 2, column 62):
  createLink(description: $description, url: $url, postedBy: $postedById) {`

My createLink Mutation is
``const CREATE_LINK_MUTATION = gql`
	mutation `CreateLinkMutation(
		$description: String!
		$url: String!
		$postedById: ID!
	) {
		createLink(description: $description, url: $url, postedBy: $postedById) {
			id
			createdAt
			url
			description
			postedBy {
				id
				name
			}
		}
	}
`;``

The function which is called when new link is submitted;
`_createLink = async () => {
		const postedById = localStorage.getItem(GC_USER_ID);
		if (!postedById) {
			console.error("No user logged in!");
			return;
		}
		const { description, url } = this.state;
		try {
			await this.props.createLinkMutation({
				variables: {
					description,
					url,
					postedById
				},
				update: (store, { data: { createLink } }) => {
					const first = LINKS_PER_PAGE;
					const skip = 0;
					const orderBy = "createdAt_DESC";
					const data = store.readQuery({
						query: ALL_LINKS_QUERY,
						variables: { first, skip, orderBy }
					});
					data.allLinks.splice(0, 0, createLink);
					data.allLinks.pop();
					store.writeQuery({
						query: ALL_LINKS_QUERY,
						data,
						variables: { first, skip, orderBy }
					});
				}
			});
			this.props.history.push("/new/1");
		} catch (error) {
			console.log("createLink error", error.message);
		}
	};`

**Comment by tuanluu-agilityio** [comment]
Hi @Reyhanahmed ,


```
const CREATE_LINK_MUTATION = gql` 
   mutation `CreateLinkMutation( $description: String! $url: String! $postedById: ID! ) { 
     createLink(description: $description, url: $url, postedBy: $postedById) { 
       id
      createdAt
      url
      description
      postedBy { 
        id
        name
      }
   }
} `;
```
You can update `createLink(description: $description, url: $url, postedBy: $postedById) {` to `createLink(description: $description, url: $url, postedById: $postedById) {`
I think it should be `postedById` instead `postedBy` field because you using variables with `postedById`, not `postedBy`.

Please format your code when you raise issue. It better than for everyone detect your issue.

Thanks,

**Comment by nikolasburk** [comment]
Thanks a lot for pointing that out @Reyhanahmed and thanks to @tuanluu-agilityio for answering already 🙏 The issue was fixed in the latest update to the React & Apollo tutorial 🙂
