### ISSUE TITLE
React + Apollo Tutorial Section 4 Routing - After creating link, routing back to Linklist doesn't get updated with data

### ISSUE THREAD

**Issue by sandeepkumar03** [howtographql/howtographql#403]
Steps to reproduce

1. Follow steps as per https://www.howtographql.com/react-apollo/4-routing/  (Assuming first 3 parts are already followed)
2. Last part talks about routing back to Link list using `this.props.history.push('/')`
3. Note that new link is getting created but after routing it is not visible in link list view
4. Refresh the browser, newly created link is visible

**Comment by lunchboxer** [comment]
I think that's intentional. In later sections it's shown how to deal with this problem, using the update method so that Apollo's cache is accurate and the UI updates. Or perhaps I have misunderstood your issue?

**Comment by sandeepkumar03** [comment]
I guess you are correct. Thanks

**Comment by moncefguettat** [comment]
@sandeepkumar03 how did you fix this issue, please? I'm having the same problem after navigating the list it won't get changed only after refreshing
