### ISSUE TITLE
Error in backend server conection 

### ISSUE THREAD

**Issue by jhudaz** [howtographql/howtographql#407]
I have following the react + apollo tutorial but with the new modifications  in the server's directory i try to run it with yarn start command but in the moment that i go to localhost:4000 my terminal throw this error

TypeError: Cannot read property 'publicClusters' of undefined
    at Environment.<anonymous> (/home/jaime/react-apollo/server/node_modules/graphcool-yml/dist/Environment.js:103:39)
    at step (/home/jaime/react-apollo/server/node_modules/graphcool-yml/dist/Environment.js:40:23)
    at Object.next (/home/jaime/react-apollo/server/node_modules/graphcool-yml/dist/Environment.js:21:53)
    at fulfilled (/home/jaime/react-apollo/server/node_modules/graphcool-yml/dist/Environment.js:12:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:9761) UnhandledPromiseRejectionWarning: Error: No cluster set. Please set the "cluster" property in your graphcool.yml
    at /home/jaime/react-apollo/server/node_modules/graphql-config-extension-graphcool/dist/index.js:137:31
    at step (/home/jaime/react-apollo/server/node_modules/graphql-config-extension-graphcool/dist/index.js:40:23)
    at Object.next (/home/jaime/react-apollo/server/node_modules/graphql-config-extension-graphcool/dist/index.js:21:53)
    at fulfilled (/home/jaime/react-apollo/server/node_modules/graphql-config-extension-graphcool/dist/index.js:12:58)
    at <anonymous>
(node:9761) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9761) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

# app package.json 

{
  "name": "hackernews-react-apollo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "apollo-client": "^2.2.0",
    "apollo-client-preset": "^1.0.6",
    "apollo-link": "^1.0.7",
    "apollo-link-ws": "^1.0.4",
    "graphql": "^0.12.3",
    "graphql-tag": "^2.6.1",
    "react": "^16.2.0",
    "react-apollo": "^2.0.4",
    "react-dom": "^16.2.0",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.0.17",
    "subscriptions-transport-ws": "^0.9.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

# server package.json
{
  "name": "hackernews-node",
  "scripts": {
    "start": "NODE_ENV=dev node src/index.js",
    "playground": "graphql playground",
    "deploy": "now --public && now alias && now rm --yes --safe graphql-template-node"
  },
  "dependencies": {
    "bcryptjs": "^2.4.3",
    "graphcool-binding": "1.3.3",
    "graphql-yoga": "1.1.4",
    "jsonwebtoken": "^8.1.0"
  },
  "devDependencies": {
    "now": "9.0.1"
  },
  "now": {
    "alias": "graphql-template-node"
  }
}

**Comment by vctormb** [comment]
I'm having this problem too!
If do not remove the "NODE_ENV=dev" from package.json "start", an error appears: "node_env is not recognized as an internal or external command".
If I remove it, the same error posted by @jhudaz appears.

**Comment by andrico1234** [comment]
@vctormb @jhudaz add this to your package.json file

`"start": "SET NODE_ENV=dev && node src/index.js"`

everything worked fine after, it seemed my terminal attempted to run NODE_ENV as a command which caused the program to shit over itself.

**Comment by vctormb** [comment]
@andrico1234  Thank you! It worked very well!!!!!

**Comment by cborchert** [comment]
I ran into a similar issue, and was able to overcome it using a variation of @andrico1234's solution. 
Hopefully others will find this useful:

If, after the changes to `./server/package.json` proposed by @andrico1234 you still get an error, along the lines of `sh: SET: command not found`, you're probably on a mac. You just need to remove the SET part.
Update the scripts section of your `./server/package.json` file to look like:

```json
"scripts": {
    "start": "SET NODE_ENV=dev && node src/index.js",
    "playground": "graphql playground"
  }
```

**Comment by nikolasburk** [comment]
Thanks a lot for pointing that out @jhudaz 🙏 The issue was fixed in the latest update to the React & Apollo tutorial 🙂
