### ISSUE TITLE
server not working

### ISSUE THREAD

**Issue by bradwoods** [howtographql/howtographql#417]
Following the tutorial @ https://www.howtographql.com/react-apollo/1-getting-started/

After starting the server I get the following errors in the playground:
on the app layer:
```
{
  "data": null, 
  "errors": [
    {
      "message": "Project not found: 'hackernews-node-02@dev'",
      "locations": [],
      "path": []
    }
  ]
}
```

on the dev layer:
```
Schema could not be fetched.
Please check if the endpoint 'http://localhost:60000/hackernews-node-02/dev' is a valid GraphQL Endpoint.
```

on the dev layer (after attempting to execute the mutation functions):
```
{
  "errors": [
    {
      "code": 3016,
      "requestId": "api:api:cjcegzn6k01840163r1fq0i0n",
      "message": "Project not found: 'hackernews-node-02@dev'"
    }
  ]
}
```

**Comment by nikolasburk** [comment]
Thanks a lot for pointing that out @bradwoods  🙏 The issue was fixed in the latest update to the React & Apollo tutorial 🙂
