### ISSUE TITLE
Website Feedback

### ISSUE THREAD

**Issue by nikolasburk** [howtographql/howtographql#42]
![image](https://user-images.githubusercontent.com/4058327/27906010-1d96265c-6242-11e7-8f84-ab60407a61f5.png)

Caption not centered below image

**Comment by sorenbs** [comment]
Code snippets look weird when the code is very short:

![image](https://user-images.githubusercontent.com/281337/28068610-9578e238-6646-11e7-9ebb-00fb69b76adf.png)

**Comment by sorenbs** [comment]
The code snippet here looks weird
![image](https://user-images.githubusercontent.com/281337/28068784-4de708ea-6647-11e7-975b-1e3481df6333.png)
https://www.howtographql.com/graphql-java/4-connectors/

**Comment by schickling** [comment]
![image](https://user-images.githubusercontent.com/1567498/28073287-27e06eb2-660a-11e7-89ff-02d7048b138b.png)

**Comment by schickling** [comment]
![image](https://user-images.githubusercontent.com/1567498/28073606-16d5f582-660b-11e7-962f-31b8b93fdff0.png)

**Comment by schickling** [comment]
![image uploaded from ios](https://user-images.githubusercontent.com/1567498/28073614-21368898-660b-11e7-8033-edb47561ba29.jpg)

**Comment by lucasconstantino** [comment]
I'm experiencing a horizontal scroll on the home page
