### ISSUE TITLE
Prisma tutorial playground missing left side menu

### ISSUE THREAD

**Issue by SlowburnAZ** [howtographql/howtographql#423]
Trying to follow the Prisma tutorial (https://www.howtographql.com/graphql-js/2-queries/), and when it has you open the playground, there's no left-side menu where you can select the two different APIs.  The tutorial shows this:  

![image](https://user-images.githubusercontent.com/5659169/35073407-e6bbe43e-fba5-11e7-8522-a4eeeabcf228.png)

However, when I run the `yarn start` command, I get the following:

![image](https://user-images.githubusercontent.com/5659169/35073447-10e9f4bc-fba6-11e7-990f-3268c46f2344.png)

Is there a missing setting somewhere that's not mentioned in the tutorial?

**Comment by ShredderMing** [comment]
try `yarn run dev`

**Comment by SlowburnAZ** [comment]
Yup, that works.  Thanks!

Hopefully this will be updated in the tutorial.

**Comment by cborchert** [comment]
I'm having the same issue as @SlowburnAZ but @ShredderMing's solution isn't working for me (since package.json does not have a dev script). Is this something that is missing but should be included in package.json?

**Comment by nikolasburk** [comment]
Thanks a lot for pointing this out @SlowburnAZ and @ShredderMing for helping out! 🙏  the tutorial was updated accordingly 🙂

**Comment by ejf89** [comment]
@SlowburnAZ @nikolasburk I dont see a yarn run dev script or changes in the tutorial. any tips would be appreciated

**Comment by wilsonpyc** [comment]
> try `yarn run dev`

yarn run v1.13.0
error Command "dev" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ejf89** [comment]
@wilsonpyc thx for the suggestion but this unfortunately does not solve the problem as there is not dev script declared. I believe the issue is in the the missing file supposed to be generated for the playground app to read

**Comment by jonatasbaldin** [comment]
hey @nikolasburk, can u retake a look on this?

**Comment by carlo-fontanos** [comment]
`$ yarn run dev
yarn run v1.0.2
error Command "dev" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by julianeden** [comment]
Same here, that script is not part of the project for me

**Comment by mattc41190** [comment]
Happening for me as well

**Comment by TolikTelia** [comment]
Same

![Playground - http:::localhost:4000: 2019-04-10 12-46-22](https://user-images.githubusercontent.com/38989553/55869205-bb74fa00-5b8e-11e9-9b3c-5a50746ed1bd.png)

**Comment by sobrio** [comment]
Same
![screenshot-localhost-4000-2019 04 11-17-27-28](https://user-images.githubusercontent.com/3015939/55970043-1c7bfb00-5c7f-11e9-90df-aa0d41b41ae2.png)

**Comment by Edrees** [comment]
Same issue

**Comment by MirelesCloud** [comment]
Same here

**Comment by jatinderchima** [comment]
Same issue using npm. Any updates on this?

**Comment by NelsonG-C** [comment]
I'm having the same issues, command "dev" not found

**Comment by ChaonanLin** [comment]
same here... anyone has a new solution?

**Comment by kavin2606** [comment]
Did anyone manage to solve this issue?

**Comment by alextraykov** [comment]
Same issue? Any tips?

**Comment by SlowburnAZ** [comment]
Hey all...  sorry I've been non-responsive.

When I originally submitted this issue, IIRC, I was missing the 'dev' command in my package.json file...  the one in my /server directory.

Had to look on an old machine to find this, but the "scripts" in my package.json looked like so:
`
"scripts": {
  "start": "node src/index.js",
  "dev": "npm-run-all --parallel start playground",
  "playground": "graphql playground",
  "prisma": "prisma"
}
`

Then I was able to run `yarn run dev` and when the browser pulled up localhost:3000/playground, the left-hand menu was visible.

I have no idea if it still works, as I'm sure the tutorial (and hence, the packages used) has been updated since then, but I suppose it's worth a shot.

**Comment by teddydengwork2018** [comment]
Still not works. Anyone solved?

**Comment by arstrel** [comment]
$ npm-run-all --parallel start playground
/bin/sh: npm-run-all: command not found
error Command failed with exit code 127.

**Comment by michaelkilburg** [comment]
I too am having the same problem - no left side menu visible, and "yarn run dev" doesn't work for me. When I try to run the 2 mutations in the editor pane, I get a timeout.

**Comment by JonAmparo** [comment]
Same, running through the same issues with the docs.

**Comment by steric85** [comment]
Running `yarn dev` doesn't open the playground with left-side menu. Can you please help? @SlowburnAZ @nikolasburk @ShredderMing
