### ISSUE TITLE
React + Apollo 6 - Error when voting for a link

### ISSUE THREAD

**Issue by veksen** [howtographql/howtographql#441]
Hiya! I'm following along with the React + Apollo guide. At step 6 (More Mutations and Updating the Store). In the second part of the guide, we're adding updating the store when voting for a link.

This causes a console error:

```
Error: Can't find field feed({}) on object (ROOT_QUERY) {
  "feed({\"first\":null,\"skip\":null,\"orderBy\":null})": {
    "type": "id",
    "id": "$ROOT_QUERY.feed({\"first\":null,\"skip\":null,\"orderBy\":null})",
    "generated": true
  }
}.
```

This error traces back down to `LinkList:32` and `Link.js:43`:

```js
// LinkList:32
  _updateCacheAfterVote = (store, createVote, linkId) => {
    // 1
    const data = store.readQuery({ query: FEED_QUERY }) // line 32

    // 2
    const votedLink = data.feed.links.find(link => link.id === linkId)
    votedLink.votes = createVote.link.votes

    // 3
    store.writeQuery({ query: FEED_QUERY, data })
  }
```

```js
// Link.js:43
update: (store, { data: { vote } }) => {
  this.props.updateStoreAfterVote(store, vote, linkId) // line 43
},
```

Commenting out the update within _voteForLink removes the problem.

I could be at fault, but I went back 2-3 times to make sure I got everything.

See, or checkout: https://github.com/veksen/hackernews-react-apollo/commit/f42148103e61c757008bf84ee823b43fe47bd72a

**Comment by veksen** [comment]
This is resolved by the pull request: https://github.com/howtographql/howtographql/pull/428

**Comment by nikolasburk** [comment]
Thanks a lot for pointing this out @veksen 🙌
