### ISSUE TITLE
Cannot connect to PRISMA db Service Queries section

### ISSUE THREAD

**Issue by iuliaL** [howtographql/howtographql#442]
When I start the playground with `yarn dev` ( `yarn start` does not show the left side menu ) and try to use the feed query I get a response that looks like this:

```
{
  "data": null,
  "errors": [
    {
      "message": "request to http://localhost:60000/hackernews-node/dev failed, reason: connect ECONNREFUSED 127.0.0.1:60000",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "feed"
      ]
    }
  ]
}
```

**Comment by nikolasburk** [comment]
Hi @iuliaL, thanks for opening this issue! 🙏  The `feed` query can only be sent in the `app` Playground, not `in the `database` Playground. (You can check which API operations are allowed by opening the docs by clicking on the green SCHEMA-button on the right). Please let me know if you have further questions 🙂
