### ISSUE TITLE
React-Apollo Ch.5 Authentication Quiz Answer

### ISSUE THREAD

**Issue by aeblin** [howtographql/howtographql#445]
Hey there, it looks like the quiz answer for the Authentication chapter is keyed to the wrong answer. 
**How are HTTP requests send by ApolloClient authenticated?**

From running through the chapter, it seems like the correct answer should be via the Apollo Link middleware that's implemented throughout. Instead, the correct answer is keyed to 
"ApolloClient exposes an extra method called 'authenticate' where you can pass an authentication token"

I can't find anything in the chapter or in Apollo's official documentation that supports this being the correct answer.

**Comment by nikolasburk** [comment]
Hey @aeblin, thanks so much for pointing this out! You're absolutely right 👍  

*CONGRATULATIONS, THIS WAS THE ACTUAL TEST!!!!!!* (just kidding, but hey, here's a medal 🥇 )

**Comment by biqing** [comment]
Hi @nikolasburk, I just encounter the same mistake, and I've checked the original document on Github, which shows you've already fixed that. Just wonder if the page of the website should be re-generated, to make it work?

I found the Ch.6's quiz answer maybe also wrong, and the right answer should be "It allows to update the local Apollo store in an imperative fashion". 

I'm just a newbie, please let me know if I am right, thank you.

**Comment by nikolasburk** [comment]
Hey @biqing, thanks for pointing this out for chapter 6! You're also correct that the answer was wrong, I just fixed that.

Thanks also for mentioning that the site actually wasn't updated even after updating the content. Turns out out build was broken - I just fixed that as well and all changes are now automatically deployed again!
