### ISSUE TITLE
Queries: Loading Links Issue: Links to Render does not display links

### ISSUE THREAD

**Issue by mtrivera** [howtographql/howtographql#505]
I'm on the **Preparing the React components** section and the last step does not display links. I get the error: 
`./src/index.js
Module not found: Can't resolve './App' in 'D:\Sandbox\hackernews-react-apollo\src'`

I followed the steps and used the `yarn start` command.

**Comment by nikolasburk** [comment]
Hi @mtrivera, thanks for opening the issue 🙂 

`App.js` should be located in the `components` directory, so the import statement for it in `index.js` needs to look as follows:

```js
import App from './components/App'
```

You can also verify what the code needs to look like [here](https://github.com/howtographql/react-apollo/blob/master/src/index.js).
