### ISSUE TITLE
Links are hard to find inside instruction blocks

### ISSUE THREAD

**Issue by mairatma** [howtographql/howtographql#51]
I've just noticed that links inside instruction blocks are not very noticeable. They look like regular text unless tou actually try hovering over them, which can be bad in some cases, as the reader needs to know about the link beforehand.

For example, without hovering:
<img width="837" alt="screen shot 2017-07-10 at 4 10 59 pm" src="https://user-images.githubusercontent.com/5216049/28035304-966d3e8a-658a-11e7-9222-17b51901a0bd.png">

After hovering:
<img width="837" alt="screen shot 2017-07-10 at 4 11 08 pm" src="https://user-images.githubusercontent.com/5216049/28035320-9f966770-658a-11e7-9a33-f889163f90f7.png">

I'd expect the links to show up as bold text or another color, like they do outside instruction blocks, for example:

<img width="298" alt="screen shot 2017-07-10 at 4 13 56 pm" src="https://user-images.githubusercontent.com/5216049/28035366-ce263b06-658a-11e7-882b-031295a58782.png">

Just a suggestion :)

**Comment by timsuchanek** [comment]
That's a very good point! I think we'll just make them bold :)
