### ISSUE TITLE
 (Apollo + React) Trouble to understand Realtime Updates

### ISSUE THREAD

**Issue by AlexandreRgx** [howtographql/howtographql#517]
I have trouble to understand the end of [this chapter](https://www.howtographql.com/react-apollo/8-subscriptions/)

The last given code aims at updating the number of votes using subscribtion events:
```javascript
 updateQuery: (previous, { subscriptionData }) => {
      console.log(`NEW VOTE`)
      const votedLinkIndex = previous.feed.links.findIndex(
        link => link.id === subscriptionData.data.newVote.node.link.id,
      )
      const newAllLinks = previous.feed.links.slice()
      const result = {
        ...previous,
        allLinks: newAllLinks,
      }
      return result
    },
  })
```
This code works, but:

- What is the purpose of `votedLinkIndex` since this variable is not used ?
- What is the purpose of `allLinks` in the `result` object ?

To understand, I rewrote the updateQuery function as follows:

```javascript
updateQuery: (previous, { subscriptionData }) => {
    const result = {
      ...previous
    }
    return result
  },
```
and I obtained the exact same results. So the `previous` parameter already contains the updated link list ? 

PS: I tested with two different browsers in parrarel (to observe updates), so the browser cache should be different.

**Comment by swcarlosrj** [comment]
Thanks @AlexandreRgx for opening this issue 😄. It should be fixed. Closing this!
