### ISSUE TITLE
Apollo + React - Port interoperability issue

### ISSUE THREAD

**Issue by DevNicoT** [howtographql/howtographql#518]
Hi guys,

First of all thanks for all the efforts behind this. It is indeed an amazing project!

My first GitHub issue here, and not claiming to be coming from an expert :) , so please acknowledge this if there's something ridiculously obvious I am missing.

Having said so, here's what I'm getting. I've gone alright with everything 'til the moment I need to start both the server and the front-end. My problem specifically happens with ports.

**How to reproduce it:**

1. 
`cd` into `server` folder and `yarn dev` from there. It opens the playground in `localhost:3000/playground`.
2. 
from another terminal tab/window, `cd` to project root ('hackernews...'), and `yarn start` from there. It will ask:
```
Something is already running on port 3000. Probably:
node home/my_username/my_path/hackernews-react-apollo/server/node_modules/.bin/graphql playground (pid PID_NUMBER_HERE)
in home/my_username/my_path/hackernews-react-apollo/server

Would you like to run the app on another port instead? Y/n
```
3.
Either of my options here would not bring me to the place I want. Obviously `'no'` will just not open the front-end and stop. But `'Yes'` will open it in `localhost:3001` and then when I do the mutations, the playground will not acknowledge them (?) at all. 
I checked the log from the server in the terminal and confirm the playground logs the queries, but no mutation at all in the above case.

**Environment:**

Tried this on Windows 10 and Ubuntu 17.10 with similar results.

********

Sorry, just one more thing, I dug a little and tried to hardcode the port in the `server/src/index.js`, tweaking a little the code at the end, like:

```
const options = {
    port: 4000,
    playground: './playground'
}
```

and then add the options, like:

`server.start(options, ({port}) => console.log(`Server is running on port ${port}`) )`

but to be honest that didn't change any bit. I should probably dig deeper into the config files, but I don't know if I'm missing something obvious or which of the libraries' config is the one causing this port problem.

Any ideas? Would be glad to collaborate if I humbly can, although as of now, no idea how.
Thanks in advance!

**Comment by bdmackie** [comment]
I hit this too. Looks like the server port for the playground isn't recognising the config.

For getting the react tutorial working, best to change the port of the front end as per https://github.com/facebook/create-react-app/issues/1083

**Comment by DevNicoT** [comment]
Thank you, @bdmackie! 
That totally did it in my case.
