### ISSUE TITLE
error Command "prisma" not found

### ISSUE THREAD

**Issue by greygatch** [howtographql/howtographql#519]
The tutorial for Apollo+React says to navigate to this folder and run this command.

It results in the above error.

**Comment by DevNicoT** [comment]
I take it you refer to the `server` folder, that is: `hackernews-react-apollo/server`.

Did you try `yarn prisma deploy` instead? That should do it, the reason being you haven't installed _prisma_ itself globally, so it's not recognized as a command.

Another option is if you want to just intall prisma globally, that is: `npm install -g prisma`, like it's mentioned in the notes below the snippet.

Did that help?

**Comment by greygatch** [comment]
Yes, was able to work around with it. Just creating the issue to smooth out the process. :)

**Comment by Nargonath** [comment]
Perhaps the problem comes from the fact that your `yarn global bin` path was not  in your PATH, at least it was the problem for me. After adding: `export PATH="$PATH:$(yarn global bin)"` to my `.bashrc` it worked smoothly.

**Comment by swcarlosrj** [comment]
Thanks @greygatch for opening this issue 😄.It should be fixed. Closing this!

**Comment by JOHNFLEURIMOND** [comment]
> Perhaps the problem comes from the fact that your `yarn global bin` path was not in your PATH, at least it was the problem for me. After adding: `export PATH="$PATH:$(yarn global bin)"` to my `.bashrc` it worked smoothly.

I have a similar problem on my project and I tried to watch a video on how to add a $PATH but it didnt work it said no such file or directory.

https://github.com/JOHNFLEURIMOND/ReactGraphQL/issues

**Comment by raniel90** [comment]
works for me with

`npm install -g prisma`

**Comment by yogesnsamy** [comment]
on ubuntu install prisma globally with admin rights --> `sudo npm install -g prisma`

**Comment by Nargonath** [comment]
@yogesnsamy Usually it is not a good idea to use `sudo` with `npm`. There is a way you can do it without it: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally.

**Comment by nickdevyyc** [comment]
After successfully installing Prisma with `npm install -g prisma` I started to get this error when I had to enter the next command  (`prisma login`) for the course I am taking.

FYI: also tried installing Prisma again a second way (`npm i -g prisma`) just in case it didn't work properly.

![Screen Shot 2020-04-18 at 8 44 12 PM](https://user-images.githubusercontent.com/11930159/79678142-67472180-81b5-11ea-9c27-32595aaa5711.jpg)
 

Any idea what needs to be done?

**Comment by stephanlevi** [comment]
@nickdevyyc 
i had exactly the same problem
just install prisma in the global scope
npm install prisma -g
restart the terminal/ide or run sources
that is it

**Comment by nickdevyyc** [comment]
> @nickdevyyc 
> 
> i had exactly the same problem
> 
> just install prisma in the global scope
> 
> npm install prisma -g
> 
> restart the terminal/ide or run sources
> 
> that is it

That doesn’t work my friend. On api.prisma.io after logging in I’m trying to login and I still get that error. Clearly there’s something wrong. This really shouldn’t require a google search when the answer should be quite simple.

**Comment by nikolasburk** [comment]
Hey @nickdevyyc 👋 the tutorial is slightly outdated and is currently being updated. The `prisma` npm package has been renamed to `prisma1`. So you probably want to install: `npm install -g prisma1`. Then you can inoke it as:

```
$ prisma1

# or 

$ prisma1 deploy
```

**Comment by michalgregu** [comment]
prisma1: command not found
same thing!

**Comment by harmandeep-singh** [comment]
i am using yarn , but failed many time ,End up using (successfully) 
npx prisma init  

inside WSL2 with ZSH Shell

**Comment by Martinsngene** [comment]
> 

Worked for me! Thanks a bunch
