### ISSUE TITLE
Graphcool chapter not working

### ISSUE THREAD

**Issue by sirLisko** [howtographql/howtographql#522]
Getting 404 trying to access https://www.howtographql.com/graphcool/0-introduction/.

<img width="591" alt="screen shot 2018-02-25 at 13 56 45" src="https://user-images.githubusercontent.com/435399/36642197-d0824f1c-1a33-11e8-8c91-bf5d78868a30.png">

**Comment by DevNicoT** [comment]
Hi @sirLisko ,

Which part or section are you trying to access? I can tell at least the beginning is [here](https://www.howtographql.com/basics/0-introduction/), but I don't know if you're trying to access any other section?

**Comment by sirLisko** [comment]
Just seen this https://github.com/howtographql/howtographql/commit/b025f3a3628c2e2d2a6ba43436c4acac655d6157.

Apparently, the **graphcool** tutorial has been deleted 😞 

I am pretty sure I followed some internal link, but I can't find it anymore.

**Comment by edmundo096** [comment]
I think it was updated to https://www.howtographql.com/graphql-js/0-introduction/

**Comment by sirLisko** [comment]
@edmundo096 not sure, it seems unrelated to graphcool 🤔

**Comment by DevNicoT** [comment]
Yes, [`graphql-js`](https://github.com/graphql/graphql-js) is an implementation in Node.

I guess now that you found that commit, the '`rich-diff`' view will have to do. :) Just maybe pretend you're looking at the website, and not at the commit. Just an idea.

Here is a screenshot, also pointing to where you display the `rich-diff`.

![github_richdiff](https://user-images.githubusercontent.com/29393294/36824253-5724c1c0-1d3c-11e8-9261-8d77990df722.png)

**Comment by nikolasburk** [comment]
Hey @sirLisko, thanks a lot for opening this issue!

The Graphcool tutorial was indeed deleted because it was quite outdated. However, the graphql-js tutorial was updated to use [Prisma](https://blog.graph.cool/introducing-prisma-1ff423fd629e) (Graphcool's latest product release) as a database layer. 

Let me know if you have any further questions 🙂
