### ISSUE TITLE
Why is the website not syncronized with the repo?

### ISSUE THREAD

**Issue by lucasfrosty** [howtographql/howtographql#523]
It looks like the website is not automatically getting the updates from the Markdown files on the tutorials.

For instance, the [Gettings Started with GraphQL, React & Apollo Tutorial](https://www.howtographql.com/react-apollo/1-getting-started/) is not synchronized with the actual [Markdown file](https://github.com/howtographql/howtographql/blob/master/content/frontend/react-apollo/1-getting-started.md) here on Github. And that's leading to some problems such as #519, which the cause was fixed on the repo but not on the website (see that on the repo, the ``yarn install`` command happens before the ``yarn prisma deploy``, but on the website it's happening after).

You're doing the "deploy" of the website by hand? Isn't there any way to update automatically the website based on the Markdown files?

Besides that, the project looks great. Thanks!

**Comment by nikolasburk** [comment]
Hey @lucasfrosty, thanks for opening this issue! The build was indeed broken but is now fixed again 🙌 Let us know if you're running into any further issues.
