### ISSUE TITLE
Add howtographql.com to Gatsby showcase?

### ISSUE THREAD

**Issue by m-allanson** [howtographql/howtographql#530]
Hi! @moonmeister [pointed out](https://github.com/gatsbyjs/gatsby/issues/4175#issuecomment-369838932) that howtographql.com is built with Gatsby.

_How to GraphQL_ is a great resource (it's [linked from the Gatsby docs](https://www.gatsbyjs.org/docs/querying-with-graphql/#how-to-learn-graphql)), would you be happy for it to be added to the [Gatsby showcase](https://github.com/gatsbyjs/gatsby#showcase)? Which is basically adding a link to this repo from the main Gatsby README.md.

If yes, I can create the PR. If not, then no problem, just close this issue :)

**Comment by nikolasburk** [comment]
Hi @m-allanson, thanks a lot for opening this issue and apologies for the delay. Not sure if someone was faster than you, but it seems it has already been added to the Gatsby showcases 😄 

![image](https://user-images.githubusercontent.com/4058327/37957465-468db048-31ae-11e8-8cf6-cfc883a866a3.png)

Thanks again 🙏

**Comment by m-allanson** [comment]
So it has, great!
