### ISSUE TITLE
Sangria tutorial compilation errors

### ISSUE THREAD

**Issue by khlumzeemee** [howtographql/howtographql#548]
Hi @marioosh ,
although it is not officially published yet, I started reviewing the Scala Sangria tutorial (see PR #546 for details about minor typos here and there).

On top of that, there are two problems towards the end of the `2-preparing-first-query.md` file:
- executeGraphQLQuery returns a Future but `complete` expects a `ToResponseMarshallable`
- in the DAO, the following line doesn't compile: `db.run(Links.result)`. `Links` is not defined

So I couldn't proceed to the Graphiql part yet as the code doesn't compile.

**Comment by marioosh** [comment]
Actually I wrote a code along with blog post, and status for that chapter is here :https://github.com/howtographql/sangria/tree/2-first-query
but in the evening I will check and confirm.. maybe I've missed something..

**Comment by khlumzeemee** [comment]
Thanks for the link!
I have fixed the Links not defined error in my code (I had to add the import manually).
However the executeGraphQLQuery still returns a weird datatype
`Future[(StatusCode with Product with Serializable, Any)]` instead of the expected `Future[(StatusCode with Product with Serializable, JsValue)]`.

I'll check on my side too, maybe make my repo available so you can check if you have some free time

**Comment by khlumzeemee** [comment]
This was the compiler error `Type spray.json.JsObject cannot be used as a GraphQL input.`
And this was the solution:
`import akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport._`.

It was already in the code sample you provided but since I rewrote it line by line the import wasn't included.

**Comment by Spyridox** [comment]
This issue should still be open, compilation after following all steps _still_ gives this error: `not found: value Links`

The problem is that the initial setup doesn't have this import in `DAO.scala`:
`import com.howtographql.scala.sangria.DBSchema._`

**Comment by khlumzeemee** [comment]
@spyridox you may be right, I'll check if I haven't already fixed it in one of the pull requests awaiting review. Otherwise you could create a PR too, it's a one liner as far as I understand.

**Comment by Spyridox** [comment]
I think the missing import is in the initial `giter8` setup [here](https://github.com/marioosh/howtographql-scala-sangria.g8/blob/master/src/main/g8/src/main/scala/com/howtographql/scala/sangria/DAO.scala), since it could be there from the beginning.
The `.g8` initial setup repository has no PRs. Should I open a PR there? @marioosh ?
Or perhaps this import should be indicated as a step in the tutorial?
