### ISSUE TITLE
Instruction to install yarn needed

### ISSUE THREAD

**Issue by MisinformedDNA** [howtographql/howtographql#563]
The documentation [here](https://github.com/howtographql/howtographql/blob/master/content/frontend/react-apollo/1-getting-started.md) tells users to run yarn, but it does not instruct users to *install* yarn.

**Comment by nikolasburk** [comment]
Thanks a lot for pointing that out, [I just added a note](https://github.com/howtographql/howtographql/commit/b74fb900c24757a44b1af4f5159ecb8d7de000cf) that points the reader to the installation instructions 🙌
