### ISSUE TITLE
Incorrect answer in react-apollo Getting Started "Unlock the Next Chapter" question?

### ISSUE THREAD

**Issue by tstewart15** [howtographql/howtographql#568]
![image](https://user-images.githubusercontent.com/8942170/38176167-061c6c8a-35b8-11e8-8430-de3cd6d314fb.png)

**Comment by nikolasburk** [comment]
Thanks so much for pointing that out @tstewart15, I just [fixed](https://github.com/howtographql/howtographql/commit/aa39f00e9d502f28d4ac0bb1b335eb28d47497ac) the issue 🙌
