### ISSUE TITLE
Bug in "two GraphQL API layers is a GraphQL spec requirement"

### ISSUE THREAD

**Issue by yihangho** [howtographql/howtographql#573]
Under [Getting Started][getting-started] in the React + Apollo track, the following question is posted:

> Why are there two GraphQL API layers in a backend architecture with Prisma?

The correct answer given was

> Having two GraphQL layers is a hard requirement by the GraphQL specification.

This doesn't sound right and people over at the forum seem to agree. (Ref: [forum post][forum-post])

I'd be happy to send in a PR to fix this if I can verify that the correct answer should be

> Prisma provides the database layer which offers CRUD operations. The second layer is the application layer for business logic and common workflows (like authentication).

[getting-started]: https://www.howtographql.com/react-apollo/1-getting-started/
[forum-post]: https://www.graph.cool/forum/t/two-graphql-api-layers-is-a-graphql-spec-requirement/3045

**Comment by nikolasburk** [comment]
Thanks a lot for catching that @yihangho, you're absoulely right! The second layer is for business logic and common workflows like authentication. [I just fixed it](https://github.com/howtographql/howtographql/commit/aa39f00e9d502f28d4ac0bb1b335eb28d47497ac) 🙌
