### ISSUE TITLE
Unclear how interface: IdentifiableType is defined in Scala/sangria

### ISSUE THREAD

**Issue by evbo** [howtographql/howtographql#583]
`IdentifiableType` is referenced but never defined. Isn't the definition necessary and how should it be defined?:

https://github.com/howtographql/howtographql/blob/09a01d319b8449f739f4a24a6141c7298878e700/content/backend/graphql-scala/6-interfaces.md#finding-a-common-parts

**Comment by marioosh** [comment]
```
val IdentifiableType = InterfaceType(
    "Identifiable",
    fields[Unit, Identifiable](
      Field("id", IntType, resolve = _.value.id)
    )
  )

```
It was accidentally removed form the article. I'll fix it soon
