### ISSUE TITLE
Problem with datamodel schema in gql with node  - 6 implementing auth

### ISSUE THREAD

**Issue by hereisnaman** [howtographql/howtographql#588]
I have been learning graphql with node js from the website. In part 6 https://www.howtographql.com/graphql-js/6-authentication/ we implement postedBy: User field in the datamodel, well that User type exposes the password field inside the User. 
![screen shot 2018-04-06 at 10 47 50 am](https://user-images.githubusercontent.com/22571395/38404480-0015ef18-3988-11e8-81a0-d7ea90c2a521.png)

Though due to a separate type def of User in api schema, I can't directly fetch user password 
![screen shot 2018-04-06 at 10 48 33 am](https://user-images.githubusercontent.com/22571395/38404491-12cdd1f2-3988-11e8-8565-729909ebe556.png)

but i can put a filter over postedBy field for the password as exposed by the generated prisma schema.
![screen shot 2018-04-06 at 10 49 06 am](https://user-images.githubusercontent.com/22571395/38404499-28958ac0-3988-11e8-8fec-91ff1afd86fe.png)

**Comment by swcarlosrj** [comment]
Thanks @hereisnaman for opening this issue 😄It should be fixed. Closing this!
