### ISSUE TITLE
Incorrect Answer for Quiz question

### ISSUE THREAD

**Issue by satyam22** [howtographql/howtographql#589]
For Quiz question **What is the second argument that's passed into GraphQL resolvers used for?** specified answer is **it is an object that all resolvers can write to and read from**.
it seems an incorrect answer as per my knowledge.
I think correct answer is **It carries the arguments for the incoming GraphQL operation**

Please let me know if i'm wrong.

Thanks

**Comment by nikolasburk** [comment]
Thanks a lot for catching this @satyam22! You're absolutely right, this was incorrect, [I just fixed the issue](https://github.com/howtographql/howtographql/commit/e062d0c3e25c8cc19667655eac9aadf116aa9030). Thanks a again 🙏
