### ISSUE TITLE
docs(1-getting-started): 3 small typos

### ISSUE THREAD

**Issue by MarcBouchard** [howtographql/howtographql#603]
Thank you for the great documentation so far! Everything is well structured and easy to follow.

While going through "1-getting-started", I noticed the 3 small typos listed below and created PR #604 to resolve them:

1. **line 6:** the quiz answer "Root fields define the available AP operations" is missing the "I" 
2. **line 178:** the word "always" is missing an "s"
3. **line 257:** the word "the" is repeated twice

**Comment by nikolasburk** [comment]
Thanks a lot for catching these and submitting the PR 🙌
