### ISSUE TITLE
docs(8-filtering-pagination-and-sorting): fix 6 typos

### ISSUE THREAD

**Issue by MarcBouchard** [howtographql/howtographql#611]
PR #610 resolves the following issues:

line 10: “implemented” => “implement"
line 54: “not” => “no”
line 56: “conidtions” => “conditions”
line 94: “provid” => “provide”
line 184: “elemenets” => “elements”
line 372: “You can test now” => “You can now test"

**Comment by swcarlosrj** [comment]
Thanks @MarcBouchard for opening this issue 😄It should be fixed. Closing this!
