### ISSUE TITLE
OrderBy not ordering feed content

### ISSUE THREAD

**Issue by nhuesmann** [howtographql/howtographql#619]
`orderBy` is not functioning as expected when using the `feed` query. I followed along with the [graphql-js](https://github.com/howtographql/graphql-js) tutorial and deployed my final server. I was able to perform all mutations and queries successfully. `skip`, `first`, and `filter` also return the expected result. `orderBy` however does not appear to be working, as the results order is not changed, no matter which `LinkOrderByInput` enum is chosen. I even cloned the `graphql-js` repo and deployed it - the issue persisted.

Example query 1:
```javascript
query {
  feed(orderBy: description_ASC) {
    count
    links {
      id
      url
      description
      postedBy {
        id
        name
        email
      }
    }
  }
}
```

Response:
```javascript
{
  "data": {
    "feed": {
      "count": 2,
      "links": [
        {
          "id": "cjg3w02lh5rkl0b9359gk7fc3",
          "url": "www.example.com",
          "description": "fake website",
          "createdAt": "2018-04-17T16:33:05.000Z",
          "postedBy": {
            "id": "cjg3vx2855q380b93yvwv1dqw",
            "name": "Nathan",
            "email": "nathan@example.com"
          }
        },
        {
          "id": "cjg3w0ek45rq10b933th57vrn",
          "url": "www.anotherexample.com",
          "description": "another fake website",
          "createdAt": "2018-04-17T16:33:20.000Z",
          "postedBy": {
            "id": "cjg3vx2855q380b93yvwv1dqw",
            "name": "Nathan",
            "email": "nathan@example.com"
          }
        }
      ]
    }
  }
}
```

Example query 2:
```javascript
query {
  feed(orderBy: description_DESC) {
    count
    links {
      id
      url
      description
      postedBy {
        id
        name
        email
      }
    }
  }
}
```

Response:
```javascript
{
  "data": {
    "feed": {
      "count": 2,
      "links": [
        {
          "id": "cjg3w02lh5rkl0b9359gk7fc3",
          "url": "www.example.com",
          "description": "fake website",
          "createdAt": "2018-04-17T16:33:05.000Z",
          "postedBy": {
            "id": "cjg3vx2855q380b93yvwv1dqw",
            "name": "Nathan",
            "email": "nathan@example.com"
          }
        },
        {
          "id": "cjg3w0ek45rq10b933th57vrn",
          "url": "www.anotherexample.com",
          "description": "another fake website",
          "createdAt": "2018-04-17T16:33:20.000Z",
          "postedBy": {
            "id": "cjg3vx2855q380b93yvwv1dqw",
            "name": "Nathan",
            "email": "nathan@example.com"
          }
        }
      ]
    }
  }
}
```

No matter what sort enum I choose, the links are returned ordered by creation date.

Also related to this issue, the repo is missing the `createdAt` field in the `Link` type. The tutorial has the reader remove `createdAt` from the Link type at one point (in the first example in the authentication section it is missing from Link), then in the subscriptions section the reader is instructed to add it back along with the `votes` field (I think the initial omission in the authentication section is an error). The final product has Link type containing the `createdAt` field, and the filtering, paginating, and sorting section demonstrated sorting on the `createdAt` field.

Please let me know if you need any further clarification on this issue.

**Comment by elliotaplant** [comment]
On the server in the current version of the tutorial repo, the `orderBy` parameter is not being used by the `Query` resolver for `feed` and is also not being used by the `Feed` resolver for `links`. To use the `orderBy` parameter you'll need to change both files:


```javascript
// server/src/resolvers/Query.js

async function feed(parent, args, ctx, info) {
  const { filter, first, skip, orderBy } = args // destructure input arguments

  const where = filter
    ? { OR: [{ url_contains: filter }, { description_contains: filter }] }
    : {}

  const allLinks = await ctx.db.query.links({})
  const count = allLinks.length

  const queriedLinks = await ctx.db.query.links({ first, skip, where })

  return {
    linkIds: queriedLinks.map(link => link.id),
    count,
    orderBy: orderBy || 'createdAt_DESC'
  }
}

module.exports = {
  feed,
}
```


```javascript
// server/src/resolvers/Feed.js

function links(parent, args, context, info) {
  const { linkIds, orderBy } = parent

  const where = { id_in: linkIds };
  return context.db.query.links({ where, orderBy }, info)
}

module.exports = {
  links,
}
```

Note that the only lines that changed are lines that contain the word `orderBy`. The reason this works and the original doesn't is because each call to `context.db.query.links()` will only sort the links if the `orderBy` key is present in the first parameter.

**Comment by mponizil** [comment]
Thank you for the solution @elliotaplant - though is this really the recommended way to handle pagination + sorting? I generally wonder if the ideal solution would be to somehow determine the `links` selection set from the `feed` `info` object and not use a child `links` resolver at all, though that gets into things beyond my understanding.

Another option I've settled on for now is to just manually restore the order as specified by `linkIds`, though I'm not sure if that's much better.

**Comment by swcarlosrj** [comment]
Thanks @nhuesmann for opening this issue 😄. it should be fixed. Closing this!
