### ISSUE TITLE
Modal gets stuck on page.

### ISSUE THREAD

**Issue by JacobMGEvans** [howtographql/howtographql#621]
When I enter the page at times the modal becomes unable to remove, or close. I have to inspect then find the modal in gatsby framework to delete the element. Wasn't sure if this is an issue that has been mentioned before, or if I am missing something. 

I was wondering if the modal is really necessary even?

**Comment by swcarlosrj** [comment]
Thanks @JacobMGEvans for opening this issue 😄Closing this due to innactivity!

**Comment by JacobMGEvans** [comment]
I think the last time I went to that same landing page the bug was no longer there. So it must have gotten fixed or something in a previous PR. 

Glad I could help in some small way, I love GraphQL and appreciate all of everyone's hard work 😄
