### ISSUE TITLE
backend/graphql-js/6-authentication

### ISSUE THREAD

**Issue by ahmetcetin** [howtographql/howtographql#634]
Why login is mutation? It just doesn't mutate data, shouldn't it be Query instead?

**Comment by guledali** [comment]
```
async function login(parent, args, context, info) {
  // 1
  const user = await context.db.query.user({ where: { email: args.email } }, ` { id password } `)
  if (!user) {
    throw new Error('No such user found')
  }

  // 2
  const valid = await bcrypt.compare(args.password, user.password)
  if (!valid) {
    throw new Error('Invalid password')
  }

  const token = jwt.sign({ userId: user.id }, APP_SECRET)

  // 3
  return {
    token,
    user,
  }
}
```


I think it's a query because you're using `context.db.query.user()`

**Comment by broberson** [comment]
As written, yes, it's essentially a query. Normally, though, logging into a system generates a new session, maybe updates the account with a new last-login date, maybe records the IP address being used, and whatever other side-effects are appropriate. So in most real-world scenarios, logging in would clearly be a mutation. Making it a mutation here is consistent with that, even if it's a bit unnecessary.

**Comment by swcarlosrj** [comment]
Thanks @ahmetcetin for opening this issue 😄. it should be fixed. Closing this!
