### ISSUE TITLE
React-Apollo having problem deploying backend server on localhost

### ISSUE THREAD

**Issue by jmdelgadoh** [howtographql/howtographql#635]
i have followed the steps in the react-apollo tutorial. I've installed my create-react-app and pulled from git the server directory.

I installed yarn since prisma deploy was giving me issues with the undefined cluster when using NPM to deploy yarn. Anyhow, I installed yarn and finally after installing the node_modules i did
`yarn prisma deploy` 
as the instructions indicate. I was prompted for a cluster host and I chose US.

Next step was to explore the db, using `yarn dev`
running this command gave me syntax erros:

juandelgado$ yarn dev
yarn run v1.6.0
warning package.json: No license field
$ npm-run-all --parallel start playground
warning package.json: No license field
warning package.json: No license field
$ node src/index.js
$ graphql playground
/Users/juandelgado/Sites/sandbox/react-apollo-graphql/server/src/index.js:19
    ...req,
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with signal "SIGTERM".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "start" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
juandelgado$ 

i've tried it from scratch a few times and i still get this issue...

**Comment by swcarlosrj** [comment]
Thanks @jmdelgadoh for opening this issue 😄. it should be fixed. Closing this!
