### ISSUE TITLE
Update relay subscriptions example to latest subscriptions-transport-ws

### ISSUE THREAD

**Issue by virtualirfan** [howtographql/howtographql#636]
This [post](https://github.com/facebook/relay/issues/1655#issuecomment-349957415) provides precise recipe for how to use the latest `subscriptions-transport-ws` version.

I'm a scala.js programmer otherwise I'd submit a PR myself. I know an earlier issue on this topic was closed but now that there is a specific example for how to use the latest `subscriptions-transport-ws`, I'm hoping that this issue can be kept open in case someone has a few minutes to update the tutorial example.

**Comment by swcarlosrj** [comment]
Thanks @virtualirfan for opening this issue 😄. Closing this due to innactivity!
