### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by MichaelArnoldOwens** [howtographql/howtographql#65]
Navigating in chrome browser to https://www.howtographql.com/?v1 gives NET::ERR_CERT_AUTHORITY_INVALID

**Comment by timsuchanek** [comment]
Thanks for reporting @MichaelArnoldOwens. Unfortunately, I can't reproduce the problem currently.
Can you please post the result of `dig howtographql.com`? Thanks!

**Comment by nikolasburk** [comment]
I'm closing this issue since it's starting to age... @MichaelArnoldOwens feel free to comment or reopen if the problem still persists and we can look into it again 🙂
