### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by TeodorKolev** [howtographql/howtographql#652]
I got error:
`SyntaxError: Unexpected token ...`

adding this code:
```
  context: req => ({
    ...req,
    db: new Prisma({
      typeDefs: 'src/generated/prisma.graphql',
      endpoint: 'https://eu1.prisma.sh/public-graytracker-771/hackernews-node/dev',
      secret: 'mysecret123',
      debug: true,
    }),
  }),
```
from this tutorial:
https://www.howtographql.com/graphql-js/5-connecting-server-and-database/

How to fix that?

**Comment by davty** [comment]
You are most probably running an old version of nodejs. Make sure you have at least version 5.12.

**Comment by myhendry** [comment]
I have a similar error with regard to the spread operator

I'm presently running node v8.2.1

**Comment by Sudip7** [comment]
I too faced similar/same problem. Node version : v6.10.2. 
Please assist. And @myhendry , what do you mean by Typescript boilerplate. Don't have much idea on this.

**Comment by jonocodes** [comment]
same. using Node 6.14.2 via NVM

**Comment by geirman** [comment]
To solve this problem, upgrade node to a version that supports object spread. v8.2.1 supports it with the `-harmony` flag.

**Comment by luckyvs1** [comment]
As mentioned above upgrading the node version resolved this issue: https://stackoverflow.com/questions/10075990/upgrading-node-js-to-latest-version

Essentially run the following in the CLI to upgrade to the latest stable version of Node:
`sudo npm install n -g`
`sudo n stable`

**Comment by Gary-Shurgin** [comment]
I am having the same problem with prisma deploy.
I have updated node to v8.10.0
I have updated npm to 6.4.1
I am running on Windows 10

**Comment by swcarlosrj** [comment]
Thanks @TeodorKolev for opening this issue 😄. It seems to be solved following the latest tutorial docs. Closing this for now, please, feel free to open an issue if you cannot make it work!
