### ISSUE TITLE
Schema Definition Language link is broken

### ISSUE THREAD

**Issue by Thiago-Caramelo** [howtographql/howtographql#655]
Hi,

I'm at howtographql/content/graphql/basics/2-core-concepts.md. I'm afraid the link to [Schema Definition Language](https://graph-cool.netlify.com/docs/faq/graphql-sdl-schema-definition-language-kr84dktnp0/) is broken right ?

**Comment by swcarlosrj** [comment]
Thanks @Thiago-Caramelo for opening this issue 😄. it should be fixed. Closing this!
