### ISSUE TITLE
React Apollo ch6: cache doesn't work as expected

### ISSUE THREAD

**Issue by marcus-nl** [howtographql/howtographql#656]
In https://www.howtographql.com/react-apollo/6-more-mutations-and-updating-the-store/ section "While we’re at it, let’s also implement update for adding new links!" the update function is defined as follows:
```js
update: (store, { data: { post } }) => {
  const data = store.readQuery({ query: FEED_QUERY })
  data.feed.links.splice(0, 0, post)
  store.writeQuery({
    query: FEED_QUERY,
    data,
  })
},
```
This seems to work, because after adding a new link it immediately appears in the list. However, I noticed that it doesn't appear in the expected position: the call to `splice` adds it to the **first** position, but it ends up in the **last** position. To confirm you can change the line to `data.feed.links.splice(3, 0, post)` and the behavior will be the same. If you remove the call to `writeQuery` the list is no longer updated after adding a new link. In the server log I can see that the feed query is executed again. So in the end it seems that the call causes the data to be refreshed from the server (in effect invalidating the cache?), whereas I expected the updated cache to be used for displaying the feed.

**Comment by marcus-nl** [comment]
I found the likely cause and solution. After disabling the line `this.props.history.push('/')` I got the following error messages:
```
writeToStore.js:137 Missing field postedBy in {
  "id": "cjhbp7huw6zr50b619eqaeqp4",
  "createdAt": "2018-05-18T08:24:46.000Z",
  "url": "26",
  "
[...]
writeToStore.js:137 Missing field votes in {
  "id": "cjhbp7huw6zr50b619eqaeqp4",
  "createdAt": "2018-05-18T08:24:46.000Z",
  "url": "26",
  "
[...]
```
This can be resolved by adding the missing fields in the mutation:
```gql
  mutation PostMutation($description: String!, $url: String!) {
    post(description: $description, url: $url) {
      id
      createdAt
      url
      description
      postedBy { id, name }      // <--
      votes { id, user { id } }  // <--
    }
  }
```
I also replaced the call to `splice` to append instead of prepend the new item to the list. 
```js
data.feed.links.push(post)
```

**Comment by swcarlosrj** [comment]
@marcus-nl thanks, would you mind open a PR with the proposed solution & pls, reference it here? I'd really appreciate it 😄

**Comment by swcarlosrj** [comment]
Thanks @marcus-nl for opening this issue 😄. it should be fixed. Closing this!

**Comment by marcus-nl** [comment]
Hi @swcarlosrj, I hadn't had much time yet to look at making a PR. Thanks :)
