### ISSUE TITLE
SubscribeToMore issue in grapghql and reat js

### ISSUE THREAD

**Issue by alaamahersalem** [howtographql/howtographql#660]
Hey guys can any one help me in find the issue why i can't find subscribeTOMore in this.props.data
Please help

**Comment by swcarlosrj** [comment]
@alaamahersalem were you able to solve it? If that's the case close the issue pls, else let us know 😄

**Comment by swcarlosrj** [comment]
Thanks @alaamahersalem for opening this issue 😄. it should be fixed. Closing this!
