### ISSUE TITLE
Node js - Authentication - Field "email" is not defined by type UserWhereUniqueInput.

### ISSUE THREAD

**Issue by christiaan-janssen** [howtographql/howtographql#661]
I'm following the tutorial and its great, but I'm having an issue. I can create a User and a Link but when I run the query:
```graphql
mutation {
  login(
    email: "alice@graph.cool"
    password: "graphql"
  ) {
    token
    user {
      email
      links {
        url
        description
      }
    }
  }
}
```
I get the following error:
`Error: Variable "$_v0_where" got invalid value {"email":"alice@graph.cool"}; Field "email" is not defined by type UserWhereUniqueInput.`

I have restarted the tutorial thinking it was an error earlier on, copy pasted the code to not make a typo but I keep getting the error.

**Comment by chapran-leobit-acc** [comment]
I had the same issue while completing the tutorial. In your `datamodel.graphql` file, make sure the User's `email` field has the `@unique` directive set. That was exactly the problem in my case. And don't forget to redeploy your Prisma service after making changes to your data model.

**Comment by xwlee** [comment]
I bump into similar issue.
@chapran-leobit-acc Do you know why the email must be unique?

**Comment by swcarlosrj** [comment]
Thanks @christiaan-janssen  for opening this issue 😄. It seems to be solved. Closing this for now, please, feel free to re-open an issue if you cannot make it work!

**Comment by Unsung-crusader** [comment]
I ran into the same issue. The solution given by @chapran-leobit-acc fixed it for me.

**Comment by KumarAbhirup** [comment]
I have the same issue.

**Comment by shawnkoh** [comment]
Same issue. I checked my datamodel.prisma file and it has the @unique directive. Still does not work

**Comment by IamGiel** [comment]
re-open ?

**Comment by TasinIshmam** [comment]
@IamGiel could you please clarify the issue/error you're facing?
