### ISSUE TITLE
mutation does not work due to authentication in 3-mutations-creating-links

### ISSUE THREAD

**Issue by jseminck** [howtographql/howtographql#677]
Hello!

Not sure if this is a bug... but first I did the server/backend code with the Node tutorial. In this project, we add authentication to the post mutation.

The steps in the FE tutorial setup the post mutation in a form. But the authentication is not yet implemented. As a result, I get the error `Uncaught (in promise) Error: GraphQL error: Not authenticated` instead of creating a new link.

https://www.howtographql.com/react-apollo/3-mutations-creating-links/

**Comment by craigblunden** [comment]
I had the same issue, I just moved forward to up until the Auth section to make sure it all worked accordingly but I agree its a bit jarring without that context.

**Comment by jh0l** [comment]
Yeah, one caveat of reusing the node tutorial code I guess. My workaround was commenting out the getUserId line in the post resolver and setting the postedBy field of the database api request to null,
like this
`async function post(parent, args, ctx, info) {
  //const userId = getUserId(ctx);
  return await ctx.db.mutation.createLink(
    {
      data: {
        url: args.url,
        description: args.description,
        postedBy: null//{ connect: { id: userId } }
      }
    },
    info
  );
}`
Which worked fine for me, this is basically the reverse of what is done in the authentication section further in the react-apollo tutorial too so pretty easy to undo.

**Comment by swcarlosrj** [comment]
Thanks @jseminck for opening this issue 😄. it should be fixed. Closing this!
