### ISSUE TITLE
Access to document

### ISSUE THREAD

**Issue by cottonsean** [howtographql/howtographql#678]
I wanted to fix some typos in tutorial, but ran into issue cloning repo.  Any ideas on how I can fix?  I tried to attach screenshot, but no luck.  This is what I get in terminal:  MacBook-Pro:~ seancotton$ git clone git@github.com:howtographql/howtographql.git
Cloning into 'howtographql'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by seanbermejo** [comment]
I think you must add your public key to github SSH Keys settings. https://github.com/settings/keys

It might also be best to fork the parent repository and create a pull request for your changes. Thanks!

**Comment by swcarlosrj** [comment]
Closing this as It looks like fixed 😄
