### ISSUE TITLE
React + Apollo: Loading Links [2]

### ISSUE THREAD

**Issue by soflete** [howtographql/howtographql#68]
The last line of the Queries: Loading Links chapter of the React + Apollo tutorial reads:

> That’s it! Go ahead and run yarn start again. You should see the exact same screen as before.

But as no mutations have been executed as part of the chapter, the content of the response to the query  is an empty list of links: `{"data":{"allLinks":[]}}`, so the 2 links provided as mock data are no longer displayed.

**Comment by abhiaiyer91** [comment]
Ah I think we were supposed to insert the command to generate some data via graphcool cli. The same 2 items that were in mock. @nikolasburk did we get around to that?

**Comment by nikolasburk** [comment]
@abhiaiyer91 how much effort would it be for you to edit the video and add a short sequence where you execute the two mutations in a playground? we could think about deleting the current video and uploading the edited version. replacing the video wouldn't be ideal though as the clicks are reset to 0 then as well. an alternative solution might be to add a note about the issue in the video description. @soflete do you think this would help already?

**Comment by abhiaiyer91** [comment]
I can do that! Whatever you want boss!

**Comment by soflete** [comment]
I think adding some written clarification would help, as long as it is clear for the viewer/reader that the list is empty because there is no data and not because s/he did something wrong. Replacing the video might be an overkill.

**Comment by nikolasburk** [comment]
Done, I added a note to the description of the video. Thanks again for pointing that out 🙌
