### ISSUE TITLE
Node.js Add chapter on how to deploy

### ISSUE THREAD

**Issue by guledali** [howtographql/howtographql#684]
Please add a chapter on how to deploy either to zeit now or heroku it would complete the guide on how to make a graphql server. 

Deployment is huge part of API considering graphql is API operating over HTTP, it would be helpful going through different deployment. One thing I noticed is that prisma comes with docker file I would love to learn how it works and how deploy with it.

**Comment by nikolasburk** [comment]
Hey @guledali, thanks a lot for the input, we'll definitely add that soon! In the meantime, you can check out these deployment tutorials for GraphQL servers for [Zeit Now](https://www.prisma.io/docs/tutorials/build-graphql-servers/deployment/deployment-with-now-ahs1jahkee/) and [Apex Up](https://www.prisma.io/docs/tutorials/build-graphql-servers/deployment/deployment-with-up-shieghae3d/) (AWS Lambda).

**Comment by guledali** [comment]
That's the server component but the database itself(PostgreSQL or MySQL) where do you host that part.

**Comment by guledali** [comment]
@nikolasburk That's the server component but the database itself(PostgreSQL or MySQL) where do you host that part.

**Comment by guledali** [comment]
Why not just add this https://www.prisma.io/blog/heroku-integration-homihof6eifi/

It showcase everything where to deploy the server and the database aswell.

**Comment by guledali** [comment]
@nikolasburk Why not just add this https://www.prisma.io/blog/heroku-integration-homihof6eifi/

It showcase everything where to deploy the server and the database as well.
