### ISSUE TITLE
Basics Tutorial - Introduction Blog Link

### ISSUE THREAD

**Issue by dnlowman** [howtographql/howtographql#685]
On the [Basics Tutorial Introduction page](https://www.howtographql.com/basics/0-introduction/), there is a link to a blog post where you can learn more about the top reasons to use graphql, it seems to not exist anymore:
https://blog.graph.cool/b60cfa683511

**Comment by nikolasburk** [comment]
Hey @dnlowman, thanks a lot for pointing that out! I just fixed the issue, this is the link to the blog post: https://www.prisma.io/blog/top-5-reasons-to-use-graphql-b60cfa683511/
