### ISSUE TITLE
Typo in advanced more graphql concepts

### ISSUE THREAD

**Issue by AndreiCalazans** [howtographql/howtographql#69]
_This brings up a different problem: In a GraphQL **query where we ask want to retrieve information** about a Child but only have a Person type to work with, how do we know whether we can actually access this field?_

I think maybe the correct would be:
_This brings up a different problem: In a GraphQL **query where we ask to retrieve information** about a Child but only have a Person type to work with, how do we know whether we can actually access this field?_

**Comment by nikolasburk** [comment]
thanks again for the PR! :)
