### ISSUE TITLE
Abrupt transition in the Node.js backend Getting Started section

### ISSUE THREAD

**Issue by dandv** [howtographql/howtographql#706]
The problem is tt https://www.howtographql.com/graphql-js/1-getting-started/ -> "A word on the GraphQL schema".

> In the info example from before, the type of the root field was a String, which is a scalar type.

The next paragraph mentions `src/schema.graphql`, something the user will only create in step 3, *A Simple Mutation*.

Another bullet that seems out of place at this point is `context`.

Finally, the paragraph before last seems to refer to a later chapter (perhaps "Adding a Database"?):

> As you provide this information, the `Prisma` instance will get full access to your database service

**Comment by swcarlosrj** [comment]
Thanks @dandv for opening this issue 😄. it should be fixed. Closing this!
