### ISSUE TITLE
Your token is invalid error from application layer side (graphql-js tutorial)

### ISSUE THREAD

**Issue by aecorredor** [howtographql/howtographql#711]
I'm following along the graphql-js tutorial for the server side and I'm running into an issue after finishing chapter 5. I'm trying to send a query from the application layer to the prisma layer but I get the `your token is invalid` error. I don't get it when I query directly from the prisma layer.

I'm doing this from the playground, running both projects at the same time.

application layer (where error happens):
<img width="1440" alt="screen shot 2018-07-10 at 11 34 53 pm" src="https://user-images.githubusercontent.com/9114987/42549473-5dc452b4-849a-11e8-97c2-494ad4832ef3.png">

prisma layer (resolves successfully):
<img width="1440" alt="screen shot 2018-07-10 at 11 35 16 pm" src="https://user-images.githubusercontent.com/9114987/42549483-6652c078-849a-11e8-93c7-8dbb8360634e.png">

In the tutorial it says that everything is supposed to work at this point, and that the application layer should be able to query the prisma layer.

**Comment by lquixada** [comment]
it seems the tutorial missed one piece of information, you have to add the secret to the Prisma binding, like this:

```js
const server = new GraphQLServer({
  typeDefs: './src/schema.graphql',
  resolvers,
  context: req => ({
    ...req,
    db: new Prisma({
      typeDefs: 'src/generated/prisma.graphql',
      endpoint: '<you database endpoint url>',
      secret: 'mysecret123', // <- right here
      debug: true,
    }),
  }),
})
```
