### ISSUE TITLE
Keep Getting a "Not Logged In Error" during Authentication - Graphene Django

### ISSUE THREAD

**Issue by mihirkelkar** [howtographql/howtographql#715]
Im trying to check if the user token is in a logged-in state using the insomnia desktop client. As described, Iv set my token with a JWT prefix as a part of the headers. However, when I query the me object, I always get a not logged in error. I have refreshed the token a number of times. I have a feeling that the token is actually not getting passed in the header. Can you help with this?
Here's a screen shot of my user query to check if Im logged in. 
[https://imgur.com/a/UUEHzeL](url)

and here's how I have the header set. 
[https://imgur.com/a/S7qAMP7](url)

**Comment by swcarlosrj** [comment]
Thanks @mihirkelkar for opening this issue 😄. Closing this due to innactivity!
