### ISSUE TITLE
Update docs) Add the secret!

### ISSUE THREAD

**Issue by guledali** [howtographql/howtographql#717]
Connecting Server and Database with Prisma Bindings
https://www.howtographql.com/graphql-js/5-connecting-server-and-database/

Currently it look like this 
![screenshot 72](https://user-images.githubusercontent.com/20647282/42716177-940a2f9e-86fa-11e8-81f1-45e003fb5965.png)

One thing its missing is the secret key
![inkedsecret](https://user-images.githubusercontent.com/20647282/42716252-e6714592-86fa-11e8-8163-1d1b64fededd.jpg)

**Comment by guledali** [comment]
There is PR referring to this issue #709

**Comment by marktani** [comment]
I merged the PR, thanks for your feedback!
