### ISSUE TITLE
Add Sections on How to Update and Delete Instances?

### ISSUE THREAD

**Issue by marcaaron** [howtographql/howtographql#720]
I may have missed the section where this is covered, but I'd like to suggest that someone briefly outline how these types of mutations might work for beginners to Ruby/Rails and the GraphQL gem.

e.g. I am having difficulty figuring out how exactly to create mutations that destroy or update model instances and have it return back the instance. Is it appropriate to make these types of mutations Resolvers? I attempted this... and while it does destroy the model instance graphiql gets back a JSON syntax error which interrupts things on the front end (Apollo will not update the change etc). 

```ruby
class Resolvers::DeleteLink < GraphQL::Function
  argument :id, !types.ID
  type Types::LinkType

  def call(obj, args, ctx)
    input = args[:id]
    Link.destroy([args[:id]])
  end
end

Types::MutationType = GraphQL::ObjectType.define do
  name "Mutation"
  field :deleteLink, function: Resolvers::DeleteLink.new
  field :createLink, function: Resolvers::CreateLink.new
  field :createVote, function: Resolvers::CreateVote.new
  field :createUser, function: Resolvers::CreateUser.new
  field :signinUser, function: Resolvers::SignInUser.new
end
```
Calling the Mutation from graphiql
```graphql
mutation delete{
  deleteLink(id:"15"){
    id
    url
    description
  }
}
```
Console Output
```bash
13:17:06 web.1    |   Link Load (0.2ms)  SELECT  "links".* FROM "links" WHERE "links"."id" = ? LIMIT ?  [["id", 25], ["LIMIT", 1]]
13:17:06 web.1    |   ↳ app/graphql/resolvers/delete_link.rb:7
13:17:06 web.1    |    (0.1ms)  begin transaction
13:17:06 web.1    |   ↳ app/graphql/resolvers/delete_link.rb:7
13:17:06 web.1    |   Link Destroy (0.4ms)  DELETE FROM "links" WHERE "links"."id" = ?  [["id", 25]]
13:17:06 web.1    |   ↳ app/graphql/resolvers/delete_link.rb:7
13:17:06 web.1    |    (5.8ms)  commit transaction
13:17:06 web.1    |   ↳ app/graphql/resolvers/delete_link.rb:7
13:17:06 web.1    | Completed 500 Internal Server Error in 22ms (ActiveRecord: 6.6ms)
13:17:06 web.1    |
13:17:06 web.1    |
13:17:06 web.1    |
13:17:06 web.1    | NoMethodError (undefined method `id' for #<Array:0x00007ff647314530>):
13:17:06 web.1    |
13:17:06 web.1    | app/controllers/graphql_controller.rb:11:in `execute'
```

Perhaps there is an obvious deficiency with this attempt. I am admittedly very new to Rails and Ruby syntax, but presumed that the destroy method returns the object that has been destroyed since running a `Link.destroy(<some id>)` in the Rails console will return the object.

**Comment by RStankov** [comment]
Hi, the working mutation would be something like:

```ruby
class Resolvers::DeleteLink < GraphQL::Function
  argument :id, !types.ID
  type Types::LinkType

  def call(obj, args, ctx)
    # TODO: check if `ctx[:current_user`] can actually destroy
    link = Link.find(args[:id) # can throw ActiveRecord::RecordNotFound
    link.destroy! # destroys the record, can throw
    link # returns the link so it can be queried.
  end
end
```

Couple of other gotchas:

- I have written about mutations in my own blog http://blog.rstankov.com/graphql-mutations-and-form-errors/
- it is better to name mutations `linkDelete` instead of `deleteLink`, in this case grouping is easier

**Comment by marcaaron** [comment]
Thanks for the reply! Tutorial helped immensely. Also great note about the naming convention :)
