### ISSUE TITLE
Typo in advanced/3-common-questions/

### ISSUE THREAD

**Issue by jessicaxp** [howtographql/howtographql#73]
"idendity" should be "identity"

<img width="809" alt="screenshot 2017-07-11 22 44 51" src="https://user-images.githubusercontent.com/10637381/28103438-9be80a10-668a-11e7-85c9-19519ece79dc.png">

**Comment by angly-cat** [comment]
This was fixed in #97.

**Comment by nikolasburk** [comment]
Thanks @angly-cat, will close the issue! 🙌
