### ISSUE TITLE
display issue on 8-filtering-pagination-and-sorting

### ISSUE THREAD

**Issue by maxime-pico** [howtographql/howtographql#733]
It's not a big deal (you'll kill this issue if not relevant), but in the section "Returning the total amount of Link elements" when you ask to adjust the feed resolver, the first line contains a new addition with the "async function" declaration instead of the previously more standard "function" declaration.

This new addition to the code is not highlighted in the snippet (see attached screenshot), which could lead to errors from readers.

![screen shot 2018-07-25 at 09 41 19](https://user-images.githubusercontent.com/4660085/43186626-8a009c92-8fef-11e8-8dce-d875cf8613dd.png)

I didn't see where I could edit that in the md version of the file, so I let you guys handle it.

Thanks for the awesome tutorial by the way, it's a real pleasure to learn about GrapQL thanks to your tutorials!

**Comment by swcarlosrj** [comment]
Thanks @maxime-pico for opening this issue 😄. it should be fixed. Closing this!
