### ISSUE TITLE
python tutorial errors with django-filter version

### ISSUE THREAD

**Issue by charlesverdad** [howtographql/howtographql#743]
There are a couple of breaking changes with the new `django-filter` library version `2.0.0`, causing errors in the part 9 (Relay) of the python tutorial. 

Quick solution was to downgrade to django-filter==1.1.0 https://github.com/graphql-python/graphene-django/issues/464

**Comment by jonatasbaldin** [comment]
Hello there, sorry for the delay :(

I think it was solved [here](https://github.com/graphql-python/graphene-django/pull/492).

Could you try again?

Cheers!

**Comment by udos** [comment]
I can confirm that upgrading to `django-filter==2.0.0` **and(!)** `graphene-django==2.2.0` fixes this
