### ISSUE TITLE
Type Feed should return number of filtered items in `count`? NodeJS-GraphQL chapter 8

### ISSUE THREAD

**Issue by aibolik** [howtographql/howtographql#764]
Hi,

Probably it was intended to do so, but at least my understanding of `Feed` type is that it should return filtered links as long as their `count`. Current implementation as long as explanation it returns total number of `Link` items.

Isn't it better to return number of filtered items? So for example if I have total of 5 link items, and 3 of them have "Github" in their descriptions, then I assume/expect that this query:
```graphql
query {
  feed(filter: "Github"){
    count
    links {
      id
      description
      url
    }
  }
}
```
should return something like this:
```json
{
  "data": {
    "feed": {
      "count": 3,
      "links": [
        ...
      ]
    }
  }
}
```
not 5 in `count` field. 

I think this is better API design in my opinion, but correct me if I am wrong.

If this will be accepted, probably changes to the content and to code itself would be needed. I am happy to help.

P.S: Also, would like to thank all of you - [howtographql](https://howtographql.com) is really great as a starting point to GraphQL.

**Comment by swcarlosrj** [comment]
Thanks @aibolik for opening this issue 😄. it should be fixed. Closing this!

**Comment by aibolik** [comment]
@swcarlosrj happy to help. I can open a PR to fix this.
