### ISSUE TITLE
Feedback on Node.js tutorial - getting started

### ISSUE THREAD

**Issue by MortenHofft** [howtographql/howtographql#765]
Thank you for writing these tutorials! There was a few things confusing me reading this.

**src/schema.graphql**
>...These are the type definitions from your application schema imported from `src/schema.graphql`...

https://github.com/howtographql/howtographql/blame/master/content/backend/graphql-js/1-getting-started.md#L222
In the context of building a small server, this in confusing. It is referencing a specific file in what I assume is another project? A common practice to have such a file perhaps? It isn't something that we have added in this tutorial at least.

**Prisma**
> ...As you provide this information, the `Prisma` instance will get full access to ...

https://github.com/howtographql/howtographql/blame/master/content/backend/graphql-js/1-getting-started.md#L265

The reference to `Prisma` seems out of context to me. It hasn't been introduced and is now referenced as if I should know it well.

**Comment by swcarlosrj** [comment]
Thanks @MortenHofft for opening this issue 😄. It's a great suggestion although as the tutorial it'll probably be updated soon, it'll remain as it's, thanks anyways for the proposal. Closing this for now!
