### ISSUE TITLE
Full Schema mutation age arg has wrong type

### ISSUE THREAD

**Issue by Charlotte990** [howtographql/howtographql#769]
Following along your video tutorial and I have spotted a bug in the 'Full Schema' slide (see screenshot below) on the Mutation, age should be of type Int! not type String!

![screen shot 2018-08-24 at 16 28 49](https://user-images.githubusercontent.com/14275796/44593476-574a2500-a7bb-11e8-9e4e-208ca307935e.png)

P.s. The videos have been really helpful - thank you!

**Comment by mannyluvstacos** [comment]
@Charlotte990 I was about to post the same thing!
I am going through the videos as well and noticed this too!

To the creators, thank you for these videos!

**Comment by swcarlosrj** [comment]
@Charlotte990 @mannyluvstacos thanks so much for the feedback provided. I guess it won't be possible to fix it rn because It'd take a lot of time to record the video again. Closing this issue 😄
