### ISSUE TITLE
maxdepth and complex queries example code

### ISSUE THREAD

**Issue by Enalmada** [howtographql/howtographql#775]
Before anyone goes into production they must consider minimum protection.  There is some talk about this in the tutorial but I think it would benefit from some concrete examples:

```
Executor.execute(
   ...
       queryReducers = List(
            QueryReducer.rejectMaxDepth[MyContext](15),
            QueryReducer.rejectComplexQueries[MyContext](4000, (_, _) ⇒ TooComplexQueryError)),
   ...
   )
   ...
    lazy val ErrorHandler = EHandler {
       case (_, error@TooComplexQueryError) ⇒ HandledException(error.getMessage)
       case (_, error@MaxQueryDepthReachedError(_)) ⇒ HandledException(error.getMessage)
       ...
     }
```
Adapted from https://github.com/sangria-graphql/sangria-playground/blob/master/app/controllers/Application.scala#L63-L65

Is there anything else easy and obvious everyone should be doing at a minumum?

**Comment by swcarlosrj** [comment]
@Enalmada thanks for the proposal, it'd be awesome. At the moment we're gonna try to fix all the issues & merge PRs, after that we'd discuss how we can improve the platform. I'd let you know in case that'd be possible to implement that 😃

**Comment by swcarlosrj** [comment]
Thanks @Enalmada for opening this issue 😄. Closing this due to innacitvity!
