### ISSUE TITLE
react-apollo/1-getting-started deploy instructions too brief

### ISSUE THREAD

**Issue by asciimo** [howtographql/howtographql#777]
I got blocked by two issues in the deployment instructions: 

1. `prisma deploy` commences an interactive dialog with a lot of questions I didn't know the answer to
1. "If you have Docker installed, you can also deploy locally" isn't exactly true. I set up a vanilla MySQL 
docker container and prisma couldn't connect to it, even though I was able to using the MySQL client.

I'm happy to submit a PR if I get past these issues, but thought I should create this issue in case I don't.

**Comment by asciimo** [comment]
I found the solution [here](https://www.prisma.io/docs/get-started/01-setting-up-prisma-demo-server-a001/#create-a-prisma-service-configuration).  Submitted PR #778.

**Comment by TorquatoNathan** [comment]
Personally, just one small problem: the instructions provided for deploying the Prisma server aren't enough.
Please, just add the instructions provided [here](https://www.howtographql.com/graphql-js/4-adding-a-database/) so one can easily go through this part of the tutorial.
The tutorial is great, though.
Keep up the good work and heppy coding!

**Comment by swcarlosrj** [comment]
It looks like already solved, closing it!
