### ISSUE TITLE
[Bug] Unable to mark the NodeJS track complete

### ISSUE THREAD

**Issue by shobhitchittora** [howtographql/howtographql#788]
The Summary page for the NodeJS track has no way to mark it complete ( as others have a quiz at the  end ). This renders it un-complete as in the screenshot below - 

<img width="432" alt="screen shot 2018-09-13 at 11 15 25 pm" src="https://user-images.githubusercontent.com/4711855/45505814-3b7ae300-b7ab-11e8-84d4-ba2e846df112.png">

Am I missing anything?

**Comment by swcarlosrj** [comment]
Thanks @shobhitchittora for opening this issue 😄. It should be fixed. Closing this!
