### ISSUE TITLE
Broken link in Common Questions

### ISSUE THREAD

**Issue by 9at8** [howtographql/howtographql#791]
Regarding [Common Questions - How to do Authentication and Authorization?](https://github.com/howtographql/howtographql/blob/master/content/graphql/advanced/5-common-questions.md)

>  you can take a look Graphcool’s permission queries.

The last link in this seems to be broken.

**Comment by davidatwhiletrue** [comment]
Found an alternative document that covers well this topic in graphcool reference docs:

https://www.graph.cool/docs/reference/auth/overview-ohs4aek0pe

Sending a PR to replace the broken link with this one.
