### ISSUE TITLE
Can't define schema in elixir 

### ISSUE THREAD

**Issue by VladimirTambovtsev** [howtographql/howtographql#795]
Following along the tutorial, when I get to the top of this page: <a href="https://www.howtographql.com/graphql-elixir/2-queries/">https://www.howtographql.com/graphql-elixir/2-queries/</a>,  the text says to modify the file <code>lib/community_web/schema.ex</code>,
 create new resolver in <code>lib/community_web/resolvers/news_resolver.ex.</code> 
and start GraphiQL in <code>lib/community_web/router.ex</code>

However, when I try to 
<pre>
iex -S mix phx.server
</pre>
I get the following error:
<pre>
== Compilation error in file lib/community_web/schema.ex ==
** (Absinthe.Schema.Notation.Error) Invalid schema notation: `field` must only be used within `input_object`, `interface`, `object`
    lib/absinthe/schema/notation.ex:1336: Absinthe.Schema.Notation.do_recordable!/4
    expanding macro: Absinthe.Schema.Notation.field/3
    lib/community_web/schema.ex:12: CommunityWeb.Schema (module)
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
</pre>

Perhaps there is some problem with <code>schema.ex</code> in type.

<br><br>
P.S The deps are the same as in instructions:
<pre>
      {:absinthe_ecto, "~> 0.1.0"},
      {:absinthe_plug, "~> 1.3.0"}
</pre>

**Comment by swcarlosrj** [comment]
Thanks @sessionboy for opening this issue 😄. Closing this due to innactivity!

**Comment by jaeyson** [comment]
here's what I did:

```elixir
  object :link do
    field :id, non_null(:id)
    field :url, non_null(:string)
    field :description, non_null(:string)
    field :all_links, non_null(list_of(non_null(:link))) do
      resolve &NewsResolver.all_links/3
    end
  end
```
next, change `{:cowboy, "~> 1.0"}` dependency with `{:plug_cowboy, "~> 1.0"}` in your project’s `mix.exs`

```elixir
  defp deps do
    [
      {:absinthe_plug, "~> 1.4"},
      {:absinthe_ecto, "~> 0.1.3"},
      {:phoenix, "~> 1.3.4"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, "~> 3.2"},
      {:postgrex, ">= 0.0.0"},
      {:gettext, "~> 0.11"},
      {:plug_cowboy, "~> 1.0"},
    ]
  end
```
next: `mix deps.get && iex -S mix phx.server`
