### ISSUE TITLE
django tutorial need to update - users module not found

### ISSUE THREAD

**Issue by Ajaxsoap** [howtographql/howtographql#800]
I think you need to update the django tutorial from manually adding ``users`` folder inside hackernews; the interpreter throws an error ``ModuleNotFoundError: No module named 'users'`` after I've run the server.

What I did was run django command ``py manage.py startapp users``, then add it on settings.py  ``INSTALLED_APPS = 'users'``

In this way, the issue has  been fixed and I can query and mutate the normal way.

So the correct path will be ``root_path/users/schema.py``. 

Thanks.

**Comment by udos** [comment]
I was wondering regarding this myself... but I was able to run the tutorial without any errors.

**Comment by jonatasbaldin** [comment]
Hey there, thanks for the comment.

HowToGraphQL is a bit stale now. Since the tutorial is running correctly, I'll just close this for now.

Cheers!
