### ISSUE TITLE
Could update prisma-client instead of prisma binding in Node tutorial? @mairatma

### ISSUE THREAD

**Issue by zwl1619** [howtographql/howtographql#801]
Hi @mairatma
Could update prisma-client instead of prisma binding in Node tutorial?

https://github.com/howtographql/howtographql/blob/master/content/backend/graphql-js/5-connecting-server-and-database.md

**Comment by nikolasburk** [comment]
Hey @zwl1619, the Node tutorial just got updated to use the Prisma client 🙂
