### ISSUE TITLE
getting "No Node for the model User with value [object Object] for id found." in the Authentication lesson

### ISSUE THREAD

**Issue by mogarick** [howtographql/howtographql#807]
Hi, 
I followed the tutorial but I'm getting an error when trying to add the link after executing de signup mutation. I'm not sure if there's a mistake in the tutorial or I missed something.

this is what I sent for signup
``` graphql
mutation {
  signup(
    name: "Ricardo"
    email: "ricardo@graph.cool"
    password: "graphql"    
  ) {
    token
    user {
      id
    }
  }
}
```
I got this response:

``` graphql
{
  "data": {
    "signup": {
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjam5odzdwdGwzajMzMGI5NHl1Nm5vM2gwIiwiaWF0IjoxNTQwMDY3MTQ0fQ.yONXlmgzopksnENlnXIubNawVoyWHSPjdgbIDOU456c",
      "user": {
        "id": "cjnhw7ptl3j330b94yu6no3h0"
      }
    }
  }
}
```

I copied the token and added to the headers in a new tab.
I executed the next mutation from that new tab:

``` graphql
mutation {
  post(
    url:"www.graphql-europe.org"
    description: "Europe's biggest GraphQL conference"
  ) {
    id
  }
}
```
and this is the error I got: 

``` graphql
{
  "data": null,
  "errors": [
    {
      "message": "No Node for the model User with value [object Object] for id found.",
      "locations": [],
      "path": [
        "createLink"
      ],
      "code": 3039,
      "requestId": "us1:api:cjnhyieez3qm10b943qtxee1d"
    }
  ]
}
```

I have no clue about why is this error happening (I'm new on this graphql thing). The user is succesfully created but the link is not.

Thank you in advance

**Comment by mogarick** [comment]
I found the cause. 
solved the problem. ` jwt.verify` returns this object:

``` js 
{
  "userId": "cjnhw7ptl3j330b94yu6no3h0",
  "iat": 1540067144
}
```
and `postedBy` expects only the userId string so it looks you need to update this piece of code:

``` js
function getUserId(context) {
    const Authorization = context.request.get('Authorization');
    if(Authorization){
        const token = Authorization.replace('Bearer ', '');
        const userId = jwt.verify(token, APP_SECRET);
        return userId;
    }
```
to 

``` js
function getUserId(context) {
    const Authorization = context.request.get('Authorization');
    if(Authorization){
        const token = Authorization.replace('Bearer ', '');
        const {userId} = jwt.verify(token, APP_SECRET);
        return userId;
    }
```
or any other option that takes into account the fact that you only need the userId from the jwt.

**Comment by swcarlosrj** [comment]
@mogarick thanks! Would you mind to open a PR with the proposed solution & please, reference it here?

**Comment by swcarlosrj** [comment]
Thanks @mogarick for opening this issue 😄. it should be fixed. Closing this!
