### ISSUE TITLE
Can't get a score of 100% 😭

### ISSUE THREAD

**Issue by ratskin** [howtographql/howtographql#813]
So, I just completed the tutorial for Node. I got to the last step - [summary](https://www.howtographql.com/graphql-js/9-summary/), but when I click "Go to next chapter" it doesn't update my completion percentage. See screen shot bellow:
<img width="1680" alt="screen shot" src="https://user-images.githubusercontent.com/24547185/47498902-e4166b00-d85e-11e8-905b-563a18bde080.png">

Happy to provide more details, if you want. BTW, love the site! Thanks for an amazing job! 10/10

**Comment by swcarlosrj** [comment]
#788 related

**Comment by swcarlosrj** [comment]
Thanks @ratskin for opening this issue 😄. It should be fixed. Closing this!
