### ISSUE TITLE
Failed installing prisma server with npm

### ISSUE THREAD

**Issue by pycloux** [howtographql/howtographql#816]
Hello,

I am at this step : https://www.howtographql.com/react-apollo/1-getting-started/
npm : 6.4.1
node : v8.12.0

When I run npm install in the server directory, here is what I get:

```
$ npm install
npm WARN deprecated apollo-codegen@0.19.1: The 'apollo-codegen' command has been replaced with the more-powerful 'apollo' CLI. Switch to 'apollo' to ensure future updates and visit https://npm.im/apollo#code-generation for more information.
npm WARN deprecated apollo-upload-server@5.0.0: Please migrate to https://npm.im/graphql-upload (see https://git.io/fADhl).
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

```

In the logs:
```
2595 silly saveTree |     `-- ultron@1.1.1
2595 silly saveTree `-- prisma@1.12.0
2596 verbose stack ZlibError: zlib: unexpected end of file

```

Tried to clean, to remove locks, etc.
I'll try with YARN but the tutorial stated that I could use npm ...

**Comment by pycloux** [comment]
Looks like it is working with yarn (at least until the step where it failed with npm).
I suggest to modify the tutorial to make the use of yarn mandatory.

**Comment by Reiahx** [comment]
did you try running with escalated privileges? i.e. sudo npm install?

**Comment by pycloux** [comment]
Hi,

I should have said that I was running windows. Not really usual for me but installing node was really painful with  Centos. So I gave up :-)

Anyway I installed yarn and ran the tutorial and it worked. I would recommend making yarn mandatory for the tutorial. This is probably easier than fixing npm.

**Comment by swcarlosrj** [comment]
Thanks @pycloux for opening this issue 😄. Closing this!
