### ISSUE TITLE
Not found page in the "Common Questions" when clicking on "Graphcool’s permission queries" link

### ISSUE THREAD

**Issue by marcos8896** [howtographql/howtographql#819]
In the [Common Questions](https://www.howtographql.com/advanced/5-common-questions/) sections, there is a link called **Graphcool’s permission queries** which points to a "Not found" page 🤔.

![example](https://user-images.githubusercontent.com/22345533/47817996-aa40db00-dd1c-11e8-8a8f-a97792b78b3a.jpg)

The current Not Found page is this one:
![image](https://user-images.githubusercontent.com/22345533/47818109-fb50cf00-dd1c-11e8-8251-e3a6a1676a30.png)

**Comment by swcarlosrj** [comment]
Thanks @marcos8896 for opening this issue 😄. it should be fixed. Closing this!
