### ISSUE TITLE
Not shown < > (gt and lt symbols) and content inside in Angular-Apollo

### ISSUE THREAD

**Issue by Akay7** [howtographql/howtographql#823]
For example in section /angular-apollo/2-queries-loading-links/ not shown text between < > inside typescript code examples, then `this.apollo.watchQuery<AllLinkQueryResponse>({` rendering like `this.apollo.watchQuery({`.
Any ideas why `<and all code inside>` not rendered from markdown?

**Comment by swcarlosrj** [comment]
Thanks @Akay7 for opening this issue 😄. It'd be updated soon. Closing this!

**Comment by Akay7** [comment]
@swcarlosrj You are welcome. I will open a new issue if you do not fix that issue soon :smile: .

**Comment by swcarlosrj** [comment]
Totally fair 😂, you might wanna speed this up pinging the core contributors!
