### ISSUE TITLE
Can't get the right response from mutation in Graphcool Playground (Only shows ID, not description &  URL)

### ISSUE THREAD

**Issue by P2PMartin** [howtographql/howtographql#826]
Hi

I can't get it to show the right response in Graphcool Playground. It says this:

{
  "data": {
    "createLink": {
      "id": "cjo7bdjfc07020196t2iupjg5"
    }
  }
}

So it only gives me the ID, which it shouldn't and not the Description & URL.

Any suggestions?

Martin

**Comment by P2PMartin** [comment]
This is my input, i got permissions "in all Fields"

type File @model {
  contentType: String!
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  secret: String! @isUnique
  size: Int!
  updatedAt: DateTime!
  url: String! @isUnique
}

type Link @model {
  createdAt: DateTime!
  description: String!
  id: ID! @isUnique
  updatedAt: DateTime!
  url: String!
}

type User @model {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
}

**Comment by swcarlosrj** [comment]
@P2PMartin thanks! Would you mind to provide more info about in which tutorial it happens? If you made it work, would you mind to open a PR with the proposed solution & please, reference it here?

**Comment by swcarlosrj** [comment]
Thanks @P2PMartin for opening this issue 😄. Closing this!
