### ISSUE TITLE
Typo in graphql-elixir/1-getting-started.md

### ISSUE THREAD

**Issue by benbro** [howtographql/howtographql#828]
Typo in [1-getting-started.md](https://github.com/howtographql/howtographql/blob/master/content/backend/graphql-elixir/1-getting-started.md)
> At this point the database tables created, and the migrations and ***the*** have been run.

**Comment by swcarlosrj** [comment]
@benbro thanks! Would you mind to open a PR with the proposed solution & please, reference it here?
