### ISSUE TITLE
HSQL Playground has same port as hackernews app

### ISSUE THREAD

**Issue by edwin-hendriks** [howtographql/howtographql#831]
Thanks for the tutorial. It would be even better if some of its issues would be solved. In this case When you just finished the **Getting started** chapter and flow to chapter **Queries: Loading Links** the tutorial does not take into account that you just started the HSQL tutorial in the previous chapter and this by default runs on port 3000. Of course the hackernews app you are currently trying to create also runs on the same port. This results on a weird GET error which only shows on the browser. Nu further error information is given and it is therefore hard for someone to figure out that this is a port conflict. 

In my regard the simplest solution that worked for me was to:

1. Kill the app server process **yarn start** which is running in the root folder (in this case **...\hackernews-react-apollo**)
2. add a file called **.env** in the root folder (so ...\hackernews-react-apollo\.env) and fill it with:
`PORT=3001`
3. Restart the app server process by executing the command **yarn start** again. 

It should now be restarting on port 3001.

**Comment by swcarlosrj** [comment]
@edwin-hendriks thanks! Would you mind to open a PR with the proposed solution & please, reference it here?

**Comment by swcarlosrj** [comment]
Thanks @edwin-hendriks for opening this issue 😄. Closing this!
