### ISSUE TITLE
i would like to contribute to translation English to Korean.

### ISSUE THREAD

**Issue by LOGANLEEE** [howtographql/howtographql#833]
before doing it, 
i would like get permission :)

**Comment by LOGANLEEE** [comment]
Hello? 
just i want to know that if i translate it 
Then you guys will reflect to the site ?

**Comment by jonatasbaldin** [comment]
@nikolasburk, can u take a look on this one?

**Comment by LOGANLEEE** [comment]
well i'm still looking for an answer :(

**Comment by swcarlosrj** [comment]
@LOGANLEEE sorry for the late reply! It'd be awesome but unfortunately the current site doesn't support other languages, anyways we'll look into that & of course we'll let you know 😄

**Comment by Keemluvr** [comment]
I could contribute to the Portuguese translation if the opportunity arises. 😀
