### ISSUE TITLE
SimpleGraphQLServlet.java in graphql-java/1-getting-started.md disappeared

### ISSUE THREAD

**Issue by julisch94** [howtographql/howtographql#834]
_SimpleGraphQLServlet.java_ is not present anymore. Since [this commit](https://github.com/graphql-java-kickstart/graphql-java-servlet/commit/1f7a7a851582007024de9300ee010b03f61e2dff) the class has been renamed and heavily modified in **graphql-java-servlet**.

Therefore, [howtographql/content/backend/graphql-java/1-getting-started.md](https://github.com/howtographql/howtographql/blob/master/content/backend/graphql-java/1-getting-started.md) needs to be adapted.

**Comment by swcarlosrj** [comment]
Thanks @julisch94 for opening this issue 😄. Closing this!
