### ISSUE TITLE
Learning Sequence for Graphcool CLI Commands [0.5]

### ISSUE THREAD

**Issue by trautlein** [howtographql/howtographql#84]
On [the second lesson of the Graphcool tutorial](https://www.howtographql.com/graphcool/2-evolving-schema/) the `graphcool status` command is taught after the `graphcool push` command has likely been put into the learner's console. This might stop them from seeing what `graphcool status` will output. I think if you are going to include the `graphcool status` command in this tutorial, which I think makes sense, it'd be the best learning experience if they were introduced to it before they push their data off to the server.

I am willing to come up with a few changes here if you think this would be a good change.

**Comment by marktani** [comment]
Thanks for your feedback! 

> I am willing to come up with a few changes here if you think this would be a good change.

Yes that would be great!

**Comment by nikolasburk** [comment]
Thanks @trautlein, this was a great suggestion. I moved the hint about the `graphcool status` command right before the instruction to run `graphcool push` so people get the chance to try it out while there are still unsynced changes on the schema. 🙌

Let us know if you have more suggestions. You're of course also welcome to create a PR if you see anything that can use improvements :)
