### ISSUE TITLE
Authentication tutorial dealing with authentication failure

### ISSUE THREAD

**Issue by mrcasablr** [howtographql/howtographql#841]
New to GraphQL and Apolloclient. In the authentication tutorial, https://www.howtographql.com/react-apollo/5-authentication/  the tutorial always assumes that authentication is successful by returning a token. How is the authentication handled if authentication has failed and token is not returned?

**Comment by swcarlosrj** [comment]
Thanks @mrcasablr for opening this issue 😄. it should be fixed. Closing this!
