### ISSUE TITLE
Suggested improvement to tutorial wording for posted_by field

### ISSUE THREAD

**Issue by infostud** [howtographql/howtographql#843]
In "Links and Voting"
It is not clear that
posted_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)
is a class variable definition in the Link class.
When you say "And add the posted_by field at the very end:"
I did without indentation and my error was not apparent until I got to "Relay" and the last remark "The changes here are mostly on classes and methods names. You can now create links!"
I kept getting "graphql.error.located_error.GraphQLLocatedError: 'posted_by' is an invalid keyword argument for this function"
After making the change I needed to makemigrations and migrations and then it was fine.

**Comment by swcarlosrj** [comment]
Thanks @infostud for opening this issue 😄. it should be fixed. Closing this!
