### ISSUE TITLE
Broken link in "Core Concepts" lesson

### ISSUE THREAD

**Issue by bomjastik** [howtographql/howtographql#846]
On the ["Core Concepts"](https://www.howtographql.com/basics/2-core-concepts/) page there is a broken link in the first paragraph:

> We also prepared a sandbox environment for you, based on **[graphql-up](https://github.com/graphcool/graphql-up)**, that you can use to experiment with what you learn.

As I understand it should be now linked to [GraphQL IDE](https://github.com/prisma/graphql-playground) instead.

**Comment by swcarlosrj** [comment]
Thanks @bomjastik for opening this issue 😄. it should be fixed. Closing this!
