### ISSUE TITLE
Add Nest.js example

### ISSUE THREAD

**Issue by guledali** [howtographql/howtographql#853]

**Comment by swcarlosrj** [comment]
@guledali could you please provide more info about this issue?

**Comment by guledali** [comment]
Originally when I wrote this I thought having something like Nest.js in how to section would have been a great idea because it's full fledge MVC framework and I even bothered to reach out to people that made Nest.js and asking them if the could make tutorial

However now since prisma community is working on https://github.com/prisma/yoga2

**Comment by swcarlosrj** [comment]
@guledali thanks anyways. Closing this, I guess that'll be a yoga2 tutorial in the near future!
