### ISSUE TITLE
Allow CORS in Java GraphQL Jetty Server 

### ISSUE THREAD

**Issue by jpizagno** [howtographql/howtographql#855]
My apologies if this question has already been answered, or does not belong here.  

I am trying to query GraphQL (with MongoDB repository) in docker-compose via a ReactJS container, and getting this error in the ReactJS container:

```
Access to fetch at 'http://127.0.0.1:10001/graphql' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

I know GraphQL is working because when I open the GraphQL app on port 10001, I can run queries and mutations that are properly persisted/read to/from MongoDB container.

All three apps (ReactJS, GraphQL, MongoDB) are in docker-compose and are linked.  

Can somebody tell me how to allow the Java GraphQL to allow CORS?
(i.e. I have a GraphQLEndpoint.java class that extends SimpleGraphQLServlet, with @WebServlet(urlPatterns = "/graphql") )
 
I tried to set the Jetty Server parameters in WEB-INF/web.xml, but then GraphQL does not work.  

I see examples for allowing CORS in a Javascript server, but I would prefer to use Java.  

thanks in advance for any help

**Comment by swcarlosrj** [comment]
Thanks @jpizagno for opening this issue 😄. Please open this issue into it respective repository `graphql-java`. Closing this!

**Comment by ketankr9** [comment]
This issue does belong to this repository, please show how to add ```Access-Control-Allow-Origin: *``` in this project.
