### ISSUE TITLE
Issue with depreciated `graphql-yoga` replacement in the Node.JS/Express Tutorial

### ISSUE THREAD

**Issue by simonOptimizely** [howtographql/howtographql#857]
Following the NodeJS Tutorial and I've run into the following issue:

1. `graphql-yoga` is now depreciated, so it is advised to use `graphql-upload`
2. Having used this, when running the initial `src/index.js` check, it fails as there appears to be an issue with the `graphqlUploadKoa.js`

```
> xxyyzz1-21:hackernews-node xxyyzz1$ node src/index.js
> /Users/xxyyzz/hackernews-node/node_modules/graphql-upload/lib/graphqlUploadKoa.js:8
> const graphqlUploadKoa = options => async (ctx, next) => {
>                                          ^
> SyntaxError: Unexpected token (
>    at Object.exports.runInThisContext (vm.js:76:16)
```
It may be that the subsequent issue is directly related to the replacement dependency `graphql-upload`, however this will hamstring the entire tutorial if an adequate `...-yoga` replacement isn't provided.

**Comment by swcarlosrj** [comment]
@simonOptimizely thanks! Did you make it work? If that's the case, please open a PR with the proposed solution & please, reference it here!

**Comment by swcarlosrj** [comment]
Thanks @simonOptimizely for opening this issue 😄. It seems to be solved following the latest tutorial docs. Closing this for now, please, feel free to open an issue if you cannot make it work!

**Comment by lars-ewers** [comment]
@simonOptimizely can you provide any details how you solved the problem?
I am encountering the same issue on my apollographql deployment. I only have this problem on older android devices. Thanks!
