### ISSUE TITLE
Error related to the code segment in 3-mutations-creating-links documentation

### ISSUE THREAD

**Issue by wasuradananjith** [howtographql/howtographql#864]
The documentation says to register the new resolver Mutation as below.
![image](https://user-images.githubusercontent.com/25246848/51097540-ec8d9a80-17ea-11e9-842f-1580b6271e35.png)

But if I do like above, it gives an error like below in my code near buildSchema().
![image](https://user-images.githubusercontent.com/25246848/51097561-121aa400-17eb-11e9-8989-c214a88ad240.png)

I think the code segment in the documentation should change like below. 
```
private static GraphQLSchema buildSchema() {
        LinkRepository linkRepository = new LinkRepository();
        return SchemaParser.newParser()
                .file("schema.graphqls")
                .resolvers(new Query(linkRepository), new Mutation(linkRepository))
                .build()
                .makeExecutableSchema();
    }
```

**Comment by swcarlosrj** [comment]
@wasuradananjith thanks! Do you mind to create a PR with the proposed solution? Please, reference it here!

**Comment by wasuradananjith** [comment]
Thank you, I have created the PR https://github.com/howtographql/howtographql/pull/881 for this.

**Comment by swcarlosrj** [comment]
@wasuradananjith thanks 😄
