### ISSUE TITLE
Wrong prisma website link

### ISSUE THREAD

**Issue by lovubuntu** [howtographql/howtographql#868]
In the summary page, instead of routing to prisma site (https://www.prisma.io) we are redirecting to Localization Enterprise eXchange (https://www.prisma.com).

File: howtographql/content/backend/graphql-js/9-summary.md

**Comment by swcarlosrj** [comment]
@lovubuntu thanks! thanks! Would you mind to open a PR with the proposed solution & please, reference it here? I'd great to have your 1st contribution, hopefully the first of the many 😄

**Comment by swcarlosrj** [comment]
Thanks @lovubuntu for opening this issue 😄It should be fixed. Closing this!

**Comment by lovubuntu** [comment]
> @lovubuntu thanks! thanks! Would you mind to open a PR with the proposed solution & please, reference it here? I'd great to have your 1st contribution, hopefully the first of the many 😄

That'd've been awesome but I didn't see the notification though 😞 
Will look for ways to help in future if I can contribute to this project for sure 👍
