### ISSUE TITLE
Getting started section Mutation does not work

### ISSUE THREAD

**Issue by reginanurieva** [howtographql/howtographql#869]
In the getting started section of the How to GraphQL after running the following mutation in the Playground 
`mutation {`
  `prismaLink: post(`
    `description: "Prisma replaces traditional ORMs and makes it easy to build GraphQL` `servers 😎",`
    `url: "https://www.prisma.io"`
  `) {`
  `  id`
 ` }`
 ` apolloLink: post(`
   ` description: "The best GraphQL client for React",`
   ` url: "https://www.apollographql.com/docs/react/"`
 ` ) {`
  `  id`
 ` }`
`}`

and after checking the query 
`{`
`  feed {`
  `  links {`
  `    id`
    `  description`
    `  url`
`    }`
`  }`
`}`

instead of getting back the following 

`{`
  `"data": {`
   ` "feed": {`
    `  "links": [`
    `    {`
      `    "id": "cjcnfwjeif1rx012483nh6utk",`
      `    "description": "The best GraphQL client",`
 `         "url": "https://www.apollographql.com/docs/react/"`
     `   },`
     `   {`
       `   "id": "cjcnfznzff1w601247iili50x",`
      `    "description": "Prisma replaces traditional ORMs and makes it easy to build GraphQL servers` `😎",`
     `     "url": "https://www.prisma.io"`
    `    }`
  `    ]`
 `   }`
`  }`
`}` 
I got back an error 
`{`
`  "data": null,`
 ` "errors": [`
`    {`
  `    "message": "Field 'count' of type 'Int' must not have a sub selection. (line 4, column 7):\n    `  `count {\n      ^",`
    `  "locations": [`
 `       {`
    `      "line": 2,`
 `         "column": 3`
   `     }`
 `     ],`
`      "path": [`
`        "feed"`
 `     ]`
 `   }`
`  ]`
`}` 

I'm unsure why I got null in the data field. 
Thank You!

**Comment by JoshuaBrigati** [comment]
@reginanurieva Any luck yet?

**Comment by JoshuaBrigati** [comment]
Alright, @reginanurieva I found a solution. Not a great one but a solution nonetheless. 
I cloned `https://github.com/howtographql/react-apollo/` and copied the server folder from that to the tutorial folder. It works for me now.

**Comment by j-Kode** [comment]
There seems to be an issues withe the count aggregate. I was having a similar issue with the following code
`const count = await context.prisma
    .linksConnection({
      where: {
        OR: [
          { description_contains: args.filter },
          { url_contains: args.filter },
        ],
      },
    })
    .aggregate()
    .count()`

taken exactly from the tutorial code, this would also cause the same error. I just replaced it with returning the length of the array based back from Prisma for a query. That works. Let me know if you have any questions

**Comment by reginanurieva** [comment]
Hello! Thanks for your help, I just saw ur email. I'm going to check it
right now. I'll let you know)))

**Comment by ztolley** [comment]
Same here

**Comment by swcarlosrj** [comment]
Thanks @reginanurieva for opening this issue 😄. It seems to be solved following the latest docs. Closing this for now, please, feel free to open an issue if you cannot make it work!
