### ISSUE TITLE
Says to add third link tag when there is only one

### ISSUE THREAD

**Issue by wizonesolutions** [howtographql/howtographql#894]
https://github.com/howtographql/howtographql/blob/master/content/frontend/react-apollo/1-getting-started.md

> Open public/index.html and add a third link tag right below the two existing ones that pulls in Tachyons:

Perhaps `create-react-app` changed, but I only see:

```
    <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" />
```

I just added the new line following the same pattern. Don't know it will break anything later, but I'll find out.

**Comment by jonatasbaldin** [comment]
Hey @wizonesolutions, thanks for the feedback.

Please update this issue if you find out anything about it. Also, feel free to open a PR with fixes if needed.
