### ISSUE TITLE
Minimum compatible ruby version

### ISSUE THREAD

**Issue by ConorSheehan1** [howtographql/howtographql#895]
It'd be nice to include a minimum ruby version in [1-getting-started.md](https://github.com/howtographql/howtographql/blame/03b9a54724e067ffd1f20b2806329cb2e9b1b6ff/content/backend/graphql-ruby/1-getting-started.md#L20).

For example, [4-authentication.md](https://github.com/howtographql/howtographql/blame/03b9a54724e067ffd1f20b2806329cb2e9b1b6ff/content/backend/graphql-ruby/4-authentication.md#L122) uses the safe navigation operator `&.` which was released in [ruby 2.3.0](https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/).
The [graphql-ruby repo](https://github.com/howtographql/graphql-ruby/blob/1b902a25d94b8d34f43043d6aa27f6512d27f023/.ruby-version#L1) itself uses ruby 2.4.1 

It's unlikely a new user would get such an old version of ruby that they couldn't run the tutorial, but it's a possibility.

Also possibly a mention of rvm or rbenv to manage ruby versions?

**Comment by jonatasbaldin** [comment]
Hey @ConorSheehan1, thanks for the feedback!

What do you think would be the best version to use? 

About using `rmv` or rbenv`, maybe that would add more complexity to the tutorial. I think using just one version across everything is better.

**Comment by ConorSheehan1** [comment]
> What do you think would be the best version to use?

The simplest solution would be to use the same version as graphql-ruby. i.e. ruby 2.4.1.

I think the lowest possible version would be good to give people a choice. i.e. >= ruby 2.x.
But that would require some testing. 

> About using `rvm` or rbenv`, maybe that would add more complexity to the tutorial. I think using just one version across everything is better.

If a user has some software that depends on an older version of ruby, and they upgrade to a newer version to try the tutorial, they may break that software. 

I wasn't suggesting adding a full set of instructions on setting up rvm or rbenv. Just a note that it's common practice to use something to manage and isolate dev ruby versions.

**Comment by RStankov** [comment]
@ConorSheehan1 thanks for pointing this out.

I added note that minimal version of the tutorial is 2.3.0 here 👉 https://github.com/howtographql/howtographql/pull/897

**Comment by jonatasbaldin** [comment]
Fixed at #897.
