### ISSUE TITLE
Overlapping text in "Big Picture" tutorial

### ISSUE THREAD

**Issue by AhmadElsagheer** [howtographql/howtographql#902]
Line 65 in the tutorial ["big picture"](https://github.com/howtographql/howtographql/blob/master/content/graphql/basics/3-big-picture.md) overlaps with the image caption making it unreadable in the [website tutorial](https://www.howtographql.com/basics/3-big-picture/).
```
// The above screenshot contains some of the resolved field names.
```

**Comment by jonatasbaldin** [comment]
Thanks for opening this issue.

Just fixed it at # #906.
