### ISSUE TITLE
Getting error when logging in: https://www.howtographql.com/graphql-js/6-authentication/

### ISSUE THREAD

**Issue by alocket2** [howtographql/howtographql#903]
I can do everything perfectly except login, I am getting the following error. I double checked everything and it is all the same.

`{
  "data": {
    "login": null
  },
  "errors": [
    {
      "message": "Variable '$where' expected value of type 'UserWhereUniqueInput!' but got: {\"email\":\"alockettjr@me.com\"}. Reason: 'email' Field 'email' is not defined in the input type 'UserWhereUniqueInput'. (line 1, column 8):\nquery ($where: UserWhereUniqueInput!) {\n       ^",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ]
    }
  ]
}`

**Comment by TamilarasuP** [comment]
@alocket2 I am facing this issue how did you resolve?

**Comment by shawnkoh** [comment]
Same issue here.
