### ISSUE TITLE
React + Apollo: Missing left menu in Playground

### ISSUE THREAD

**Issue by ohmoses** [howtographql/howtographql#911]
After I fetch the backend code and `yarn start` the backend server, I have the same issue as #423—the tutorial shows a menu in the Playground which lets the user choose between the app and database APIs. while my Playground doesn't have a menu.

![](https://screenshotscdn.firefoxusercontent.com/images/1e417180-dc28-4382-b86b-2e5efaf49e94.png)

**Comment by jonatasbaldin** [comment]
Hey @swcarlosrj, could you take a look into this one?

**Comment by sobrio** [comment]
Same problem here 

![55970043-1c7bfb00-5c7f-11e9-90df-aa0d41b41ae2](https://user-images.githubusercontent.com/3015939/56019712-a2db2000-5d05-11e9-98d2-17562658f5f8.png)

**Comment by Edrees** [comment]
Same issue and can't run: yarn run dev
![image](https://user-images.githubusercontent.com/10978103/56191605-efd43480-602c-11e9-982c-6de80055745b.png)

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @ohmoses and sorry for the delay! The tutorial was a little bit outdated, the backend project had been updated in the meantime and the `.graphqlconfig` had been removed. So it was actually correct that the sidenav didn't show. I just updated the tutorial to reflect the changes 👍

**Comment by sobrio** [comment]
@nikolasburk thanks

**Comment by Edrees** [comment]
@nikolasburk thank you 👍
