### ISSUE TITLE
Unlock the next chapter (subscriptions)

### ISSUE THREAD

**Issue by healthycola** [howtographql/howtographql#937]
Hello!

This has been such a great resource for me learning graphql. I really, truly appreciate all the hardwork that's been put into this.

I did have a question regarding subscriptions [here](https://www.howtographql.com/graphql-js/7-subscriptions/). Can someone explain the unlock the next chapter question here? I don't think anything related to that question was taught in the lesson?

I'm hoping this is the right forum to ask questions regarding the content of the tutorial. If not, please point me to the correct avenue.

Thank you!

**Comment by jonatasbaldin** [comment]
hey @nikolasburk, can u take a look into this?

**Comment by nikolasburk** [comment]
Thanks a lot for pointing this out @healthycola! I just adjusted the question in [this](https://github.com/howtographql/howtographql/commit/88b606e00f8dd03472f39dd892ba0ca8dd083ae8) commit.
