### ISSUE TITLE
Authentication in graphql-python - MIDDLEWARE configuration changed

### ISSUE THREAD

**Issue by nicostuhlfauth** [howtographql/howtographql#947]
In the [Tutorial](https://www.howtographql.com/graphql-python/4-authentication/)
```
MIDDLEWARE = [
    # After django.contrib.auth.middleware.AuthenticationMiddleware...
    'graphql_jwt.middleware.JSONWebTokenMiddleware',
[
```
throws

`UserWarning: Add 'graphql_jwt.middleware.JSONWebTokenMiddleware' to your GRAPHENE['MIDDLEWARE'] setting and remove it from your Django middleware classes.Please see the documentation for more information: <https://github.com/flavors/django-graphql-jwt#installation>`

It must be replaced by

```
GRAPHENE = {
    'SCHEMA': ...,
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ]
}
```

**Comment by jonatasbaldin** [comment]
Thanks for the heads up, just fixed at #948.

Cheers!
