### ISSUE TITLE
Node.js tutorial/ 7-subscriptions. Answer to question is wrong

### ISSUE THREAD

**Issue by vikthortt** [howtographql/howtographql#958]
In this chapter the last question is:
**Which of the following statements is true?**
and the options are:

- Subscriptions follow a request-response-cycle
- Subscriptions are best implemented with MailChimp
- Subscriptions are typically implemented via WebSockets
- Subscriptions are defined on the 'Query' type and annotated with the @realtime-directive

having the last one as the correct answer in the quiz, while the text of the lesson clearly states "Subscriptions are usually implemented with WebSockets" with no indication of @realtime-directive annotation

**Comment by svictoreq** [comment]
I created a [Pull Request](https://github.com/howtographql/howtographql/pull/961) updating the value of the answer.

**Comment by jonatasbaldin** [comment]
Thanks for the PR!
